### ISSUE TITLE
Does not work in Firefox Quantum

### ISSUE THREAD

**Issue by avdv** [sindresorhus/refined-github#1010]
I am using Firefox 57.0.4 (64-bit) and installed the Add-on.

Even after a restart, I see no changes on Github at all. 😭 

Is this Add-On supported on Firefox 57?

**Comment by avdv** [comment]
I have tried it at home again, but still no dice.

I do not see the "Trending" link in the top bar:

![topbar](https://screenshotscdn.firefoxusercontent.com/images/3f3887ea-b9a8-41e1-a5e6-31b1c0d7a0f8.png)

Also, clicking on the "refined" icon in the toolbar, it says that "Github Enterprise" is not yet supported, as if I am trying to use Github Enterprise features. Is this expected?

Also, when trying to enable the logging checkbox, this is not persisted - ie. when I close the dialog and re-open it, the checkbox is unchecked.

Is there anything I can do to debug this?

**Comment by ramlmn** [comment]
*Note: This may likely be not a bug in Firefox Quantum to be specific, it should affect all browsers.*

The whole problem comes from the following line:
https://github.com/sindresorhus/refined-github/blob/1d559b9262735366a2a2b6c4f19387bbb6aac71d/source/libs/utils.js#L16

## Explanation
### Stage 1:
When you install the extension for the first time, the options are not yet flushed into the browser storage. And when `new OptionsSync().getAll()` is called, is just returns an empty object (see image below. for the object to be filled with values, the user has to interact with the input fields atleast once).

### Stage 2:
And when you destructure the `options` object as `const {disabledFeatures, logging} = await options`, both the `disabledFeatures`, and `logging` variables would be `undefined`.

### Stage 3:
Finally when `disabledFeatures` is assumed to be an array, and `includes` is called on it, the browser throws an exception for each `enableFeature` call, effectively disabling all the features.

-----------------------------

![screenshot from 2018-01-19 23-33-20](https://user-images.githubusercontent.com/12368291/35165147-2cc5effa-fd73-11e7-9bdc-56d09e740634.png)

In the above image, only `logging` is available in browser storage, no sign of `disabledFeatures`, because I've only interacted with logging checkbox, and not even once with diabled features textarea.

----------------------------

Will submit a quick PR to migrate this issue! 😘

**Comment by ramlmn** [comment]
**Quick update**: Thought that `disabledFeatures` is an array, but realized it to be a string. Updated the PR accordingly.

**Comment by avdv** [comment]
@ramlmn Hey, thanks a lot, that seems to be spot-on! And, you taught me how to debug Firefox extensions! 😄
