### ISSUE TITLE
GitHub has new rules for the text color of labels?

### ISSUE THREAD

**Issue by shroudedcode** [sindresorhus/refined-github#1016]
I was just looking through an issues list and noticed something very strange. Labels that previously had a white text color now have a black text color.

![](https://user-images.githubusercontent.com/29176678/35171201-2cff7e9c-fd63-11e7-945a-60e27de09012.png)
![](https://user-images.githubusercontent.com/29176678/35171210-37952d02-fd63-11e7-9503-4592bcdf1cd4.png)

Has GitHub recently changed their algorithm for determining the text color? And should we **revert the old behavior**? I think both of the above labels have enough contrast with white text (especially the second one) and just look better.

![](https://user-images.githubusercontent.com/29176678/35171374-ec32a3de-fd63-11e7-862f-acaf4b900889.png)
![](https://user-images.githubusercontent.com/29176678/35171395-fb2077e0-fd63-11e7-990a-cf2f25ad490e.png)

*A bunch of [Refined GitHub's labels](https://github.com/sindresorhus/refined-github/labels) are also affected by this.*

**Comment by sindresorhus** [comment]
Let's give it a couple of days and see if they'll fix it themselves.

**Comment by sindresorhus** [comment]
And make sure to voice your concern here: https://github.com/support

**Comment by busches** [comment]
It's intentional https://twitter.com/github/status/954467266434945024

**Comment by bfred-it** [comment]
That makes no sense to me. Is it just me or “help wanted” now is considerably harder to read?

**Comment by shroudedcode** [comment]
> Is it just me or “help wanted” now is considerably harder to read?

No, I think so as well. In general I haven't noticed any improvements by this change, just colors that looked *out of place* or made the labels harder to read. 

What should we do about this? Add an option to set the preferred color contrast ratio? And by default revert it to the old one?

**Comment by bfred-it** [comment]
I think we should talk to GitHub about it, especially since they just made the change so they should be open to feedback.

**Comment by hkdobrev** [comment]
It seems to me that GitHub has changed it the defaults, but haven't retroactively updated colours on existing repositories. Look at the difference between "help wanted" in the screenshot above and the one on Twitter.

I have previously noticed that when you rename or change the background colour of a label, the previous instances of the label on issue/PR timelines remain the old name/colour. That's because they replicate the label state at the time instead of having a dynamic reference. This decision is fine for various performance reasons depending on the infrastructure.

However, what they did here is that they calculate the text colour of a label dynamically while showing the old saved background colour. In our case, we have probably modified the label background colours and that's why GitHub hasn't touched them. I like how readable the labels on GitHub's tweet are, there's nothing wrong with them. They just haven't replicated that properly across existing repos.

**Comment by bfred-it** [comment]
No, that's two separate issues:

- algorithm to determine the text color (black or white)
- base colors

Since the colors can be user-defined, the algorithm should pick the best text color in all scenarios. It's not happening here (forget about the caching, look a the [labels page](https://github.com/sindresorhus/refined-github/labels))

The new base colors have conveniently better contrast than the previous ones (with the new algorithm), but that shouldn't exclude the first point.

**Comment by hkdobrev** [comment]
I think they have just changed all `help wanted` labels to white text colour disregarding the current background 😞There are other such examples from the Twitter thread.

**Comment by hkdobrev** [comment]
It seems GitHub has addressed the issue or has any of the collaborators changed our label colours?

**Comment by bfred-it** [comment]
I did

**Comment by bfred-it** [comment]
Hey, look, they fixed them!

<img width="224" alt="white on green" src="https://user-images.githubusercontent.com/1402241/35498710-f892269a-0501-11e8-9602-cb177f1312bc.png">
