### ISSUE TITLE
Analytics?

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1039]
Should we have some anonymous analytics? We could collect the most-disabled features.

Alternatives to Google Analytics? Possibly with a public UI? I feel that there should be such a service for open source software.

**Comment by hkdobrev** [comment]
I've seen it done before including free open-source tools and it was either GA or custom built.

**Comment by Calinou** [comment]
I would rather not see analytics if possible – not only because of privacy issues, but also because I'm not convinced of the usefulness of automated (opt-out) statistics in open source projects; I believe that constructive feedback using GitHub issues or similar is more helpful to open source projects.

That said, [Matomo](https://matomo.org/) (formerly Piwik) is one of the more established open source analytics systems out there, it might be worth a look. If you end up adding analytics, please do make sure to add a way to opt out. :smiley:

**Comment by bfred-it** [comment]
I wouldn't use GA for privacy concerns also, but we could definitely run GA through a proxy (e.g. a now.sh server) to anonymize it. But AFAIK GA doesn't have a public console.

**Comment by hkdobrev** [comment]
@Calinou What are your issues with analytics if they are anonymised on the client? I just see your two reasons as one.

**Comment by bfred-it** [comment]
Eh. Not really useful either way
