### ISSUE TITLE
Display disabled features as list of checkboxes 

### ISSUE THREAD

**Issue by lex111** [sindresorhus/refined-github#1043]
How about showing a list of all the features in the form of checkboxes (or multiple select)? Checked checkboxes (feature) will be disabled, it's convenient and easy.

![image](https://user-images.githubusercontent.com/4408379/35471729-540df0d0-0372-11e8-9b9b-18019f0c5aee.png)

**Comment by bfred-it** [comment]
The file names are only really available to webpack, which conveniently sets them as function names and we don't have a full list of them anywhere, on any page, because each page will only have some functions.

In short, the only way to do this would be to create a webpack plugin to generate the list of `feature` files as `json` so it can be imported in `options.html`

**Comment by bfred-it** [comment]
If anyone wants to pick this up, have a look at the https://github.com/sindresorhus/refined-github/tree/webpack-4 branch, I think we'll **need** a plugin starting from webpack 4 since it doesn't seem to preserve the file names as function names anymore, which breaks the disabling altogether 😖

**Comment by bfred-it** [comment]
Not worth the effort. If you find a webpack plugin you can try sending a PR

**Comment by bfred-it** [comment]
Resent as https://github.com/sindresorhus/refined-github/issues/2040
