### ISSUE TITLE
Gist collection header should be the collection name

### ISSUE THREAD

**Issue by artivilla** [sindresorhus/refined-github#1100]
Maybe this is intentional by design but I thought the title/header should be the name of the collection, not the name of the first file in the collection. As an example, here's the public gist: https://gist.github.com/artivilla/ba1408aece35feb98e97c5aa2425e4e6.

Proposal:

<img width="1078" alt="editing_array_mutations" src="https://user-images.githubusercontent.com/2120159/36390708-f702ec08-1571-11e8-9332-053d18bbfc1b.png">

**Comment by bfred-it** [comment]
That is a weird choice, indeed, but the gist description can also contain links, so it might not always be suitable. Example: https://gist.github.com/bfred-it/cc0a7e2197b7b05b6727b9e8277c82c2

**Comment by artivilla** [comment]
So with respect to the interface, I meant `Gist description` should be at the top both in edit/view mode since you can have multiple files in a gist collection. In this example `array mutations` is only one file of the many you can edit/view.

https://cloudup.com/cUWi2vbY_V8

**Comment by bfred-it** [comment]
In your screenshot I don't see how we can sensibly move things around since "Editing array mutations" is a permalink, so we can't just replace it with text (that it can contain links). The only thing I could think of would be to drop that text altogether and use the gist ID as permalink.

<img width="504" alt="mockup" src="https://user-images.githubusercontent.com/1402241/36412271-0fe132a4-164c-11e8-8f43-cdd660828858.png">

If you have better ideas, mockup away! :)

Do you also want to change this in the [gist lists](https://gist.github.com/bfred-it/) and the [regular non-edit views](https://gist.github.com/artivilla/ba1408aece35feb98e97c5aa2425e4e6)

**Comment by artivilla** [comment]
Yes, I was expecting it to change across the board so the users mental model it to update/edit/view collections instead. Not sure how this can be implemented via css only. I posted the issue to github so ¯\_(ツ)_/¯ .

I think the gistID will make it unreadable.

**Comment by bfred-it** [comment]
Closing issue as request is unclear and no mockups were provided
