### ISSUE TITLE
Reactions - how to know which users are there?

### ISSUE THREAD

**Issue by pgorod** [sindresorhus/refined-github#1103]
Hi. For me, at least on Firefox, when I am looking at reactions and I hover,  I can't find a way to know the username.

I also tried clicking on the Avatars, expecting to maybe to go the user's page, but nothing happens.

Is it just for me? Or is this intended behavior? I value knowing _who_ reacted.

Thanks for you awesome add-on, by the way :+1:

**Comment by bfred-it** [comment]
I think we initially removed it because each of those avatars has its own tooltip, so in Chrome you'll see the username right over the user.

Firefox however doesn't allow `:hover` states on the avatars inside the Reaction button. Chrome does and you can even right click on the avatars and open their profile.

I restored the regular per-reaction tooltip in 6003f91

**Comment by pgorod** [comment]
Thanks!
