### ISSUE TITLE
Open "participating" notifications by default

### ISSUE THREAD

**Issue by krlmlr** [sindresorhus/refined-github#1143]
I love the "open notifications in tabs" feature, I'm switching from tracking e-mails to viewing GitHub notifications in the browser.

Most of the time I care about notifications for discussions I'm participating in (creator/mentioned/...). Would you be supportive of a tweak that selects the "participating" notifications by default when opening notifications? For now I'm working around with a bookmark. Thanks!

**Comment by shroudedcode** [comment]
While I understand why this feature could be useful, I don't think that the tabs should be opened when the user visits the notifications page. What if, for example, a user who doesn't know about this feature visits the notifications page, doesn't notice the tabs opening, later closes them to declutter his tabs and never sees the notifications again because GitHub thinks he has already seen them?

An alternative solution would be to add a small [![](https://user-images.githubusercontent.com/29176678/37095457-4fef6c8c-2216-11e8-8a3d-e73438717958.png)](https://octicons.github.com/icon/link-external/) icon next to the `Participating` tab on the left allowing the user to open all the issues he's participating in in new tabs. We could also allow this feature to be triggered using a special URL like `/notifications/participating?rgh-open-all=1` making it bookmarkable.

**Comment by bfred-it** [comment]
I think he just wants the bell icon to open `/notifications/participating` instead of `/notifications`. We can't do that and we don't add options like that. Refined GitHub only changes things to improve them, not as options (even though _improvements_ can be disabled)

**Comment by shroudedcode** [comment]
Oh, now I get it. I agree that this is out of scope for RGH.

@krlmlr You can also use a user script to accomplish what you want:

```js
document.querySelector('js-notification-indicator')
	.setAttribute('href', '/notifications/participating');
```

**Comment by bfred-it** [comment]
```js
// code golfing 😅
document.querySelector('.notification-indicator').href += '/participating';
```

**Comment by krlmlr** [comment]
Thanks, I'll try my luck at the other extension.
