### ISSUE TITLE
Long filenames in sticky diff header are pushing diff stat and options on new line

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#122]
See https://github.com/composer/composer/pull/4998/files and scroll to files with long filenames.

I suggest to use ellipsis in the path of the file when it is too long like GitHub does in some places.

Screenshot:

![screen shot 2016-03-31 at 00 16 09](https://cloud.githubusercontent.com/assets/506129/14157877/cf2f9b66-f6d5-11e5-98e1-1278131fa404.png)

**Comment by paulmolluzzo** [comment]
It'd make it a little more clear to keep the filename and collapse/truncate the directory structure like:

```
../../../../../autoload_files_functions_with_removed_extra.php
```

Usually I can find a file locally with some fuzzy finder if I have the filename, but the directory will have multiple files. Then show the entire file name on hover?

**Comment by hkdobrev** [comment]
@paulmolluzzo This looks like a relative path, but you don't know what's it's relative against.

Why not what GitHub does:

```
tests/.../autoload_files_functions_with_removed_extra.php
```

?

**Comment by paulmolluzzo** [comment]
That could work just as well, so if GH is using a similar pattern we might as well match it for consistency.

**Comment by DrewML** [comment]
I can take this. Do we always want to summarize the path as `${root}/.../${filename}`, or just in the scenario that the text is going to force a line-break?

**Comment by paulmolluzzo** [comment]
It's more complex to do, but really it should only truncate when it doesn't fit since it's a loss of info. It's not using a monospace font, but a character count should be a good estimate on whether it'll fit or not.

For another option I would guess anything over 3 or 4 directories deep won't fit. Maybe if splitting on `/` creates 3 or more strings we can use the pattern instead.

**Comment by DrewML** [comment]
If no one minds the extra hits to the DOM, we could try to calculate whether or not we need to truncate, and then apply our truncation logic (if necessary). I'm worried that, if we make an assumption about a static length, it may break for people using other extensions that change page widths, or those who are zoomed out a level or two.

```javascript
function maxPxAvailable() {
   const rightOffset = $('.toc-select').get(0).getBoundingClientRect().right;
   const leftOffset = $('.diff-toolbar-filename + .right').get(0).getBoundingClientRect().left;

   return leftOffset - rightOffset;
}
```

Basic workflow would be:

1. (Only when the value changes) Create a span with the filename, and temporarily append to the DOM with `position:absolute` and `visibility:hidden` so we can calculate the real width needed
2. Determine if the width of the element from 1 is > the width available in the sticky header (sample code above). If it _is_, use our logic to shrink down the filename.

Think this is overkill?

**Comment by paulmolluzzo** [comment]
Clever! Could you use the file name in the header of the files themselves to calculate the width without a virtual/hidden element? Alternatively, you could just put it in the right place and determine if it's longer than the container and shrink it in place. Since it'll be changing _right before your eyes_ maybe figure a way to animate it or something?

**Comment by DrewML** [comment]
Yeah, that should be able to work. I'd need to temporarily set the position to absolute to prevent the flash that would happen if the element was too long and forced the info on the right down to a new line, but that shouldn't be an issue (famous last words).

Also, thinking about this a bit more, `tests/.../autoload_files_functions_with_removed_extra.php` *may* not be the best solution. There are scenarios where the root folder won't be of much help.

As an example, consider the pattern where you have a component per dir, and they all have an `index.js` in the root.

```
root
├── component1
│   └── index.js
├── component2
│   └── index.js
└── component3
    └── index.js
```

In this scenario (pretend those paths are too long), all the files would be listed as `root/../index.js`.

Having said all that, I think there are 2 more things to note:

1. We can put a `title` attribute on the span to allow hovering to see the full filename
2. If the filename isn't clear from our truncated version, you can always scroll up to find the info you need

**Comment by paulmolluzzo** [comment]
> I'd need to temporarily set the position to absolute to prevent the flash that would happen if the element was too long

`overflow:hidden; max-width:50%` might work without position stuff.

**Comment by DrewML** [comment]
I don't think `overflow:hidden` will work in that case, because the element it's pushing is floated :(

**Comment by paulmolluzzo** [comment]
The `max-width` is what should prevent the forced wrapping, the `overflow:hidden` is to prevent the scrollbar if the content would be wider than the width.

**Comment by DrewML** [comment]
Just curious: Do you know of any advantages/disadvantages of either solution? I originally went with the hidden element solution [because it was what MooTools apparently used to do](http://stackoverflow.com/a/2923323). Trying to think out if there are any obvious gotchas that they may have known of. I'm open to doing it either way, but right now I'm slightly leaning towards the MooTools trick, purely because I assume it's been used in practice with success.

One small disadvantage I can see with the `overflow:hidden; max-width:50%` option is that it leaves the opportunity for someone to see a quick flash of different filenames while we're checking widths (haven't tested if it would be noticeable).

**Comment by paulmolluzzo** [comment]
The disadvantage to my suggestion is that "blip" you mentioned, for sure. You'd want to handle that nicely by either hiding it in place and then showing, or animating any change you make in the open.

A concept I had about how to animate it (mostly pseudo-code so try to bear with me) is like this:
1. Separate the pieces of the file name into spans like `<span>foo_dir/</span><span class="middle">bar_dir/</span><span class="middle">baz_dir/</span><span>super_long_file_name.js</span>`.
2. Add a CSS transition to the spans `transition: width 500s linear`
3. Put the whole thing in the container.
4. Check the length.
5. If it's too long, `$('span.middle').each(el => {el.innerHTML('.../')})`. That will make the width smaller (less content) and the transition will make it look nice as it changes.

You're already going for it, so at this point just do your thing and we'll see how it turns out.

**Comment by hkdobrev** [comment]
@paulmolluzzo If it works well enough, I'm against animating it. I really like the instant change as you scroll. It gives good instant feedback. What @DrewML had done in #128 works perfectly for me. I just wanted to check it out some more later.
