### ISSUE TITLE
Add "Possibly related issues" to existing issue pages

### ISSUE THREAD

**Issue by anandthakker** [sindresorhus/refined-github#1220]
From https://github.com/sindresorhus/refined-github/pull/1188#issuecomment-376210202:

It might be useful to have the "Possibly related issues" list available when _reading_ (in addition to composing) an issue, to help maintainers quickly find duplicates (or just related issues that may be relevant to discussion).

@sindresorhus notes:

> I think we should let this feature mature for a bit first though. I'm sure it could be smarter, and getting false-positives is a lot more annoying when reading issues than when writing.

**Comment by bfred-it** [comment]
I doubt we can have reasonable “related issues” list by just querying what we have on the fly (most likely the title). It may work when creating an issue since the intent there is to find *duplicates*, but *related* is different.

We should ask Algolia to do that, they already have an autocomplete plug-in for GitHub search and they might make more connections than we could with a couple API calls.

**Comment by sindresorhus** [comment]
GitHub just implemented showing related issues (https://github.com/sindresorhus/refined-github/issues/1610) when creating a new issue, so I think the best way forward is to submit feedback to them that it would also be useful to show related issues on existing issues too.

You can submit feedback directly on the new feature after activating it or sending an email to GitHub: support@github.com

**Comment by bfred-it** [comment]
I don't think we can offer good matches here, "related" needs some sort of "best match" algorithm that we can't offer.
