### ISSUE TITLE
Suggestion: Merge "Github Sync Fork"

### ISSUE THREAD

**Issue by lars18th** [sindresorhus/refined-github#1225]
Hi,

Perhaps you like to incorporate/merge/collaborate with:
https://github.com/whizzzkid/github-sync-fork-chrome-ext

Regards.

**Comment by shroudedcode** [comment]
I think that these kinds of features/bots/app are not really useful. If you always work on separate branches and only need to sync your fork's `master` whenever you start working on a new feature, creating a pull request for that seems kind of redundant because there can't be merge conflicts and the tests also can't fail unless you or the upstream repository owner has configured something incorrectly or has force-pushed.

I always use [these commands](https://help.github.com/articles/syncing-a-fork/) before I branch off from `master` before starting work on a new feature:
```
git fetch upstream
git checkout master
git merge upstream/master
```
When I think about it, I should probably set up an alias to make it even easier.

But that's just my opinion. I'm interested in what the other contributors think about this.

**Comment by bfred-it** [comment]
There’s no reason to merge extensions

**Comment by lars18th** [comment]
> When I think about it, I should probably set up an alias to make it even easier.

This is idea: have a button for it!

**Comment by shroudedcode** [comment]
@lars18th A button in the browser for a command that is run in the terminal? How's that supposed to work?

**Comment by lars18th** [comment]
Hi @shroudedcode ,

> How's that supposed to work?

See the referenced Chrome extension...
https://github.com/whizzzkid/github-sync-fork-chrome-ext/wiki/How-To-Use

It's very practical: When you work with forked projects, developing patches, you need to incorporate the last commits from the original repository _before_ start a new branch for a new branch. With the button provided by this extension all is automatic. You pick the button, and the `master` in your fork is synced with the `master` in the source.

**Comment by shroudedcode** [comment]
Still, the only situation where this is really useful (useful enough to be added to this extension) is when you work entirely in the browser using GitHub's basic code editor. Whenever I work on a feature, I have my code editor and terminal open anyway, so running the command is really not inconvenient.

Look, I'm not saying that the extension you mentioned is bad and can't be useful to anyone. I just don't think it's worth merging it into Refined GitHub since everyone who really wants to use this feature can just install the extension.
