### ISSUE TITLE
Upload icon missing

### ISSUE THREAD

**Issue by krlmlr** [sindresorhus/refined-github#1242]
From https://github.com/sindresorhus/refined-github/issues/1179#issuecomment-378730057:

![screenshot from 2018-04-04 21-51-54](https://user-images.githubusercontent.com/1741643/38334030-8b058946-385a-11e8-8945-ee6527d57052.png)

Workaround: Ctrl + U.

**Comment by yakov116** [comment]
@krlmlr just drag and drop or cntrl + V

**Comment by krlmlr** [comment]
I don't understand it: the icon is visible in #693!

![screenshot from 2018-04-04 23-15-05](https://user-images.githubusercontent.com/1741643/38335269-10e60024-385e-11e8-89fa-3acc537a17c0.png)

I'm happier with Ctrl + U, I tend to avoid file managers and the mouse but the "pick a file" dialog works for me.

**Comment by notlmn** [comment]
Hey, I figured out the three problems with the upload button.

### Problem 1: No upload button
GitHub doesn't send the markup for the toolbar in the response, the toolbar is added dynamically later to the form. `addUploadButton()` executes before the toolbar is even available, so no button.

### Problem 2: Upload button on some pages
This happens for ajaxed pajes. The ajaxed pages do contain the markup for toolbar, so after `ajaxedPagesHandler()` call, the upload button is added to the form. This is the reason for @krlmlr seeing icon on the other page, because it being an ajax loaded page.

### Problem 3: Broken upload button
Even if the button is added as in problem 2, the `delegate()` calls are invoked as `addUploadBtn()` is called in the `ajaxedPagesHandler()`, adding new listener for each back and forth ajax loads.

-----

@bfred-it I already have a working solution, I'll send a PR if it is ok.

**Comment by krlmlr** [comment]
Thanks for looking into it, I don't remember seeing any problems with uploading content (and also forgot about Ctrl+U by now ;-) )

**Comment by ShalokShalom** [comment]
This is still broken for me. No upload button and no option to toggle (so far as I can see) to bring it back, how it was before. Uploading images is something that happens quite frequently, I doubt it's very beneficial for the add-on to hide that feature so much. Tons of people have zero reason to hit Ctrl+U

**Comment by bfred-it** [comment]
The button was dropped. Refer to https://github.com/sindresorhus/refined-github/issues/2014
