### ISSUE TITLE
Use native GitHub hovercards on reaction avatars

### ISSUE THREAD

**Issue by j-f1** [sindresorhus/refined-github#1286]
Currently, the avatars displayed next to reactions use GitHub’s old-style hovercard with just the user’s name:

![screenshot 2018-04-25 at 9 41 12 am](https://user-images.githubusercontent.com/25517624/39249643-1802c0f8-486d-11e8-9dc6-bc13614db40d.png)

However, avatars on GitHub now use this hovercard:

![screenshot 2018-04-25 at 9 49 56 am](https://user-images.githubusercontent.com/25517624/39250044-11b19386-486e-11e8-8450-14257530dc0a.png)

Would it be possible to use this hovercard on reactions?

**Comment by hkdobrev** [comment]
This could work for 1 person, but we need to show a list of people who reacted.

**Comment by j-f1** [comment]
Why not show the hovercard for each person only when hovering over their avatar?

**Comment by bfred-it** [comment]
I’d go the opposite way actually because Firefox does not support hover on elements inside the buttons. This led to us restoring the single tooltip with all the names and now it looks like that with two tooltips. 

Do you know if there’s a way to see a list of all the people who reacted? Not that any of this is particularly useful information anyway…

**Comment by sindresorhus** [comment]
Going to pass on this. The avatars are just meant to give an quick indication whether there are people you know that voted, not as a means of discovering new people. I would recommend submitting a feature request to GitHub instead to improve showing the people that voted natively: support@github.com
