### ISSUE TITLE
Insert code button is missing in comment form

### ISSUE THREAD

**Issue by AlexByte** [sindresorhus/refined-github#1368]
With extension:

![image](https://user-images.githubusercontent.com/25251772/41131125-ab72a4bc-6ac2-11e8-8598-2b8913e19fd3.png)
Without:

![image](https://user-images.githubusercontent.com/25251772/41131157-dac557dc-6ac2-11e8-81a7-7f31787d77dd.png)

**Comment by busches** [comment]
This is working by design, see comments here https://github.com/sindresorhus/refined-github/issues/779#issuecomment-343645968

If you absolutely want them back, you can override these lines with some CSS in the extension options. https://github.com/sindresorhus/refined-github/blob/master/source/content.css#L107-L112

**Comment by bfred-it** [comment]
Buttons that can be replicated via keyboard have been removed. For code it’s best you just type \`\`\`
