### ISSUE TITLE
Feature Request: Quick comment resolve button

### ISSUE THREAD

**Issue by tgolen** [sindresorhus/refined-github#1396]
This is related to https://github.com/sindresorhus/refined-github/issues/1056 and is now possible with the new minimize comment feature that GH added https://blog.github.com/2018-04-18-new-tools-for-open-source-maintainers/

# Problem
It takes 5 clicks to hide a comment.

# Solution
Add a button here that lets you hide a comment as "resolved" with a single click.

![image](https://user-images.githubusercontent.com/1228807/42229355-84bb473a-7ea3-11e8-86a8-5ed6442a1c17.png)

The button could be called `Resolve Comment` or simply `Resolve` to save space.

**Comment by notlmn** [comment]
This is already being discussed in #1268, to make it 2 clicks.

**Comment by tgolen** [comment]
Ah, I see. Thanks for pointing that issue out to me. 2 clicks is better than 5, but 1 is better than 2! If the options discussed in that issue were visible on hover, that could remove one of the clicks to bring it back to 1.

For example, the dropdown menu could be changed to show on hover, and then the quick options could be part of the dropdown.

**Comment by notlmn** [comment]
All the actions would just not fit on the header, adding only one action on the header and leaving the rest is a problem by itself because now you are discussing which action is important, all of them are, each within its own context.

These actions are kind of destructive, one may need to think twice before applying an action. Making them a one click action is a dangerous thing, anything can happen by accident. Having a minimum of 2 clicks IMO is the good thing to do.

**Comment by tgolen** [comment]
Yeah, that's fine. I'd be happy with 2 clicks! I can make my own extension
for adding 1 click buttons.

**Comment by bfred-it** [comment]
Closing this, it can be continued in https://github.com/sindresorhus/refined-github/issues/1268
