### ISSUE TITLE
"Enable extension on this domain" doesn't show whether it's enabled

### ISSUE THREAD

**Issue by mehul0810** [sindresorhus/refined-github#1509]
## Proposed Solution
I think by default the extension should be enabled for github.com domain and the `Enable Refined Github on this domain` option on right clicking should appear on other domains only. Also, if a particular domain has enabled the extension then the option should say `Disable Refined GitHub on this domain` and clicking on that should disable extension on that domain.

![image](https://user-images.githubusercontent.com/1852711/45072718-df082b80-b0f9-11e8-8ed8-6a6bb8e2e620.png)

**Comment by bfred-it** [comment]
RGH is obviously already enabled on GitHub.com

What you're suggesting however is good. The `contextMenu` API lets us add a checkmark next to the item, so that would be a good way to show where it's enabled.

I haven't made this change because it means that the `contextMenu` needs to be instantiated for each tab (or something like that) instead of once.

Feel free to add the checkmark and thus the ability to _disable_ the domain as well to the original module: https://github.com/bfred-it/webext-domain-permission-toggle

I opened an issue there: https://github.com/bfred-it/webext-domain-permission-toggle/issues/4

**Comment by fregante** [comment]
This was fixed in https://github.com/fregante/webext-domain-permission-toggle/pull/8
