### ISSUE TITLE
Add a shortcut to Travis build (bypass Check tab)

### ISSUE THREAD

**Issue by Kocal** [sindresorhus/refined-github#1620]
Example of pull requests with Travis PR/Branch Checks: https://github.com/Kocal/semantic-release-preset/pull/7 and https://github.com/Kocal/semantic-release-preset/pull/4.

#### The problem

Before GitHub Checks, we had the possibility to directly go on Travis website by clicking on `details` here:

![selection_999 195](https://user-images.githubusercontent.com/2103975/48411735-bbd5aa00-e742-11e8-9c80-dde19f9939f3.png)

Now we should make 3 or 4 clicks and it's really boring:

![selection_999 194](https://user-images.githubusercontent.com/2103975/48405857-6cd44880-e733-11e8-8a12-ebfcb4e9f850.png)

![selection_999 196](https://user-images.githubusercontent.com/2103975/48405862-6e9e0c00-e733-11e8-8820-eb834d3d2418.png)

![selection_999 197](https://user-images.githubusercontent.com/2103975/48405865-71006600-e733-11e8-9f04-78b2b8065578.png)

#### Suggestion

The big issue here is to retrieve Travis build URL. I don't know if it's possible to do through GitHub v3/4 API, but we can do:
- For each Travis Checks:
  - Extract `a.status-actions[href]` value
  - Make a XHR request
  - Parse the response body and find the `<a>` containg `View more details on Travis CI`, and extract `href` value

I have three suggestion at the moment. 

#### Visual update

I have three ideas on how to exploit Travis url.

Completely replace `Details` link, easy and clean:
![selection_999 202](https://user-images.githubusercontent.com/2103975/48411882-3dc5d300-e743-11e8-9887-7f180b5a3468.png)

Make `Travis CI - ...` a link, less easy, would break CSS:
![selection_999 199](https://user-images.githubusercontent.com/2103975/48406427-bb361700-e734-11e8-9ca4-400963de8244.png)

Or create a new link and put it aside `Details` link, hard and horrible to see, would break some CSS too:
![selection_999 200](https://user-images.githubusercontent.com/2103975/48406431-bc674400-e734-11e8-9982-46145b662765.png)

Thanks

**Comment by bfred-it** [comment]
Can you add a link to a repo with checks? I haven't seen any yet

**Comment by Kocal** [comment]
Ah yes, added in OP.

**Comment by hkdobrev** [comment]
👍 I haven't seen one good thing from the introduction of Checks on GitHub. The URLs are strange, you cannot get back to the PR easily from some of the check pages. It's extremely frustrating you cannot get quickly to a failing build.

Until recently, we had both and we just needed to remember which name of the CI status was the old one without the Checks so we can click on it to go to the build URL. Now, when this is removed, I'm only using the CLI or nervously clicking 2-3 times to go to the build.

If it's quick to do a XHR request on hover/click, this could be become even better than before as we could extract the specific jobs from the Checks HTML (referencing Travis CI with one build and multiple jobs). However, the problem is the HTML of the Checks page is different for each service, but I guess supporting Travis CI would cover the majority.
