### ISSUE TITLE
Show number of closed issues in GH Labels view

### ISSUE THREAD

**Issue by nektro** [sindresorhus/refined-github#1645]
Current Behavior:
`13 open issues and pull requests`

Desired Behavior:
`13 open issues and 25 closed issues`

**Comment by bfred-it** [comment]
I think this would result in a relatively heavy GraphQL query because it has to query:

- up to 25 labels per [page](https://github.com/facebook/react/labels)
- up to dozens of issues per label (filtered by status)
- up to dozens of PRs per label (filtered by status)

And then count their IDs (because we'd get 2 lists of IDs for each label)

On [this page](https://github.com/facebook/react/labels) we'd make 20 queries (in one) and receive 462 IDs split among them (a bit of an edge case, admittedly, but possible)

It'd be nice to ask GitHub directly.

**Comment by bfred-it** [comment]
Ohhh wait. You don’t want to split issues and PRs, you want opened and closed. 

Can’t do. The closed issues can be hundreds per label and they’re paginated 100 at a time. Even heavier.
