### ISSUE TITLE
Preview when editing .md file

### ISSUE THREAD

**Issue by ps-gssleap** [sindresorhus/refined-github#1704]
In pull requests, GitHub provides a MarkDown preview tab when writing a comment or issue. That isn't available when editing a file in the repository, though, even when the file is README.md (which you'd think they'd recognize). Could you make the file editor act like the comment/issue editor when the file being edited ends in .md?

**Comment by bfred-it** [comment]
This would have to be a hack that'd have to steal the `New Issue`'s preview form (and authenticity token) to achieve the effect.

The feature should probably be its own extension (or ask GitHub, it sounds pretty straightforward)

**Comment by notlmn** [comment]
@ps-gssleap What exactly are you referring to? Because I do see "preview" tab while editing "readme.md".

|Source repo|Forked repo (not readme)|
|-|-|
|![image](https://user-images.githubusercontent.com/37769974/51163820-feda0800-18c0-11e9-8dba-8d7325a4c4bb.png)|![image](https://user-images.githubusercontent.com/37769974/51163857-23ce7b00-18c1-11e9-8707-27e9d69cbabf.png)|


GitHub provides preview tab everywhere you write Markdown, can you provide a screenshot where you are not seeing the preview tab?

**Comment by ps-gssleap** [comment]
I don't know how I missed that. I swear it wasn't doing it when I put this in, but now I'm questioning my sanity. Thanks.
