### ISSUE TITLE
RGH handles only one API Token

### ISSUE THREAD

**Issue by busches** [sindresorhus/refined-github#1714]
Currently if you use RGH on a different domain and GitHub, as soon as you provide a token, the other site no longer works (as expected).
```
features.js:79 RefinedGitHubAPIError: The token seems to be incorrect or expired. Update it in the options.
    at call (chrome-extension://mnoacfgkaplmhhcgdnekddifjfcllloj/content.js:2481:11)
    at <anonymous>
```
We need to add the option to specify what URL the token is for and only use it for that domain. This becomes more important if #1713 is merged.

**Comment by Chalarangelo** [comment]
I'd love to fix tht, too, but I don't really know where to start.

**Comment by bfred-it** [comment]
@busches refer to https://github.com/sindresorhus/refined-github/pull/1384#issuecomment-398375125

**Comment by simonkotwicz** [comment]
Do we need the option to specify the URL for a token or do we just need an extra field called `GHE personal token?
<img width="355" alt="Screen Shot 2019-05-18 at 12 43 31 PM" src="https://user-images.githubusercontent.com/12237902/57972582-9aac7b00-796a-11e9-850b-50f1e07ef835.png">

**Comment by bfred-it** [comment]
The further we go, the more I think this extension needs to be installed once per domain:

1. works with any number of Enterprise installations
2. it can be updated when GHE updates, rather than trying to keep RGH working with all versions: https://github.com/sindresorhus/refined-github/issues?q=label%3Aenterprise+label%3Abug

Given that GHE gets features later than regular GitHub, I expect most new features to cause errors so it's always best to wait.

Rather than adding a field, I'd rather see documentation explaining how to:

- clone and build the extension locally, on a 1 month delay (e.g. `HEAD@{ISO date 1 month ago}`)
- change the URLs in `manifest.json` so it applies to your GHE URLs instead of `github.com`
- merge in new changes from `origin` when the user wants to

**Comment by simonkotwicz** [comment]
I'm not sure that's the right solution since there are still a lot of new features added to `refined-github` that work with GHE and if there is a GHE fix you'd probably want to pick up that fix right away.

**Comment by bfred-it** [comment]
> There's only one open bug right now that with the GHE label.

That's because we had to fix (or ignore) all the others

**Comment by simonkotwicz** [comment]
Another option would be to support disabling some features in GHE (either by default by marking some features as targeted for public Github only or as an option) until they are properly supported in GHE (like for example `recently-pushed-branches-enhancements`). I don't think this is a huge deal though since you can already disable extensions (and will be even easier with https://github.com/sindresorhus/refined-github/pull/1780)

**Comment by bfred-it** [comment]
> Another option would be to support disabling some features in GHE

That only gives my suggestion more weight. You can disable all you want if some features don't work in your specific GHE installation, without further changes in Refined GitHub.

I don't use Enterprise at all so even if I wanted to I couldn't tell what works there and what doesn't.

**Comment by simonkotwicz** [comment]
I personally prefer having a single "copy" of the extension that updates itself and picks up the latest features and fixes for both public Github and GHE. The main issue is the token issue. I don't think adding a second token text field for GHE really clutters up the extension options?

**Comment by simonkotwicz** [comment]
I guess the question is what kind of PR would you accept to resolve this issue? Or maybe we need input from other people who use GHE?

**Comment by bfred-it** [comment]
No PR other than the tool I described probably, because once this is in, someone else will ask another field for their second GHE installation (see #1384)

**Comment by bfred-it** [comment]
An alternative solution would be to extend `webext-options-sync` to have per-domain storage and we’d have automatic per-domain tabs (created by Refined GitHub) in the options.

This is actually kind of possible since `webext-options-sync` lets you change the storage key (currently stored as `options` in `chrome.storage.sync`), we just need to ensure that:

- supported domains are automatically added to the options page
- the form updates correctly when the domain tab is changed (perhaps by cloning the form and replacing it)
- that migrations, defaults and any listeners work correctly and don’t just pile up when switching domain.  

https://github.com/sindresorhus/refined-github/pull/2111 contains code useful to generate those tabs (i.e. “what additional domains do we have permission to?”)
