### ISSUE TITLE
Linkifies branch references in pull requests doesn't work properly.

### ISSUE THREAD

**Issue by fvelasco1** [sindresorhus/refined-github#18]
We have the following naming convention for branching : feature/BA-1234 and every time I click on the branch reference I am redirect to the wrong place.

Example:
At moment the redirect link is: https://github.com/{GitUserName}/{RepositorieName}/tree/feature/BA-1234

And it should be: https://github.com/{RepositorieName}/{RepositorieName}/tree/feature/BA-1234

Thanks
Francisco

**Comment by sindresorhus** [comment]
> https://github.com/{RepositorieName}/{RepositorieName}/tree/feature/BA-1234

I doubt this is correct, you've listed the repo name twice.

**Comment by sindresorhus** [comment]
Our parsing probably doesn't take into account branch names with `/` in them. Would you be interested in looking into a fix?

**Comment by paulmolluzzo** [comment]
I can do this one. If @fvelasco1 is working on it already LMK

**Comment by sindresorhus** [comment]
@paulmolluzzo Go ahead :)

**Comment by paulmolluzzo** [comment]
OK, I see the issue, which is totally different than we were thinking. The issue is not the string splitting, and my Regex fix branch is off base. (Sorry about that.)

The issue is that if you're merging a PR in _your own repo_ there is no `username` in the blocks at the top, so there's no branch name to show.

@fvelasco1 can you please confirm you're noticing this on a repo you have push access to? (i.e. not a fork).

If that's the case it should really be that we test for the length of `parts` inside `linkifyBranchRefs` and assign accordingly. I'll be doing this in the same branch.
