### ISSUE TITLE
batch-open-issues causes line break in large repos

### ISSUE THREAD

**Issue by FloEdelmann** [sindresorhus/refined-github#1830]
When a repository has many open PRs, you have push access to it (so a batch checkbox is shown), the "Open all" link by the `batch-open-issues` feature causes  an ugly line break the PR list header:

![screenshot_2019-03-05_23-29-36](https://user-images.githubusercontent.com/202916/53842364-8a0d7b00-3f9f-11e9-92fc-8219a63c23e0.png)

Maybe it would be possible to replace the text with the [link-external octicon](https://octicons.github.com/icon/link-external/) to save some space.

The issues list does not have the "Review" filter, so it's not a problem there. Also, as soon as you tick a checkbox, there is plenty of space again, so the triage link text "Open in new tabs" (https://github.com/sindresorhus/refined-github/blob/master/source/features/batch-open-issues.tsx#L57) can remain unchanged.

Unfortunately, I can't share a link to the repo I discovered this issue with, as it's a private one (and you would need push access).

**Comment by bfred-it** [comment]
Almost happening here: https://github.com/facebook/react/pulls

<img width="994" alt="" src="https://user-images.githubusercontent.com/1402241/53854181-59f7c380-4003-11e9-8b18-a73891505bae.png">

But not happening because my checkbox is missing.

Before, I had suggested to use icons for some filters but they might look messy. The icon for `Open all` might not be clear of what it does (it generally doesn't stand on its own)

Perhaps the space between the filters could be reduced

**Comment by FloEdelmann** [comment]
Reducing `padding-left` / `padding-right` from `15px` to `12px` already makes a huge difference. I've opened PR #1833 with this fix.
