### ISSUE TITLE
Activity box looks chaos

### ISSUE THREAD

**Issue by ZYSzys** [sindresorhus/refined-github#1859]
GitHub's activity boxes are always the same width, but Refined GitHub's activity boxes' width change due to different kinds of activities

![Screen Shot 2019-03-14 at 9 19 45 PM](https://user-images.githubusercontent.com/23313266/54360877-cbd5aa00-46a0-11e9-846c-879f6bac3f45.png)

I think it's some kind of chaos, can we recover this ?

**Comment by bfred-it** [comment]
Since https://github.com/sindresorhus/refined-github/pull/1824

The only one _off-looking_ is the combo `X and Y starred 1 repository`, it wasn't meant to look like that. Only the last one kept the original style because there's more than one repo.

However the intent was just to make it more readable over the original suggestion:

<img width="634" alt="" src="https://user-images.githubusercontent.com/1402241/53782108-cf518e80-3f46-11e9-91c0-270055157803.png">

But to do that we can just make the whole feed's background white and it will be more compact, easier and _regular_.

PR welcome to undo 44bb7ee and apply the "white box" style on `.news` (I think)

**Comment by bfred-it** [comment]
@ZYSzys you were right. I just saw that the non-aligned avatars look bad even in the grouped events.

![54360877-cbd5aa00-46a0-11e9-846c-879f6bac3f45](https://user-images.githubusercontent.com/1402241/54401258-e8ee9500-4701-11e9-896b-bb43b771afe8.png)
