### ISSUE TITLE
Add way to load *all* comments when some are hidden due to number of comments

### ISSUE THREAD

**Issue by pnkfelix** [sindresorhus/refined-github#1892]
Look at https://github.com/rust-lang/rfcs/pull/2544

Scroll down the the "Load more ..." (below "NNN hidden items" for some NNN).

The link there only loads *some* of the comments. It would be great to have a way to load all of them (e.g. it would help for people who then use search to find text in the page).

(I did try Alt-click; it did not work for me in this context.)

**Comment by bfred-it** [comment]
This kinda makes sense because if I'm looking for something in those comments, chances are I want to check them all out. However we still need to limit this to, maybe 3 loads at a time, or else on the rare super-long discussion it might load too many pages nobody needs.

**Comment by pnkfelix** [comment]
Here’s maybe a simpler request: could we add a “load more ...” button that is always in the same (hopefully easily accessible) location, eg right below the description, and just grated out when all are loaded, so that the work flow for loading all comments doesn’t involve repeatedly searching for the link after each load, and instead one can just sit and hit the button in one place until it’s all done?

**Comment by bfred-it** [comment]
I don’t think that can integrate nicely with the design.

**Comment by bfred-it** [comment]
This can just be added with alt+click, it will probably look a lot like `infinite-scroll` but instead of using `IntersectionObserver` it just waits for the click event.

**Comment by JeanMertz** [comment]
Funnily enough, I came searching for this feature request for the _exact_ same reason (searching for a string in Rust RFCs, and not finding them because the comments are collapsed).

What makes this even more awkward is that searching for that string in the repo itself does return issues containing that string as a result, but then opening that issue, the string can no longer be found, because it is collapsed.

Personally, I'd like to have a "load all" button, or even better yet "always load all", but I can see how that might be detremental to page loading times (although the current workflow described by @pnkfelix of having to grep for "load more" clicking it, and repeating that several times takes way more time than an initial load all would cost).

**Comment by warpech** [comment]
I would really appreciate this feature. For now, here's a recursive user script that works for me: 

function loadAllComments() {
    var needRescheduling = false;
    var buttons = Array.from(document.querySelectorAll('button'));
    buttons.forEach((button) => {
        if (button.classList.contains('ajax-pagination-btn')) {
            if(!button.hasAttribute('disabled') && button.innerText === 'Load more…') {
                console.log("found", button);
                
                var event = new MouseEvent('click', {
                    bubbles: true,
                    cancelable: true
                });
                button.dispatchEvent(event);

                needRescheduling = true;
            }
            else if(button.hasAttribute('disabled') && button.innerText === 'Loading…') {
                console.log("waiting", button);
                needRescheduling = true;
            }
            else {
                console.log("unrecognized load more button", button);
            }
        }
    });
    if (needRescheduling) {
        setTimeout(loadAllComments, 500)
    }
    else {
        console.log("all comments loaded");
    }
}

loadAllComments();
```
