### ISSUE TITLE
Create a separate section of test files in PR 

### ISSUE THREAD

**Issue by prajapati-parth** [sindresorhus/refined-github#1910]
When reviewing a PR it would be really useful if all the changes in tests files would appear at the end or within a separate section. That way I could review the code first and then the tests.

**Comment by bfred-it** [comment]
This isn't feasible because GitHub decides the order in which files load (they are lazy-loaded a few at a time, especially in PRs that touch many files)

Refer to https://github.com/sindresorhus/refined-github/pull/1085 and all of the links at the bottom to see other possible solutions to move tests files _out of the way_
