### ISSUE TITLE
Auto-expand wiki "pages" table-of-contents

### ISSUE THREAD

**Issue by dwelle** [sindresorhus/refined-github#1916]
Github auto-folds longer (8+ items? dunno) wiki "Pages" table-of-contents when clicking through them. Would be nice to expand them on page load.

https://github.com/lodash/lodash/wiki

![image](https://user-images.githubusercontent.com/5153846/55864892-a348af00-5b7d-11e9-8220-7139fd64dc5a.png)

**Comment by fregante** [comment]
This doesn't seem to be getting any attention, but if you can submit a clean PR for this feature it probably can be added. It could use `sessionStorage` to remember it being open.

**Comment by dwelle** [comment]
I can no longer repro on lodash's wiki so I reckon this resolved itself :)

**Comment by zachsiegel-capsida** [comment]
For me, the "Pages" pane is not automatically expanded, even though I always expand it. Is there a setting for this?

Note that I do not have permissions in my org to view all repo settings, but I am making this wiki, and if there is a setting to auto-expand the "Pages" pane (the de facto table of contents) I will ask the admin to check it since it will definitely improve usability.

Thank you!
