### ISSUE TITLE
Fix auto-deploy

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#194]
It still displays version 1.0.1 in the Chrome web store.

Also noticed a thing. The auto-deploy creates new tags, but it doesn't update the version in manifest.json.

-

// @paulmolluzzo

**Comment by paulmolluzzo** [comment]
@sindresorhus so, two things. First, this won't auto-generate a tag, it just goes through the build step if it's a tagged version. Deployment is dependent on a purposeful release. Second, we still need to manually increment the version number (you would do it in the commit that gets tagged). I can write in a `sed` command to find/replace the version with the tag number, but it won't get committed by Travis CI back to the repo so that doesn't seem right.

What we'd want to do is modify the manifest when merging a PR (or commit directly to `master`) so we have a version. Or just make a commit like "Increment Version", then tag that commit and it'll release it that way.

Any thoughts? If you want to have hat `sed` in he deploy we can do that, but I'd prefer to deploy the  master version, not a modified version of master. It'll be confusing if they don't match.

**Comment by sindresorhus** [comment]
I'm good with the one tagging first doing a commit to increment the version. Don't think we need any automation for that.

**Comment by paulmolluzzo** [comment]
Try that now then. Just commit the increment on `master`, tag that commit and push. We're on v1.0.4, but with the popover we might want to do v1.1.0 since it's a function. If it doesn't work I can take a look tonight.

**Comment by sindresorhus** [comment]
Yes, seems to work now :)

@hkdobrev @DrewML Make sure bump the version in manifest.json and commit before tagging.

**Comment by paulmolluzzo** [comment]
Glad that worked and sorry I didn't make that clear before.
