### ISSUE TITLE
Edit-files-faster incompatible file icons extension

### ISSUE THREAD

**Issue by janat08** [sindresorhus/refined-github#1993]
[File icons for github, bitbucket, gitlab](https://github.com/xxhomey19/github-file-icon) causes two icons to appear if used with this feature. Maybe it could be integrated.

**Comment by sindresorhus** [comment]
We cannot possibly be compatible with all other extensions. You can disable the feature in the settings.

**Comment by bfred-it** [comment]
I thought about this when implementing the feature but the fix is too complex.

You could ask the other extension to:

- add a `octicon-file` class to their new icon
- place replace the existing `.octicon-file` element

So it should work regardless of the order in which the 2 extensions are executed
