### ISSUE TITLE
label/milestones buttons are messed up

### ISSUE THREAD

**Issue by tooomm** [sindresorhus/refined-github#2013]
(Newest Refined GitHub as of 2019-05-06)

The label overview is messed up. When you disable the extension it looks nicer actually. The `new` button position is different than for milestones.
I like the wider search box though 👍 

It looks to be all about the `New Label` button position.

Example: https://github.com/Cockatrice/Cockatrice/labels

label:
![label](https://user-images.githubusercontent.com/9874850/57217818-f6cee100-6ff3-11e9-97f9-92797937761d.png)

milestone:
![milestones](https://user-images.githubusercontent.com/9874850/57217813-f5051d80-6ff3-11e9-9faf-aec77d6802ad.png)

**Comment by bfred-it** [comment]
Due to:
https://github.com/sindresorhus/refined-github/pull/1886
https://github.com/sindresorhus/refined-github/commit/ca8b1e13f78c50a5a3283982fba41e8be49e12c0

Previous issues/PRs for this bug:
https://github.com/sindresorhus/refined-github/issues/1959
https://github.com/sindresorhus/refined-github/pull/1961
