### ISSUE TITLE
Drop `star-repo-hotkey` feature

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#2034]
How often do you star a repo that it justifies a shortcut? Thoughts?

**Comment by sindresorhus** [comment]
It's not a difficult feature to maintain though. I sometimes use it.

**Comment by MostHated** [comment]
I would not mind that. I star things I like constantly so that it helps shape my recommendations. What I would really like is something in between staring a repo and adding it to a bookmark in my browser. Perhaps having a Star as Favorite option. Then having an overlay drop down to quickly see and get to those or something similar. I have too many stars now to try and find specific things in the list of things I have stared. >_< Personal problems are hard, I guess.
