### ISSUE TITLE
Add option to display invisible/unprintable characters

### ISSUE THREAD

**Issue by waldyrious** [sindresorhus/refined-github#2150]
This is already mentioned as "Possible Future Additions" in #2073, but I thought it would be helpful to have a dedicated issue to track the implementation.

Ideally, it should be possible to visualize non-printable characters, control characters, zero-width spaces, etc. both when viewing the source code of a file, in code blocks in comments, and on diffs. Especially on diffs.

See for example [how Diffchecker does it](https://www.diffchecker.com/Q4ng5hqs) (note the red dot after "Lorem" on the left text box):

<img width="1125" alt="Screenshot 2019-06-11 at 17 52 42" src="https://user-images.githubusercontent.com/478237/59291013-cffa6f00-8c71-11e9-8a95-99ff974768d2.png">

**Comment by bfred-it** [comment]
I think should would belong to the same feature, which also has its own “tracking issue” here https://github.com/sindresorhus/refined-github/issues/588

**Comment by bfred-it** [comment]
Perhaps I’ll leave this open as a possible extension to that feature

**Comment by notlmn** [comment]
I left that out in the "possible future extensions" section because:
1. Way too many DOM nodes
1. No clear idea on what should be displayed in place of the character
   1. Like what Sublime shows!?
      ![image](https://user-images.githubusercontent.com/37769974/59326377-054f9d00-8d04-11e9-976f-ae1c25f0f857.png)
   1. Or use the [replacement character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character) like VSCode does
     ![image](https://user-images.githubusercontent.com/37769974/59326782-4300f580-8d05-11e9-95b5-4fd29b4ccfd7.png)
   1. Or [leave with what GitHub already shows](https://github.com/google/WebFundamentals/pull/6755/files#diff-76e41ac4fea56c88fec254a0edb06ce3L119) for **some** non-printable characters
     ![image](https://user-images.githubusercontent.com/37769974/59326917-b0148b00-8d05-11e9-9608-314b1659969b.png)
1. And finally what specific Unicode ranges to handle

**Comment by tonglil** [comment]
I actually like this feature, however maybe there is a way to break it into several options?
- [ ] show all whitespaces
- [x] show whitespaces other than spaces (the dots) `<- my preference`
- [ ] disable (uncheck option in prefs)

**Comment by allejo** [comment]
In addition to invisible/unprintable characters, could support for highlighting "smart quotes" also be added? Smart quotes can cause so many headaches.

**Comment by fregante** [comment]
Because of https://github.com/sindresorhus/refined-github/issues/2150#issuecomment-501133116, I think this would be best as its own extension/userscript
