### ISSUE TITLE
`content.css` not injected on GHE

### ISSUE THREAD

**Issue by ahatzz11** [sindresorhus/refined-github#2174]
This was initially discussed in https://github.com/sindresorhus/refined-github/issues/2170

Here is how the feature should work:
![](https://user-images.githubusercontent.com/1402241/60038476-08c12c00-96e7-11e9-8af2-99fe6d5e1e6f.gif)

Here is how it actually looks on GHE for me (in incognito with no other extensions)

![image](https://user-images.githubusercontent.com/6256032/60051439-a0e3f480-9698-11e9-9b0e-1c8229f6ba92.png)

**Comment by bfred-it** [comment]
This is a consequence of https://github.com/sindresorhus/refined-github/pull/2111

I’ll have to fix it

**Comment by bfred-it** [comment]
Great! The API I used to implement it in Chrome is broken for CSS: https://bugs.chromium.org/p/chromium/issues/detail?id=708115

Found on https://bugzilla.mozilla.org/show_bug.cgi?id=1323433 (Mozilla decided not to implement Chrome's API because it's broken and unused and they have a better one)

In my test, the CSS is injected only on the first load until you visit a different domain.

I'll see if I can work around this issue or if I have to go back to https://github.com/bfred-it/webext-dynamic-content-scripts/ in Chrome 🙄

**Comment by tknickman** [comment]
Confirmed this is fixed on GHE `v2.16.10`. Thanks so much!
