### ISSUE TITLE
Add Code Folding

### ISSUE THREAD

**Issue by axetroy** [sindresorhus/refined-github#2195]
> Code folding - the ability to selectively hide and display sections of a code - is an invaluable feature in many text editors and IDEs. Now, developers can utilize that same style code-folding while poring over source code on the web in GitHub. Works for any type of indentation- spaces or tabs.

ref: https://github.com/noam3127/github-code-folding

This extension has not been maintained for a long time. If it can be integrated into refined-github, it is definitely great.

**Comment by jerone** [comment]
There is a great UserScript from Mottie: https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-code-folding

**Comment by corysimmons** [comment]
Chrome Extension for cold folding: https://chrome.google.com/webstore/detail/github-code-folding/lefcpjbffalgdcdgidjdnmabfenecjdf

**Comment by waldyrious** [comment]
I'm curious about why this issue was closed, since there was no closing comment. Was the closure simply rejecting the possibility of directly importing the extension's code, or is the functionality itself undesired for Refined GitHub? Pinging @sindresorhus and @fregante who downvoted the opening comment.

**Comment by fregante** [comment]
Too complex to belong to Refined GitHub, it can live as it's own extension or userscript (and one already exists)

**Comment by waldyrious** [comment]
Gotcha! Thanks for the quick response.
