### ISSUE TITLE
Verified commits UI is a bit broken

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#220]
Reproducible on https://github.com/mathiasbynens/dotfiles/commit/adc5b5971649017f4de5b28074e51fcf67ac5b0d

![screen shot 2016-05-17 at 12 52 16](https://cloud.githubusercontent.com/assets/506129/15318318/3c22afec-1c2e-11e6-8f98-aa574e79b12c.png)

The space is too narrow for the Verified badge.

I guess we could restyle that a bit or probably remove the `.patch` and `.diff` links if they keep creating problems in that area.

**Comment by paulmolluzzo** [comment]
> I guess we could restyle that a bit or probably remove the .patch and .diff links if they keep creating problems in that area.

We might have discussed this before, but is there some icon we can use instead to save space? IIRC, we went through the process of shrinking padding to make more room there, so I don't know what else we can do except removing content or rearranging the whole area - like a two row layout.

I'm not keen on either scenario, but if anything gets removed it's the patch/diff links since they're added by RG.

Another idea: We can use keyboard shortcuts to switch to patch/diff of the commit and get rid of the links entirely. <kbd>+</kbd> for patch, and <kbd>=</kbd> for diff?

**Comment by hkdobrev** [comment]
I'm open to either shortcuts or icons. I really don't want some of the more obscure things which RG adds to break the default UI. Thanks for the PR, will test it out a bit later today.

**Comment by paulmolluzzo** [comment]
@hkdobrev if you can figure out some icon that works well, I'm for that as a solution too. @sindresorhus brought up the point that we might not remember the shortcuts, which is a valid concern. A link is better for something used infrequently.

**Comment by sindresorhus** [comment]
I'm still not sold on #224.

I managed to fix the UI by decrementing the font-size by one pixel for each element, the following:

- `.full-commit`
- `.full-commit .sha-block`
- `.commit .sha-block, .commit .sha`

<img width="1012" alt="screen shot 2016-05-31 at 15 13 13" src="https://cloud.githubusercontent.com/assets/170270/15667781/39cbdbf0-2742-11e6-86fc-e681d84ce650.png">

**Comment by paulmolluzzo** [comment]
I'm cool with @sindresorhus's solution if someone wants to make a PR.
