### ISSUE TITLE
Private orgs no longer showing lock icons

### ISSUE THREAD

**Issue by doms** [sindresorhus/refined-github#2210]
Hiya 👋 

I noticed this morning that private orgs no longer showed the lock icon on them. There was also a relevant error message saying that `publicOrgs.map is not a function`. After some digging, it seems as though the response from GitHub's API changed a bit(?), and some of the keys in the response aren't iterable.

<p align="center">
	<img width="529" alt="Screen_Shot_2019-07-07_at_3_21_53_PM" src="https://user-images.githubusercontent.com/8808097/60774636-e1496680-a0cb-11e9-8c66-42ac21d76fed.png">
</p>

I have a PR incoming with a suggested fix 😄

**Comment by jerone** [comment]
I can confirm this issue:
![image](https://user-images.githubusercontent.com/55841/60881828-d1a25d00-a246-11e9-8596-a24f88967b11.png)

It is because the API itself returns an `array`, which is [because of recent change](https://github.com/sindresorhus/refined-github/pull/2185/files#diff-3b4e3f99bb4c228c70878e87f3e7808cL103) now [spread to an `object`](https://github.com/sindresorhus/refined-github/blob/master/source/libs/api.ts#L107) in #2185. Resulting in using the `map` function on an `object` instead of the previous `array`.
