### ISSUE TITLE
Twitter account for Refined GitHub?

### ISSUE THREAD

**Issue by trivikr** [sindresorhus/refined-github#2242]
Hi,

I just started using Refined GitHub, and am very happy with the experience.
The updates maintained by @bfred-it in #1137 helped go through all updates to discover which ones can be used to improve productivity.

There's an official twitter account called [GitHub Changelog](https://twitter.com/GHchangelog) which tweets about anything that has been added/changed/deprecated/fixed or removed by GitHub.
It would be helpful if a similar Twitter account existed for Refined GitHub which tweets updates from #1137 and other important announcements.

Regards,
Trivikram

**Comment by jerone** [comment]
You can follow https://twitter.com/sindresorhus. He posts updates from time to time about Refined GitHub.

**Comment by sindresorhus** [comment]
Maintaining a Twitter account is a lot of work. We can do it if anyone volunteers.

**Comment by FloEdelmann** [comment]
I am following the [RSS feed of the master branch](https://github.com/sindresorhus/refined-github/commits/master.atom). That way, I always know what's new without having to follow all discussions.

There are tools that automatically fetch RSS feeds and post new articles to Twitter.

The commit messages are very technical though (and sometimes just meta stuff), so possibly not catchy enough to put it directly on Twitter.

**Comment by fregante** [comment]
There's no way to get a Twitter changelog account "for free": volunteers will eventually falter and automation is no better than the commits list.

You can follow either [Sindre's Twitter](https://twitter.com/sindresorhus) or [mine](https://twitter.com/fregante) for new features, or just the updates issue: https://github.com/sindresorhus/refined-github/issues/1137, but all of those will still only report new features rather than small changes.

Best case scenario is a bot on zeit/now that:

1. reacts to PR merges
2. skips meta commits (either by title or PR tag)
3. uses the `description` and `screenshot` fields for new features and the PR title for the rest

It doesn't sound like a lot of work, but it's only going to happen if someone writes that.
