### ISSUE TITLE
`mark-files-as-viewed` does not mark files loaded asynchronously

### ISSUE THREAD

**Issue by lukaszklis** [sindresorhus/refined-github#2252]
Whenever you have a PR which has only some files rendered in the PR diff mode, simply approving the PR without scrolling to the end of the PR will not mark all of the files changed as viewed. I would love to fix it myself (especially since I’ve introduced the feature), however in the next 1,5-2 weeks I won’t be able to find time. :(

**Comment by bfred-it** [comment]
Ouch, indeed. I don't think this is an easy feat because the button triggers a full page load.

Horrible solutions I can think of:

- Preload all the diffs every time you opening the Files tab, _just in case_ you approve it. Bad perf.
- Preload the diffs after Approve is clicked, but hold its submission until their down. Bad UX.
- After the submission, `fetch` the Files tab and do all that work in the background. May be difficult to implement.

**Comment by bfred-it** [comment]
I think the feature works even less often than that:

> the [Approve] button triggers a full page load.

This means that even the visible "Viewed" form submissions might not make it in time before the page is unloaded. I just approved a PR with 5 files and only the first 3 were marked as "Viewed"

**Comment by fregante** [comment]
I don't think this feature is easily possible, I dropped it for now
