### ISSUE TITLE
Sorting PRs by merge date

### ISSUE THREAD

**Issue by aymericbouzy** [sindresorhus/refined-github#2287]
From time to time, I do a quick summary to the team of what went in production since last time.

When I'm viewing my merged PRs, I would like to see them sorted by merge date. That way, I can quickly see what are the new features that were merged since last time I did the update. At the moment, it's possible to sort by time of last update, but it's not always the same as the time the feature was merged.

Example URL:
https://github.com/expo/expo-cli/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed

**Comment by fregante** [comment]
It doesn't look like it's possible. The closest thing is `sort:committer-date` but it doesn't work on PRs, just commits.

https://help.github.com/en/articles/sorting-search-results#sort-by-committer-date

**Comment by JRinglerTexVisions** [comment]
Then where does `relative-time` come from and why are we unable to sort by it?

---
![image](https://user-images.githubusercontent.com/50834093/93085030-f5d7a600-f662-11ea-96ec-5932c5449440.png)

**Comment by fregante** [comment]
Because GitHub doesn’t offer it as a sortable value. There’s a lot of data that GitHub doesn’t offer in the search

**Comment by JRinglerTexVisions** [comment]
That's unfortunate.

**Comment by holgerd77** [comment]
Everytime I am doing releases for our monorepo it makes me speechless that this feature is not available/still not implemented.

I would simply need a list of the PRs we merged since the last release, feels like the most mundane use case ever.

I am then helping myself out by sorting by "Recently updated". This randomly draws in all old PRs though which got some comment since our last release round.

**Comment by fregante** [comment]
I think this is appearing on a common Google search. 

I'll lock it because this is not a GitHub forum, this is for a browser extension called [Refined GitHub](https://github.com/refined-github/refined-github).
