### ISSUE TITLE
Older/Newer buttons to follow renames broken

### ISSUE THREAD

**Issue by karlhorky** [sindresorhus/refined-github#2330]
#1870 introduced the following of the file across renames (original issue #998), super awesome! 🎉

Unfortunately it's broken currently ([link](https://github.com/microsoft/vscode/commits/master/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json)):

![Screen Shot 2019-08-14 at 16 12 36](https://user-images.githubusercontent.com/1935696/63028257-c3330b00-beae-11e9-978c-6531b977ed16.png)

![Screen Shot 2019-08-14 at 16 12 46](https://user-images.githubusercontent.com/1935696/63028267-c62dfb80-beae-11e9-8fed-60fcd6e7b3bf.png)

The problem appears to be that it is taking the commit **from the current page** instead of the commit before/after the rename.

cc @fregante

**Comment by fregante** [comment]
It still works on the original test file:

- https://github.com/sindresorhus/refined-github/commits/master/source/features/copy-on-y.tsx

So I'm not sure what's going on here

**Comment by karlhorky** [comment]
Oh weird! Yeah maybe because more of the path changed...?

**Comment by fregante** [comment]
This works on the assumption that "History" pages for a file will always be available, whether the file still exists or not.

For some reason in this case it's not working, but if I replace `master` with the parent commit of the commit that renamed the file, it works:

https://github.com/microsoft/vscode/commits/df9b7778f262c2aaa0633d3545e9d46b045cfd31/extensions/markdown/syntaxes/markdown.tmLanguage.json

Paths or just filenames shouldn't make a difference because to git they're the same thing.

**Comment by karlhorky** [comment]
> if I replace master with the parent commit of the commit that renamed the file, it works

Yeah I noticed that too, that's what I meant in the description "instead of the commit before/after the rename".

I guess this is a potential solution for the problem? Link to the `commits` URL with the commit hash of the last / first commit in the list?

**Comment by fregante** [comment]
The problem is that if we change the link to point to the commit instead of `master`, the `Newer` button will never work.

If you visit https://github.com/microsoft/vscode/commits/df9b7778f262c2aaa0633d3545e9d46b045cfd31/extensions/markdown/syntaxes/markdown.tmLanguage.json you won't see any reference to _whatever the "Older" page should point to._

This is not fixable unless we are able to follow the file's whole history and generate the navigation that way

**Comment by karlhorky** [comment]
Hm, right... I was thinking of getting the reference to the commit via the tilde operator at the end of the commit (https://github.com/microsoft/vscode/commits/df9b7778f262c2aaa0633d3545e9d46b045cfd31~/extensions/markdown-basics/syntaxes/markdown.tmLanguage.json), but that actually goes in the wrong direction - it gets the parent (and there's no way of knowing whether the "next commit" would involve this file either).

Wonder if there would be any easier way to grab the next URL from the API...

**Comment by karlhorky** [comment]
If it cannot be done, maybe the bug with just the Older button can be fixed for now, and a second bug opened for the Newer button...?

**Comment by fregante** [comment]
> If it cannot be done easily or right now, maybe the bug with just the Older button can be fixed for now, and a second bug opened for the Newer button...?

That's the thing, the feature works correctly now in many cases, in both directions. If we fix the Older button in your case, the Newer button breaks for everyone.

A possible solution would be to preserve the branch information so that `Older` points to `commits/$commit?branch=master` and Newer can keep pointing to `commits/$branch`, even if in your case it might work.

This search parameter would have to be preserved across all navigation though

**Comment by karlhorky** [comment]
> If we fix the Older button in your case, the Newer button breaks for everyone.

Ah I didn't understand that the fix would cause the other cases to break 😞

The other solution sounds like it could be a start for an idea... is that `?branch=master` parameter a GitHub feature already? 😮 Never seen it before.

**Comment by fregante** [comment]
The original issue is no longer reproducible. If you find a bug, please open a new issue specific to it.

**Comment by karlhorky** [comment]
This looks good now, thanks for reporting back to this issue @fregante! If I notice anything else related, I'll open a new issue :)
