### ISSUE TITLE
revert changes for a single file doesnt work on private repos

### ISSUE THREAD

**Issue by staabm** [sindresorhus/refined-github#2362]
in a private repos I cannot 'revert changes of a single file'. I am getting a 'Revert failed - see console for details' message and the following error logs:

![grafik](https://user-images.githubusercontent.com/120441/63423617-fb859c80-c40c-11e9-8ea7-93f344ec3fab.png)

after adding the 'personal token' in the extensions settings it works as expected.

would be great to have a cleaner error message that I missed to configure the token

using 19.8.20 in google chrome 78

**Comment by kidonng** [comment]
![image](https://user-images.githubusercontent.com/44045911/63424825-d3fcf700-c441-11e9-82c1-84584e1cddeb.png)
![image](https://user-images.githubusercontent.com/44045911/63424835-d95a4180-c441-11e9-92ad-dccff09f033b.png)

**Comment by staabm** [comment]
I am aware that ‚some features‘ require the token. 

A simple console log error telling that the token is missing would be great for UX

**Comment by kidonng** [comment]
If it's for great UX then we should use a snackbar or popup instead of console messages.
[There are already messages](https://github.com/sindresorhus/refined-github/blob/0b2400511c28c9e22edbfc18770f113eafcecfc4/source/libs/api.ts#L176-L182) telling you that token may be needed. But your screenshot didn't contain the error message for `revert-file` feature.

**Comment by fregante** [comment]
Indeed. The token error is already present in the console. We generally expect it to be there and don’t provide extra UI for such errors.
