### ISSUE TITLE
When the drop menu and fork count overlap, the fork count is displayed above

### ISSUE THREAD

**Issue by eai04191** [sindresorhus/refined-github#2368]
This happens when the window width is narrow or when looking at Projects.
I have disabled hide-watch-and-fork-count.

![image](https://user-images.githubusercontent.com/3516343/63446436-2c99b780-c475-11e9-9f5a-f3b053ec660f.png)

Those probably related
https://github.com/sindresorhus/refined-github/blob/34e0f8be28677144c2194bca7ecc40c01890e36e/source/features/hide-watch-and-fork-count.css#L13-L18

**Comment by busches** [comment]
@jerone can you verify this is resolved in #2230?

**Comment by jerone** [comment]
[**@busches**](https://github.com/busches) commented on [Aug 21, 2019, 6:55 PM GMT+2](https://github.com/sindresorhus/refined-github/issues/2368#issuecomment-523549645 "2019-08-21T16:55:25Z - Replied by Github Reply Comments"):
> [@jerone](https://github.com/jerone) can you verify this is resolved in [#2230](https://github.com/sindresorhus/refined-github/pull/2230)?

I can confirm that this is **not** fixed by #2230 
![image](https://user-images.githubusercontent.com/55841/63457527-838d9580-c451-11e9-9ffd-e07692216326.png)

**Comment by fregante** [comment]
I recently dropped `position: relative` on those buttons in an effort to avoid these issues specifically. It’s kinda weird that this number is positioned on its own and it doesn’t make sense. 

PR welcome to nuke `position: relative` on these elements like in https://github.com/sindresorhus/refined-github/pull/2340
