### ISSUE TITLE
Move "Viewed" checkbox to the bottom of the file (or add another there) 

### ISSUE THREAD

**Issue by tadeu** [sindresorhus/refined-github#2392]
The "Viewed" checkbox is a nice recent addition to GitHub PR's, but it is annoyingly located at the top of the file. We usually read files from top to bottom, so the most natural location would be at the bottom (to avoid scrolling, etc., just read the file and check it)

![image](https://user-images.githubusercontent.com/955251/63970933-c23bd500-ca7b-11e9-8011-a6fd9a2417af.png)

**Comment by fregante** [comment]
File headers are sticky so you'll always have that on screen for the entirety of the file. You never have to _scroll_ to see it.

**Comment by tadeu** [comment]
True, I noticed this just right after creating this issue 😅🤦‍♂

**Comment by kmoth** [comment]
I found this issue because I was reviewing a long file and thought to myself "that viewed checkbox should go on the bottom". I searched the internet to see what others were saying. 

I've been using this feature for years and I guess I've missed the sticky headers all this time. So I think this post is doing at least a small portion of us a good service 😅 

I think the bottom is a good place for it from a reading flow perspective, but I guess they can save some space by grouping it in the header with the other controls.
