### ISSUE TITLE
Code fonts have different sizes

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#242]
One thing we didn't consider when doing https://github.com/sindresorhus/refined-github/issues/179 is that code fonts have different default sizes. I got `Ubuntu Mono`, which is a lot smaller than the default font.
## With `refined-github`

<img width="1004" alt="screen shot 2016-06-01 at 13 48 26" src="https://cloud.githubusercontent.com/assets/170270/15795559/00b94286-29f3-11e6-99b6-bc12818806e5.png">
## Without

<img width="1007" alt="screen shot 2016-06-01 at 13 48 32" src="https://cloud.githubusercontent.com/assets/170270/15795560/00bbf684-29f3-11e6-86ee-6f8fdbb7c856.png">

What do we do about this?

**Comment by paulmolluzzo** [comment]
Am I wrong to think this is expected behavior? I expect the font's character dimensions to be different when using a different font. In other words, of course `Ubuntu Mono` in `12px` is not going to be the exact same size as 'Menlo` in the same `12px`, and that's (part of) the point of different fonts.

If you want to have different sizes for different fonts to sort of "balance" them out, here are some possibly helpful links I googled (we seem to be getting into JS-font detection...):

http://stackoverflow.com/questions/3555962/css-different-font-sizes-on-different-families (Relevant: http://caniuse.com/#feat=font-size-adjust)
https://css-tricks.com/forums/topic/specifying-different-font-size-for-different-fonts-in-a-font-family/
http://stackoverflow.com/questions/11023107/specifying-different-font-sizes-for-different-font-families

**Comment by JaKXz** [comment]
I also think font is a subjective choice so it would be nice to be able to choose between Menlo and Ubuntu Mono [and potentially others].

**Comment by bfred-it** [comment]
Closing this as a consequence of #575 

Continue here: https://github.com/sindresorhus/module-requests/issues/97
