### ISSUE TITLE
Chrome Webstore has not published since the first.

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#2518]
![image](https://user-images.githubusercontent.com/16872793/68130151-dae7c180-fee8-11e9-9505-cbec9328368a.png)
Travis is working fine.

![image](https://user-images.githubusercontent.com/16872793/68130243-01a5f800-fee9-11e9-9ff0-4af5c9c80944.png)

**Comment by yakov116** [comment]
@fregante ?

**Comment by yakov116** [comment]
Looks like its fixed

**Comment by fregante** [comment]
The extension keeps getting stuck in the review queue so there's nothing we can do about it. Maybe switch to Firefox 😏

**Comment by sindresorhus** [comment]
<img width="1027" alt="Screenshot 2019-11-10 at 12 17 19" src="https://user-images.githubusercontent.com/170270/68539318-2b14c700-03b4-11ea-82d2-2df24e9e6958.png">

**Comment by sharkykh** [comment]
Is this happening again?
This may be due to a different reason because now both Chrome and Firefox are outdated.
- [**Chrome** extension][link-cws] [<img valign="middle" src="https://img.shields.io/chrome-web-store/v/hlepfoohegkhhmjieoechaddaejaokhf.svg?label=%20">][link-cws] (19.12.16)
- [**Firefox** add-on][link-amo] [<img valign="middle" src="https://img.shields.io/amo/v/refined-github-.svg?label=%20">][link-amo] (19.12.9)

[link-cws]: https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf "Version published on Chrome Web Store"
[link-amo]: https://addons.mozilla.org/en-US/firefox/addon/refined-github-/ "Version published on Mozilla Add-ons"

**Comment by fregante** [comment]
AMO has disabled some versions because of their strict submissions requirements
