### ISSUE TITLE
trigger infinite scroll if not enough dashboard data is loaded

### ISSUE THREAD

**Issue by Ma27** [sindresorhus/refined-github#256]
sometimes my dashboard looks like this:
![refined-github-fail](https://cloud.githubusercontent.com/assets/6025220/16349721/a2d74410-3a5a-11e6-947a-4f2b2768f241.PNG)

In such cases I'd have to click on the `More` button manually. I'd love to see a feature triggers the load functionality one more time if not enough content for the whole page can be displayed.

**Comment by sindresorhus** [comment]
👍 I [mentioned it](https://github.com/sindresorhus/refined-github/pull/27#issuecomment-187514933) on the original PR for this feature, but didn't seem that important. Now that I've used it for a long while I could really use this. Almost every day there's no content on load time, because everything is hidden.

**Comment by paulmolluzzo** [comment]
I [mentioned a possible solution](https://github.com/sindresorhus/refined-github/pull/27#issuecomment-187515777) back then too. :wink:

**Comment by sindresorhus** [comment]
@paulmolluzzo Happy to go in that direction, but would doing just that fill the dashboard even though it might have to fetch multiple times to fill? Sometimes I have to click load more 3 times to get enough to fill the screen.

**Comment by paulmolluzzo** [comment]
@sindresorhus it would require you to be scrolling, but wouldn't be prevented from filling the screen for any specific reason as long as you don't stop scrolling before it fills.

If you remember, the bug that this addressed was that we just clicked until it loaded everything and thus it interrupted other click events from users. The addition of the `scroll` listener was saying "you're not scrolling and clicking simultaneously".

We could also make the logic something like "if scrolling or if the page isn't full then click". Worst case we have that other bug back if you have a large screen, and slow network, and click as the page is loading.

**Comment by sindresorhus** [comment]
> but wouldn't be prevented from filling the screen for any specific reason as long as you don't stop scrolling before it fills.

The problem is that it's very hard to scroll as slow as it's filling up, as it usually has to do many fetches to fill it up. I think we should be extra eager at first. Maybe do 4 fetches when start scrolling.

> If you remember, the bug that this addressed was that we just clicked until it loaded everything and thus it interrupted other click events from users. The addition of the scroll listener was saying "you're not scrolling and clicking simultaneously".

I remember now. That sucks... I guess we can start just improving the scrolling behavior and see how that works out.

**Comment by paulmolluzzo** [comment]
> Maybe do 4 fetches when start scrolling.

That'd be like creating a queued process, which will clog up the `click` listener until that entire process is complete. We can only trigger `click` after the loading is complete because the button gets disabled.

It might work fine, but anyone in a thin connection is going to have a longer process. Worth a shot.

**Comment by sindresorhus** [comment]
Ugh, so many problems 😛 Let's try and see.

**Comment by paulmolluzzo** [comment]
> Ugh, so many problems 😛 

I'm curious if there's a better solution. Maybe we can figure a way to "pause" the virtual clicks if a user interacts and then resume when the user stops?

// @DrewML

**Comment by DrewML** [comment]
Ugh, this is a hell of a painful problem. I tried replicating it earlier today, but there is so much activity from my job's org that I always have a full page on the first load :(

**Comment by bfred-it** [comment]
@DrewML: CMD- is your friend. Big viewports are never full 🙂

**Comment by arkon** [comment]
I'm wondering if an [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) might be helpful? It could detect if the button is visible.

**Comment by bfred-it** [comment]
@arkon detecting the position of the button is [easy](https://github.com/sindresorhus/refined-github/blob/5fae705a1fb6227ad574e9c74cb8da689ee1a334/src/content.js#L165-L171). IObserver won't help because it only fires on scroll anyway.

**Comment by bfred-it** [comment]
Actually… good point! IO triggers even when the button moves in the view without any scroll/resize events (e.g. when some content is hidden and the button comes in)

Tracking each new button becomes a bit spaghetti, but it's safer than relying on a blind setInterval to achieve the same result. Submitting a PR.
