### ISSUE TITLE
Restore `faster-pr-diff-options` feature on PRs

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2597]
Originally disabled on PRs because of https://github.com/sindresorhus/refined-github/issues/2291

![](https://user-images.githubusercontent.com/1402241/54178764-d1c96080-44d1-11e9-889c-734ffd2a602d.png)

This feature was applied to two places:

- PR file header: now disabled because of #2291
- commit header: it still works

## Suggested solution

1. Restore the buttons right next to the gear icon, replacing it
2. On small screens (via `.d-md-block` classes) we can still show the native dropdown

<details><summary>Old suggestion</summary>

I had suggested some alternatives to replacing the original "PR diff options" dropdown:

> - dropping its "apply and reload" button (saves one click)
> - perhaps opening the dropdown on hover (saves one more click)
> 
> There's already a keyboard shortcut to toggle the whitespace.
> _Originally posted by @fregante in https://github.com/sindresorhus/refined-github/issues/2291#issuecomment-517539452_

Or replacing the gear icon with 2 small icons as described in https://github.com/sindresorhus/refined-github/issues/2597#issuecomment-794294349

<details>

**Comment by dpashkevich** [comment]
I use the "No Whitespace" button all the time (wish it was just ALWAYS enabled by default) and really miss it now.

**Comment by fregante** [comment]
Sadly there's not really space for it:


<img width="1028" alt="" src="https://user-images.githubusercontent.com/1402241/62343178-ec00eb00-b513-11e9-9f55-30cb56fc2712.png">

**Comment by dpashkevich** [comment]
We could change the label on the button from "No whitespace" to something
like "-w" or an icon

**Comment by fregante** [comment]
Still not enough space if all of GitHub’s widgets are visible and the title is there too

**Comment by dpashkevich** [comment]
At what screen width does it break?

**Comment by fregante** [comment]
All of them. Look at the last screenshot I posted. Add the “Commit suggestions” widget and voila: no space left.

**Comment by dylmye** [comment]
As a compromise, it could hide the 'files viewed' indicator maybe? Or we could reduce the amount of space the title has. Or we would increase the width the content has on the header.
I'm happy to mock up visualisations of these if you're interested.

**Comment by fregante** [comment]
>  it could hide the 'files viewed' indicator maybe?

We shouldn't hide a useful feature (the feature's utility is debatable, but...)

> Or we could reduce the amount of space the title has.

I don't wanna play that game. We tried it for the past 2 years and we've been just moving the problem and never resolving it.

> Or we would increase the width the content has on the header.

This could work, but the compromises are:

- only works when the window fits it
- it might not look great since the header would be _slightly longer_ than the content width

**Comment by fregante** [comment]
In the end, I think these are the safest to implement and they still bring down the total number of clicks to **one** (+ hover)

> - dropping its "apply and reload" button (saves one click)
> - perhaps opening the dropdown on hover (saves one more click)

**Comment by dylmye** [comment]
+1 for dropping apply and reload, especially as only two settings live on that menu. Not sure about the latter, is the hover behaviour implemented anywhere else?

**Comment by fregante** [comment]
> is the hover behaviour implemented anywhere else?

It used to be implemented on the reactions popup, but it stopped working and we never readded it.

**Comment by bundyo** [comment]
Can you at least re-add the shortcut? :slightly_smiling_face:

**Comment by fregante** [comment]
PR welcome for that. Most of the feature code can be dropped: https://github.com/sindresorhus/refined-github/blob/master/source/features/faster-pr-diff-options.tsx

**Comment by jensf** [comment]
Maybe something changed as I see plenty of space for those icons with my resolution (1920x1200)

![image](https://user-images.githubusercontent.com/1754057/110380204-c7d98a00-8025-11eb-8ac7-f4d37e8543d0.png)

Also when scrolled down (though in this mode the icons may need to be shorter)
![image](https://user-images.githubusercontent.com/1754057/110380655-682fae80-8026-11eb-8645-949db81b7f58.png)

Even on smaller resolutions there is enough space because GH removes some of the filters conveniently leaving room for the no-whitespace icon. (width: 640)
![image](https://user-images.githubusercontent.com/1754057/110380559-49311c80-8026-11eb-8884-7edcb3431b48.png)

**Comment by fregante** [comment]
We still could, however, replace the current gear icon with 2 icon toggles:

- unified diff toggle
- visible whitespace toggle

The icons will make absolutely no sense on their own but this would only take an extra 30px on the lower line. They'll probably only make sense with tooltips.

**Comment by jensf** [comment]
@fregante I see now. That last situation the gui is super tight.

I would be ok with ok with 2 toggle icons though it's not ideal due to vagueness of the their use. Perhaps a hover hint may be enough to clear up their purpose.

Some other ideas:

- Move _Commit suggestions_ 
imo this is the problem. The PR name is almost removed with only 1.5 words showing, and the filters are all jammed together. Perhaps we can add an extra line to space things out a bit? or move the _Comment Suggestions_ or _files viewed_ beneath the _Review Changes_.
 
- shrink the _Commit suggestions_ 
I'm struggling how this might be shrunk and still be useful, but if it wasn't so big it would likely solve our issue.

- Add when enough space
Add the nice icons only when there's enough space. Say width > 1000 for the collapsed header and maybe always for the non collapsed header. I'm always reviewing on a large screen so this would be perfect for me.

**Comment by fregante** [comment]
Could you open new issue to clean up the file review header? There's indeed _room_ for improvement to make more _room_.

**Comment by fregante** [comment]
I added another suggestion in my first issue to restore the feature almost as it was, with the exception that:

- the icons appear in a slightly different place
- the icons only appear on larger screens

This should avoid the wrapping issue on small resolutions.
