### ISSUE TITLE
Editing an issue sometimes shows me old data

### ISSUE THREAD

**Issue by TheBestPessimist** [sindresorhus/refined-github#2621]
I cannot provide you a link to the comment, since it is in one of my private repos.

Using the plugin on firefox.

I have disabled the plugin for about 2 weeks and this stale data issue did not appear. After i enabled the plugin again, the problem re-appeared.

Problem: it seems that when having multiple revisions of a comment on an issue, pressing the edit button bring me the wrong revision back (ie. one in the past). If i don't pay attention, edit whatever i need then save, the new comment will have the old data (from a previous revision) plus only my edit. I have recorded the diff shown by github in the following gif. Note that all of my changes in the comment were to replace the link of a picture (ie. i uploaded a new picture and deleted the link of the old one).

![all of the deletes should not be there  ](https://user-images.githubusercontent.com/4482210/70685628-a36ff000-1cb2-11ea-9930-3d5dce600dec.gif)

It seems that this bug manifests even if i hard refresh (ctrl + f5).
Maybe it is somehow related to me looking, before editing, at the issue history, and clicking one of the revisions there.

**Comment by TheBestPessimist** [comment]
For reference, here's the correct version (ie, the version that i expected to have at the end):

```
# Concept and estimation

### Add Tour to Sales Order, Shipment Candidates, Shipment Document and persist/carryover 

- 5h

### The tour shall be shown on "Rüstschein" (see sales order action and on the sales order document

Note: it's a different process name:
![image](https://user-images.githubusercontent.com/4482210/70685401-f39a8280-1cb1-11ea-9bb3-ce7666d1ca32.png)


- ???h

### Create process in Shipment Window which allows multiselect shipments and adds them to a Transportation Order

- Q: How shold we handle Shipments which already have a package in a different Transportation Order?
    - A: Quick Solution. Add a virtual column flag in shipment that indicates if a shipment is already integrated into a transportation order. This way the user can see it.Besides that no further functionality needed atm.

- probably must call `de.metas.shipper.gateway.commons.ShipperGatewayFacade#createAndSendDeliveryOrdersForPackages` in order to generate the shipment documents (and web-request the shipper)
    - which is called by de.metas.handlingunits.shipmentschedule.api.HUShippingFacade#generateShippingDocuments, but this has multiple roles:
        - receives shipment candidates
        - creates the shipments from candidates
            - ❗️ Q: this should not be done
                - i think i need to add a flag here to disable this (must talk with @metas-ts ❗️ )
        - creates the packages and attaches them to transportation order
        - create the invoices
            - ❗️ Q: should this be done?
        - calls the Shipper to get the PDF data
    - est: 8h
- testing: 4h - maybe more since this touches the Shipper and Shipper Transportation flows, so i don't want to break those



### Transportation Order: Have an action that allows to print out all shipment documents at once that are in the transportation order. New browser Tab opens and shows a PDF which has all Shipment documents. The user cann do print and select the amount of copies before.

> The user cann do print and select the amount of copies before.
Q: What do you mean by this?

- Create test data 
    - 2h
- Try and use something similar to
    - de.metas.dunning.process.C_DunningDoc_JasperWithInvoicePDFsStrategy#executeReport
    - de.metas.invoice.process.C_Invoice_SalesInvoiceJasperWithAttachedDocumentsStrategy#executeReport
    - de.metas.printing.process.ConcatenatePdfs#doIt
    - 6h
- Testing
    - 3h

Total estimation: 5+?+8+4+2+6+3=28h + ??
Used: 7.5h

Milestone does not change from 2019-12-17.
```

**Comment by fregante** [comment]
This is unlikely to be Refined GitHub's fault since the only related feature is faster-edit-comments, which simply copies the `.js-comment-edit-button` class to have GitHub listen to it exactly like it listens to its native Edit button in the dropdown.

<details>
<summary>This is GitHub's code connected to it</summary>

```js
p("click", ".js-comment-edit-button", (function(e) {
const t = g(e.currentTarget, ".js-comment");
t.classList.add("is-comment-editing"),
y(t, ".js-write-tab").click();
const n = y(t, ".js-comment-field");
if (!(n instanceof HTMLTextAreaElement))
throw new Error("invariant: app/assets/modules/github/behaviors/commenting/edit.js:20");
n.focus(),
A(n, "change");
const s = e.currentTarget.closest(".js-dropdown-details");
s && s.removeAttribute("open")
}
)),
```

</details>

Other than this, normally GitHub will warn you if you edit an old comment and try to save it (actually it just discards what you just wrote 🤦‍♂️ and loads their newest version). This is probably done via the `timestamp` hidden field, which is then compared with the remote version to see if it's newer.

So if this is really happening without warning, your DOM includes the latest version of the comment (and related `timestamp`) but something is replacing/restoring the `textarea` content with the old content before you edit it.

I don't think we have any feature that does that.

---

What browser are you using?

**Comment by fregante** [comment]
The only way I can think of this happening is due to GitHub's `js-session-resumable` feature, which saves your comment locally and restores it if you mistakenly close the tab or navigate away before submitting it.

For example it _could_ happen if you:

1. Start editing comment
2. Navigate away (the unsaved comment is stored locally)
3. In secondary tab, edit and submit comment
4. In the primary tab, navigate back
5. Click to edit the comment again
6. The page loaded the latest version, but `js-session-resumable` filled in your last unsaved copy.

But this is not Refined GitHub’s feature.

**Comment by TheBestPessimist** [comment]
Browser: Firefox 71.0 (64-bit). I only have a single tab with that issue. I'm always ctrl+f5 refreshing before editing anything (so that i also catch what my coleagues may edit). 

From what i remember, github never warns me that i am editing a stale version because i am not editing a stale one: after refresing the page i see the correct text (ie. the latest revision of a comment) but only when editing the issue the text the old one.

**Comment by fregante** [comment]
This is sadly not very actionable and hard to reproduce. We can't do anything about it unless someone adds steps to reproduce it

**Comment by keelerak14** [comment]
Dito
