### ISSUE TITLE
Feature request - Add compare tab

### ISSUE THREAD

**Issue by whitneyit** [sindresorhus/refined-github#267]
I often find myself doing comparisons of commits/releases when trying to determine if a bug fix has shipped in a given release.

Currently GitHub doesn't offer a simple way to get to the compare screen.

Similar to how the `Releases` tab was added, I was thinking of adding a compare tab beside that. Clicking on that tab would default to redirecting the the `/compare` url, but if you clicked on it from a commit, diff, or release etc it will make a comparison between that point and `master`.

Is this something that sounds reasonable? I'll be happy to submit a PR in the event that it is

Cheers

**Comment by whitneyit** [comment]
And on that note, potentially the releases page could be updated with an _unreleased_ section which would be the comparison between the latest tag and master. Thoughts?

**Comment by sindresorhus** [comment]
I like the idea.

@hkdobrev @paulmolluzzo @DrewML What do you think?

**Comment by hkdobrev** [comment]
I don't see why we need a compare tab. I'd like to have compare links for each tag on the releases page and probably for commits and other places. But why a tab?

**Comment by whitneyit** [comment]
I see the tab making sense given how the /compare route acts like a top
level entry point into lower level comparisons

**Comment by paulmolluzzo** [comment]
> Clicking on that tab would default to redirecting the the /compare url, but if you clicked on it from a commit, diff, or release etc it will make a comparison between that point and master.

Is there a way that we can use something other than a tab when you're comparing a diff/commit/release? With the other idea I quote below, that tab is going to change behavior depending on the page you're on.

> And on that note, potentially the releases page could be updated with an unreleased section which would be the comparison between the latest tag and master. Thoughts?

I like this idea for the tab - it's sort of like an "Unreleased" tab, more than a compare.

**Comment by whitneyit** [comment]
In the above discussion the comparisons have been made towards `master` but that may not actually work. Not all repos have `master` as their [default branch](https://help.github.com/articles/setting-the-default-branch/). Take [`Laravel/Framework`](https://github.com/laravel/framework) for example. As of this moment it resolves to the [`5.2`](https://github.com/laravel/framework/tree/5.2) branch and will soon change to [`5.3`](https://github.com/laravel/framework/tree/5.3).

So how about this, When viewing a commit, say [`d1ca32f`](https://github.com/sindresorhus/refined-github/commit/d1ca32faadeb96f7838c6fc73b1caac20724736a), beside the `Browse files` we place a `Compare files` button there that compares that commit to the _base_ branch.

As for the releases tab, inside the `Releases` and `Tags` button group a `Unreleased` button is added which shows the difference between the latest release and the _base_ branch,

When viewing the route for a tag directly, say [`1.5.1`](https://github.com/sindresorhus/refined-github/releases/tag/1.5.1), in the left hand column, under the last item in the _release-meta_ list, a `compare` item is added that will compare that tag to the _base_ branch,

Another place that I can think of that may be useful to have this is when viewing the commits for a branch, say [`master`](https://github.com/sindresorhus/refined-github/commits/master) for this repo. When viewing the commits, beside the _Browse the repository at this point in the history_ button, maybe we could add a button to _Compare the repository at this point in the history_.

Lastly it could be added to the `/blame` route under the `Blame ^` text that is currently there.

How about that. Does that clear up the concerns?

**Comment by sindresorhus** [comment]
@hkdobrev @paulmolluzzo @DrewML You good with this? Any other concerns?

**Comment by DrewML** [comment]
No concerns from me 👍

**Comment by paulmolluzzo** [comment]
I'm good with this too. :+1:

**Comment by hkdobrev** [comment]
I'd like to work on some of that functionality.

However, some comments on the above

> When viewing the route for a tag directly, say [1.5.1](https://github.com/sindresorhus/refined-github/releases/tag/1.5.1), in the left-hand column, under the last item in the release-meta list, a compare item is added that will compare that tag to the base branch,

GitHub already provides that. I'm not sure if it was there when the above comment was written, but it's been there for a few months. Next to the date of the tag there is a link saying "28 commits to master since this tag" with a [link to the relevant compare page](https://github.com/sindresorhus/refined-github/releases/tag/1.5.1) and it's working with the [base branch regardless of how it's called](https://github.com/laravel/framework/releases/tag/v5.3.21).

This is also present in the list of releases - https://github.com/avajs/ava/releases However it's not present in the list of tags which is unfortunate (for completeness it's present on a tag details page). I'd very much like to add it so even if a project is not using GitHub releases, users of the extension would have easy access to these useful compare links.

---

Other than that I'd very much like to add a new feature to the tags & releases pages - ability to compare adjacent releases. So let's say you're looking at https://github.com/sindresorhus/refined-github/releases I'd very much like an easy way to compare `1.9.1` and `1.9.0`. I'd like a link to be present next to each tag/release linking to the compare page comparing that version with the previous one. It won't be perfect for projects supporting multiple major versions like https://github.com/laravel/framework/releases where a maintenance release for an old major version creeps in among the new releases, but still, it would be a very welcome change IMHO for most projects and cases.

This is much about scratching my own itch so while I support adding links to `/compare` from commit pages and others I'd like to limit my scope to the release/tags page.

What do you think? Do you like my suggestions above? Do you have suggestions to change something? Anyone wants to help or take some of the work for the other pages e.g. commit pages?

Thanks for reading so far! Here are a cat and a cup of tea 😼  🍵

**Comment by j-f1** [comment]
Isn’t this feature complete?

**Comment by bfred-it** [comment]
It's been moved

https://github.com/sindresorhus/refined-github/pull/509
