### ISSUE TITLE
"Update Branch" button: show warning if PAT is undefined

### ISSUE THREAD

**Issue by mmoayyed** [sindresorhus/refined-github#2679]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2410%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/2679)

Thank you for this useful extension!

If no personal access token is defined, clicking on the "Update Branch" button changes the button caption to "Not Found", and it's not immediately obvious why. Alternatively, the button can be displayed, hidden or perhaps a warning message should/could be displayed in its place instead, when no access token is defined/available.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $10.00)

- [<img src='https://avatars0.githubusercontent.com/u/183673?v=4' alt='janpio' width=24 height=24> janpio](https://issuehunt.io/u/janpio) ($10.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by sindresorhus** [comment]
Would be nice if features in the settings indicated whether or not they required a PAT.

**Comment by fregante** [comment]
> Would be nice if features in the settings indicated whether or not they required a PAT.

We do have a [link](https://github.com/sindresorhus/refined-github/search?q=libs/api) for that in the options:

<img width="409" alt="" src="https://user-images.githubusercontent.com/1402241/71966709-ab309f00-3234-11ea-886b-6a13dfae8abd.png">

I don't think it would solve this issue specifically since the button would still be shown.

---

Like with any feature, the way to find out why a feature isn't working, is to open the console. Such error can show up in the future regardless of the PAT and the console should have more information.

How can we teach the users to open the console when something doesn't work?

**Comment by fregante** [comment]
**I extended the copy in** https://github.com/sindresorhus/refined-github/issues/1137 (the first thing new users see) with info about:

- where to look for errors;
- the PAT: until now, the user had to open the options to even know that a PAT may be needed.

**Comment by fregante** [comment]
I'll add: Even if there's a token saved, it doesn't mean that it's valid and that it has access to the current repo, so:

- **"user action" features like this should show a warning**: "XXX failed because YYY"
- "background" features that just show info will silently fail (other than the console error)

PR welcome to add the first part, specifically for the "Update branch" button.

**Comment by jerone** [comment]
What if we make two changes:
1. Behind every feature in the options window, we add an small text that says `token required` and hash-link it to the API token setting.
2. Add an extra [`feature.add` setting](https://github.com/sindresorhus/refined-github/blob/master/contributing.md#featuresadd), indicating that an token is required. If the API token is missing, we disable the feature.

**Comment by fregante** [comment]
I don't wanna keep track of that too. Next thing someone will ask is to group/hide/filter those features in the options. I think have a _"Some features"_ link is enough.

This PAT should be a non-issue: if you want RG to work 100%, you need the PAT. Without it, its working isn't guaranteed. This is why I leaned towards just informing the user about it:

>  Some features may not work without it. Generate one.

> **Enabling API-based features**
> Make sure you create and add a Personal Access Token in the extension’s options to ensure every feature works correctly.

It's cool that RG finally lets users pick and choose features compared to its initial "all or nothing" policy, but we're spending **a lot** of effort just maintaining this UI. Let's keep it at a minimum.

**Comment by janpio** [comment]
What was confusing me and took me a long time (until I found this thread via Google) was the fact that _some_ other Refined GitHub features _do_ advertise the explicit need for a PAT in the console: 

![image](https://user-images.githubusercontent.com/183673/82739836-7c2e4c00-9d43-11ea-8d74-82ad0eb088f7.png)

The "Update Branch" button does not do that, and the "Not found" message on failure also does not indicate anything about a missing PAT.
