### ISSUE TITLE
Force "squash and merge" title to be the pull request title

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#276]
It does if there are multiple commits, but if there is only one commit, if will use the commit title instead. I often rename pull requests because submitters do a very bad job of naming their pull requests. When I then "squash and merge" it will instead choose the commit title, which is the original bad title, and I have to rename yet again. Would be nice if we could just copy in the pull request title when "Merge pull request" is clicked and you're in the confirm view.

**Comment by hkdobrev** [comment]
@sindresorhus Have you contacted GitHub about that? It seems like that should be the default.

**Comment by sindresorhus** [comment]
@hkdobrev No. I'm tired of wasting time sending them feature requests (I've sent 100+ through the years) and getting back a generic fake-nice response and never seeing anything done. That's exactly why I made this extension. Feel free submit the request yourself though.

**Comment by apapko** [comment]
Has it been reported that PR title is not used as commit message if pull request contains only one commit?
ex pr title: ```feat(test): squash test ```

**Comment by alerque** [comment]
I've just found this extension and like many of the things it fixes. This is actually one "feature" I'd like to turn off though. I find that in PR's with one commit the author often has taken more care with the commit message than the PR title, and that's a better default to start with. Since the interface lets me adjust the commit message anyway, starting with the least intrusive option of not touching the commit message seems like a better place to start. Your adjustment isn't suited to all workflows, and I think the default Github behaviour is better for mine.

**Comment by bfred-it** [comment]
> . Your adjustment isn't suited to all workflows, and I think the default Github behavior is better for mine.

That's why you can disable it as `fix-squash-and-merge-title`

Generally I found the opposite, where the commit is something like `Update README.md` and the title has any sense.

This very feature is actually being extended in https://github.com/sindresorhus/refined-github/pull/1934 to also fix the PR title as shown here: https://github.com/sindresorhus/refined-github/issues/1743

**Comment by alerque** [comment]
Thanks for the feedback @bfred-it, I hadn't even discovered the extensions allowed selectively disabling features — only that it did something I didn't like out of the box. That's awesome, and just the Firefox extension just picked up five stars from me.

**Comment by bfred-it** [comment]
That's good to hear :D

**Comment by joeshaw** [comment]
FYI, this feature appears to apply to regular merge commits now as well.

**Comment by bfred-it** [comment]
That was an intended change in https://github.com/sindresorhus/refined-github/pull/1934

**Comment by bharathwaaj** [comment]
The description is now not getting populated with the PR description message. Instead it is populating the individual commit message titles. Kindly request you to provide an option to select whichever behaviour is preferred.

The main reason I was using this extension was I don't have to copy paste the PR description when squash merging PRs.

**Comment by bfred-it** [comment]
> Instead it is populating the individual commit message titles

That's GitHub's default behavior.

> The description is now not getting populated with the PR description message

That's because the feature was dropped. The PR comment is often full of content that does not belong to commits, such as markdown links and test links. Or it's just `fixes #XXX` which also isn't useful.

If you like that feature, you can package it up in a userscript because it's no longer part of Refined GitHub

**Comment by zachwhaley** [comment]
@bfred-it Would y'all be willing to consider a user option to copy the PR description into the merge message?  I've got a very basic version of this "working", see recording below.  If not, I understand. I just wanted to make one more suggestion.

![merge-message-option](https://user-images.githubusercontent.com/2996465/57393418-a8068000-7188-11e9-9167-2471a634a47c.gif)

**Comment by fregante** [comment]
GitHub implemented it

https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/
