### ISSUE TITLE
Notifications Beta: `mark-unread` is not compatible

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2801]
The notifications UI is completely different, so that `mark-unread` part needs to be rewritten. Maybe not right now, but definitely when Notifications leaves Beta

**Comment by ilyam8** [comment]
Hi @fregante. I no longer see `Mark as  unread` button on the issue page. I guess this issue about Notification page, right?

**Comment by fregante** [comment]
@ilyam8 are you on 20.2.14.922? #2796

**Comment by ilyam8** [comment]
Yes, i use Chrome, `20.2.14.922` is latest in the web store.

**Comment by notlmn** [comment]
@fregante doesn't "Mark as unread" now feel the same as "Save"? It would make more sense because the user is essentially _saving_ an issue/PR to get back to sometime later. Except we do that even if there is no notification for that issue/PR and the user doesn't have to subscribed for it in the first place to _save_ it, same as _bookmarking_.

Well we can't call that any of these because GitHub already uses the same wording. Maybe "Save for later", and show these in the "Saved" notifications view?

Also worth mentioning that this only makes sense if the user has "Group by repositories" applied; as the default "Group by date" view (for both "Saved" and "Repository level notifications") is paginated with a count at the bottom.

**Comment by fregante** [comment]
I’m not sure of what you’re talking about GitHub’s Mark as unread hasn’t changed behavior. Refined GitHub’s Mark as unread matched its behavior exactly, except that instead of remaining as “read” notification, it would just disappear. Neither one of them ever worked as “Save” — which is an additional, unrelated list that doesn’t expire, even if marked as Done; basically bookmarks.

**Comment by notlmn** [comment]
I was trying to say that our "Mark as read" worked as GH's "Save" (kinda), and should probably work that way if implemented?

**Comment by fregante** [comment]
That would change the feature and I don’t see a reason to. If you need to Save something, create a bookmark, it’s way more flexible.
