### ISSUE TITLE
Ability to turn off all styles

### ISSUE THREAD

**Issue by stevelacey** [sindresorhus/refined-github#2845]
I don't see any way to turn off `align-issue-labels.css` for example, without working out what the original styles were and compiling a custom user sheet to restore them, it'd be great if everything could be toggled, I'd personally turn off everything then pick and choose the features I want.

**Comment by fregante** [comment]
> I'd personally turn off everything then pick and choose the features I want.

That’s the opposite of what Refined GitHub is about. Features are only added when they make sense for most people; many refinements are so subtle many would never enable them. Some controversial CSS features do get toggles in the options but not all of them need it

**Comment by stevelacey** [comment]
Alright that's a shame, I love some of the JS features like the "convert from start review to comment", that's the reason I'm here, but the issues/prs list font-size/line-height is all messed up, the draft PR icon is broken, there's various other changes, it'd be real nice to be able pick n choose.

**Comment by stevelacey** [comment]
I figured I’d see what happens if I pack the extension myself, and disable the core styles that can’t be toggled (commented out the imports at the top).

Turns out it pretty much all works, I’m happy with it, and am now running that custom build with only a handful of features disabled and some small style tweaks.

I stand by my suggestion, moving all core css into features so everything can be toggled would be an improvement, and make Refined GitHub less opinionated.

Great work 😊👏🏼 There’s some real nice stuff here

**Comment by fregante** [comment]
> I don't see any way to turn off `align-issue-labels.css` for example

https://github.com/sindresorhus/refined-github/issues/2650

**Comment by Hans5958** [comment]
I don't understand how "afeature is so subtle" can justify a feature can't be turned off at all. Users should be given a freedom to personalize their own experiences even the smallest things, and not forced into a one-sided opinion.

**Comment by fregante** [comment]
> should

> not forced

Nobody is being forced to install Refined GitHub. If anything, you want to force us to support your specific use case. Controversial CSS features have been made disableable when asked politely and with reasoning, but not **all** of them, because it's just extra, unneeded noise and code for the most part.

**Comment by Hans5958** [comment]
Firstly, I'm not here to forcing my single use case that only I would find it useful. That would be too naive. In fact, someone is also suggesting the same addition that could be found useful for his daily driver, which is OP, and hopefully some others. So, I know that this is not an isolated case, and hence, I commented to this issue in order to sign interest on this issue, even if it is closed. It's also not about being forced to use RG, this is just a suggestion of a small part of RG after all.

Secondly, about your point of "too much code," I don't think that would be a significant issue considering that there are around 200 new features, and a few other that can't be turned off. I'm not sure how difficult is adding a new feature on RG, but I also developed a similar extension, and it is quite easy to add one. Might not apply here, but it's a wild guess. If you are going argue that it would make the list longer, you would probably used the search bar instead of scrolling down in most cases.

I think it boils down to our viewpoints. You and your team probably have a slight difference on the philosophy that I'm not aware of and probably not aligned to, or I'm just a young adult who is picky on things. I don't know.

**Comment by yakov116** [comment]
@Hans5958 I understand your frustration, we are open to suggestions and are willing to allow the users to disable features.

Almost all features you can disable, css only features that we did not feel users would want to disable we did not make options (maybe 20 of them if that many).



We are just asking you to
1. Open an issue with the feature you need to be disabled (see https://github.com/sindresorhus/refined-github/issues/3773 for example)
2. Explain why we should add an option to disable it.

We will then determine if it makes sense to add an option.

Thanks for your feedback.

**Comment by Hans5958** [comment]
I'm not frustrated at all. I just wanted to give you my point-of-view of this issue.

My suggestion is not just to allow disabling some features, but to let us disable all features without exception. I have conducted my research before writing an issue. I have read this issue beforehand, and its comments, including issues and PRs that are related to this. Hence, I giving you my point-of-view in this issue instead of creating another issue asking me to disable.

You guys may think that I am entitled or something like that, but I'm here to just giving you guys my feedback without any malice intended. I still apologize for the nature of these comments.
