### ISSUE TITLE
Link `latest-tag-button`’s default branch comparison (#2771) to its changelog

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2861]
#2771 added this piece of information

<table><td><img width="285" alt="" src="https://user-images.githubusercontent.com/1402241/76000733-2b157580-5f15-11ea-8055-11213c60a096.png"></table>

But I think it could be extracted to be its own button linked to its "changelog" view: https://github.com/sindresorhus/refined-github/compare/20.3.4...master

<table><td><img width="283" alt="" src="https://user-images.githubusercontent.com/1402241/76000735-2c46a280-5f15-11ea-88cc-ae1e7484a39e.png"></table>

However it doesn't look as neat or clear anymore.

Maybe with the diff icon? It's what we use in `changelog-link` as well

<table><td><img width="279" alt="" src="https://user-images.githubusercontent.com/1402241/76001125-b2fb7f80-5f15-11ea-9efa-eb239ebe3f36.png">

**Comment by yakov116** [comment]
I love the way it now.

**Comment by kidonng** [comment]
I love the one with the diff icon. It is more clear and (if implemented) provides a useful shortcut.

Currently, if we want to compare the latest release against master branch, we need to:

- More => Compare => Choose base ref => Tags => Select the latest tag (which may not be the first one due to sorting)
![image](https://user-images.githubusercontent.com/44045911/76063950-ab92af80-5fc3-11ea-8684-d23b19f0f210.png)
- Latest tag button => More => Compare => Switch base (one step less than above one, but still inconvenient)

**Comment by fregante** [comment]
> Latest tag button => More => Compare => Switch base (one step less than above one, but still inconvenient)

I'm surprised that the "Switch base" step is required. Maybe it should be swapped

**Comment by kidonng** [comment]
> I'm surprised that the "Switch base" step is required. Maybe it should be swapped

Because you are always comparing the current ref with the master ref, but the master is newer so it will show nothing.

**Comment by fregante** [comment]
This keeps the small number where it is and just adds a clear "compare" icon next to the tag ✌️ 
<img width="149" alt="" src="https://user-images.githubusercontent.com/1402241/76743440-e9859580-6772-11ea-8083-e14c34b88a93.png">
