### ISSUE TITLE
On `commits` page, next to `Newer` and `Older` buttons, add buttons called `Newest` and `Oldest`

### ISSUE THREAD

**Issue by garyking** [sindresorhus/refined-github#2882]
[Example page, where the feature would appear](https://github.com/sindresorhus/refined-github/commits/master)

At the bottom of the page, it says `Newer` and `Older`. It'd be nice to have a `Newest` and `Oldest` button, to jump to the Newest page, and more importantly, to jump to the Oldest page/commit.

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/pull/1922

**Comment by garyking** [comment]
Yeah that's the exact same thing. Sad to see it was never added. I'll leave this issue open, for discussion, for now. Someone can close it, if necessary. I'd still love to be able to jump to the first commit page somehow.

**Comment by fregante** [comment]
Closing because it was already discussed

**Comment by fregante** [comment]
Reopening to track the addition of a Newest button, as discussed in #1922

**Comment by kidonng** [comment]
How about https://github.com/sindresorhus/refined-github/pull/2667#pullrequestreview-338411193?

**Comment by fregante** [comment]
> Newest: I'm not sure but it seems #1922 (comment) is never implemented. However, I doubt its necessity as you can simply use the branch switcher on top left.

You’re right! 🤩

> Oldest: How about #2667

Yeah that’s the obvious link, however that feature works with a single API call because `isRepoRoot` has the commit count. We don’t have that information on the commit list so this feature would require 2 HTTP requests… for a feature of doubtful utility. 

Also the link to the first commit, should one be interested, will be provided in `repo-age` itself hopefully soon, as part of that linked PR. 

I think this can be closed.
