### ISSUE TITLE
New Notifications to Original Style

### ISSUE THREAD

**Issue by shellscape** [sindresorhus/refined-github#2891]
Github is forcing yet another inbox upon us, and I hate it. I don't hate many things. But I hate this. I have enough inboxes to contend with. And I've always felt the old / original style was plenty good enough. It's always worked well for me.

What I propose is sprinkling magic into Refined Github to allow for reverting that interface to something which at least appears to be the old notifications. A post explaining the move: https://github.blog/2020-02-25-your-new-web-notifications-experience-is-here/ and the announcement https://github.blog/2019-11-13-universe-day-one/#notifications

Example URL:
https://github.com/notifications

**Comment by fregante** [comment]
> reverting that interface to something which at least appears to be the old notifications

That's not Refined GitHub. You can suggest specific improvements, but we won't recreate the current interface.

**Comment by shellscape** [comment]
@fregante that's a rather premature close. Come on man, I was all geared up to discuss and get into contributing to the project. Now I've got a salty taste in my mouth. 

Instead of closing, why not ask me to elaborate on what I had in mind, or ask if my intention was to "recreate," as you put it. (Pssst it's not).

**Comment by fregante** [comment]
This is one of those "bring the old X back" requests that are time consuming and time limited: Eventually everyone moves on and they get used to the new UI.

Your request has no specific part you don't like, so it's not actionable in the first place.

Since we are _not_ bringing it back, you can open a new issue with your specific gripes and we can discuss those.

If you really don't like it, a new extension surely will be of interest to many, but we can't rework the whole interface in Refined GitHub.

**Comment by fregante** [comment]
To be clear, feature requests are still welcome, but they should be specific and actionable
