### ISSUE TITLE
`forked-to` only works on some repositories

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2909]
Out of 31 source repos of the forks I have on my account, only on 3 of them (funnily, refined-github is one of them) `forked-to` seems to work.
Example repo where it doesn't work: https://github.com/Cog-Creators/Red-DiscordBot
Screenshot:
![image](https://user-images.githubusercontent.com/6032823/77211461-55b22180-6b04-11ea-8dfa-ef7f6623191b.png)

**Comment by fregante** [comment]
1. Visit https://github.com/jack1142/Red-DiscordBot
2. Wait 1 second
3. Visit https://github.com/Cog-Creators/Red-DiscordBot

Still no? #2892 was meant to fix this...

**Comment by jack1142** [comment]
@fregante I'm using 20.3.16 and same problem in both Chrome and Firefox (with token set it both)

One interesting I noticed when I opened `jack1142/Red-DiscordBot` is that it shows the link to fork (so to `jack1142/Red-DiscordBot`) there:
![image](https://user-images.githubusercontent.com/6032823/77212221-96129f00-6b06-11ea-9166-fbed26370f8c.png)

What's even more interesting, the link on `jack1142/Red-DiscordBot` shows only when I open the fork in Chrome 🤔

**Comment by fregante** [comment]
Can you look into this? The button is not supposed to show on your fork:

https://github.com/sindresorhus/refined-github/blob/eca9e80d26e7e9bc07d27b862c00f795c91f9ed1/source/features/forked-to.tsx#L31-L34

My guess is that you still have an old cache. Perhaps try clearing it in the options (very bottom of the page)

**Comment by jack1142** [comment]
Clearing cache fixed it showing on fork.

The link to fork still doesn't show on source repo.

**Comment by fregante** [comment]
Any errors in Chrome's console?

**Comment by jack1142** [comment]
None that I can see. I looked both in console of background page:
![image](https://user-images.githubusercontent.com/6032823/77260257-2f68bf00-6c87-11ea-8363-202583366234.png)
and of the actual github page.

I'll try to pinpoint the issue tomorrow and give an update then.

**Comment by jack1142** [comment]
I did a little debugging at it appears that `isForkedRepo()` call here returns `false`:
https://github.com/sindresorhus/refined-github/blob/master/source/features/forked-to.tsx#L90

I checked what that function does and by the looks of it, it checks if the repo is a fork and the page where the link should show is definitely not a fork (which I also verified by checking that meta attr - it's set to `false`):
https://github.com/sindresorhus/refined-github/blob/master/source/libs/page-detect.ts#L355

So the problem appears to be that the function checks if the repo is a fork rather than if the repo has forks.

**Comment by fregante** [comment]
Right, `isForkedRepo` means "is current repo a fork", not "current repo HAS forks", so the function does what it means to do.

The feature never really checks whether the current repo was forked because this feature is useful in the few situations where YOU forked a repo and are regularly contributing to it from the fork. Most repos you see are not in this situation, and we don't want to make HTTP calls unless they're useful _most of the time_.
It's explained there:

https://github.com/sindresorhus/refined-github/blob/6c46766237ccbf8a8c23ba07aca1e48a11a71b4b/source/features/forked-to.tsx#L88-L89


This is why I suggested doing this:

> 1. Visit [jack1142/Red-DiscordBot](https://github.com/jack1142/Red-DiscordBot) (the fork)
> 
> 2. Wait 1 second
> 
> 3. Visit [Cog-Creators/Red-DiscordBot](https://github.com/Cog-Creators/Red-DiscordBot) (the source)

It first needs to see the fork, and **then** it adds the button on the source repo.

**Comment by fregante** [comment]
If after following those instructions you don't see the link to the fork added to the source repo, it may be because:

- the fork isn't being remembered
- the fork isn't being associated to the right source (<- most likely)
- the DOM has changed (it should throw an error)

Try this in the background page:

```js
await browser.storage.local.get()
```

And look for something like `cache:forked-to:cog-creators/red-discordbot`

It can help you understand why it's not being associated correctly.

**Comment by jack1142** [comment]
@fregante Ah, that makes sense. I checked the local storage and cache works (not a lot of entries since I cleared the cache 2 days ago/yesterday):
```
cache:forked-to:jack1142@Cog-Creators/Red-DiscordBot:
data: ["jack1142/red-discordbot"]
maxAge: 1585402612639
__proto__: Object

cache:forked-to:jack1142@jelmer/python-fastimport:
data: ["jack1142/python-fastimport"]
maxAge: 1585336802470
__proto__: Object

cache:forked-to:jack1142@sindresorhus/refined-github:
data: ["jack1142/refined-github"]
maxAge: 1585402706428
__proto__: Object
```

So looks like the problem here is that the repo key should be lowercase (I manually added lowercase cache entry and now the fork link works)
