### ISSUE TITLE
"Merged" and "Closed" buttons in `extend-discussion-status-filters` link to opposite filters

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2913]
"Merged" button links to closed PRs and "Closed" button links to merged PRs.
Example URL: https://github.com/sindresorhus/refined-github/pulls
Screenshot:
![image](https://user-images.githubusercontent.com/6032823/77216488-e0058000-6b1a-11ea-8425-6d152ca742aa.png)
![image](https://user-images.githubusercontent.com/6032823/77216491-eb58ab80-6b1a-11ea-9aa9-1510be947c6a.png)

**Comment by fregante** [comment]
Thank you for the report! This was because the `SearchQuery` parser was being created for the Closed link and then edited later thinking it was the Merged link.

Also I noticed that they made PR lists responsive so there are 2 pairs of Open/Closed buttons: one for mobile view and one for the regular view
