### ISSUE TITLE
`expand-all-hidden-comments` doesn't work on super-long issues

### ISSUE THREAD

**Issue by jarrah31** [sindresorhus/refined-github#2931]
I'm attempting to expand all 671 comments found in this issue: https://github.com/Koenkk/zigbee2mqtt/issues/1429

I have the Refined Github extension v20.3.16 added to Google Chrome v80.0.3987.149 on MacOS 10.15.3, and I have added a personal token within Options.

When I Option+Click the "Load More..." link, it very quickly disappears and just shows the first of the latest set of comments from 8 days ago. e.g.

![image](https://user-images.githubusercontent.com/3072303/77534560-cb194b80-6e90-11ea-9fcd-425fa4c76942.png)

After trying Opt+Click:
![image](https://user-images.githubusercontent.com/3072303/77534579-d7050d80-6e90-11ea-8eff-0c281f7b7837.png)

This is the related pull request: https://github.com/sindresorhus/refined-github/pull/2754

TIA

**Comment by yakov116** [comment]
Did some debugging. Looks like if you do more than 200, it loads 60 and hides the button

**Comment by fregante** [comment]
I didn't check the limit, but yes, alt-clicking that "Load 672 more..." button returns a 404 instantly.

To be fair, this feature is rather hostile to GitHub because it forces them to render huge pages.

What we can do, if easy, is to limit it to ~200 items, so loading the whole conversation would require 4 clicks instead of the regular 12

**Comment by krystian3w** [comment]
Anybody can write user.js to auto click in link under "X hidden items" in  light loop for browser?
