### ISSUE TITLE
Navigation between unresolved conversations.

### ISSUE THREAD

**Issue by dgeelen-uipath** [sindresorhus/refined-github#2962]
I work on a project which recently switched to GitHub and we're still finding our way around. Thank you for GitHub Refined, it already makes the review process a lot easier than plain GitHub. In our project we often have big pull requests, which garner a lot of change requests. One thing we find is that "unresolved conversations" are often hard to find and navigate in a large diff.

Feature request:
Would it be possible to add some navigation options to show all unresolved conversations and jump between them?

Example URL:

https://github.com/sindresorhus/refined-github/pull/2948

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/343

**Comment by fregante** [comment]
Yeah keeping track of review threads isn't easy, especially because a review at the beginning of the conversation might be "fresher" than the last comment of the page.

I think https://github.com/sindresorhus/refined-github/issues/1270 could help more generically navigate issues (you could skip a resolved thread when you encounter it).

Maybe the header could include up/down arrows specifically to highlight and navigate unresolved conversation.

- If there's an arrow in the header, it means that there are unresolved conversations on the page

**Comment by yakov116** [comment]
Should be merged with #3319

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/issues/1270 already does this since resolved conversations are not open by default and therefore they'll be skipped by it.
