### ISSUE TITLE
Green notifications badge

### ISSUE THREAD

**Issue by dimitarnestorov** [sindresorhus/refined-github#3044]
I've seen all notifications but this badge shows up, usually it's blue. Is that some feature that I'm unaware of? If not then tell me what info to gather because it's not always visible. For example if I go to read notifications and mark one as done it disappears, refresh and it's back.
URL: https://github.com/notifications?query=is%3Aunread (everywhere)
![image](https://user-images.githubusercontent.com/8790386/80682620-8c983180-8acb-11ea-9b13-876d04d71b42.png)
![image](https://user-images.githubusercontent.com/8790386/80682666-a0439800-8acb-11ea-8890-f1154f4ca16c.png)

**Comment by jdreesen** [comment]
Might be this: #683

**Comment by dimitarnestorov** [comment]
How does one view threads marked as unread?

**Comment by fregante** [comment]
You probably used our `mark-unread` feature on the past but it’s currently broken: https://github.com/sindresorhus/refined-github/issues/2801

This specific bug is fixed in version 20.4.28 because the feature has been disabled until someone can fix it. 

If you use Chrome you might have to wait a few days before seeing that new version

**Comment by dimitarnestorov** [comment]
Yes, I used the button.
The button is now also gone.
I guess you can close this issue now.
