### ISSUE TITLE
Make stars and forks buttons useful

### ISSUE THREAD

**Issue by Androz2091** [sindresorhus/refined-github#3064]
I don't know if my suggestion is technically possible, but it would be interesting. Currently the icons displaying the number of stars and the number of forks of a repository are of little use. It would be helpful if I could click on this icon to simply add a star to the repository and if I could click on the other icon to fork the repository.

When the repository is not starred and not forked:

![Capture d’écran 2020-05-05 à 15 23 26](https://user-images.githubusercontent.com/42497995/81071102-80094400-8ee4-11ea-9af5-f2d80ae23785.png)

And when starred and forked, the icons become a little blue:

![Capture d’écran 2020-05-05 à 15 25 57](https://user-images.githubusercontent.com/42497995/81071299-cb235700-8ee4-11ea-8289-737ad38fabe1.png)

It would also be useful to see if we have already added a star to this repository or if we already have a fork of this repository.

**Comment by fregante** [comment]
We hide the same `Star` button in on the dashboard with the reasoning that you probably want to learn more about a projects instead of starring after one sentence

https://github.com/sindresorhus/refined-github/blob/2e5c19a4d8fa7db94e775beeac9b8bd610a2fa2b/source/features/clean-dashboard.css#L85-L89

**Comment by sindresorhus** [comment]
Thanks for the suggestion. Unfortunately, we're going to pass on this.
