### ISSUE TITLE
Restore `reactions-avatars`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3122]
> Github no longer loads who reacted in the aria-label until you hover 😞 
>
> _Originally posted by @yakov116 in https://github.com/sindresorhus/refined-github/issues/3120#issuecomment-632331245_

`reactions-avatars` stopped working (https://github.com/sindresorhus/refined-github/issues/3120) because of this change.

The feature used to look like this:

<img src="https://user-images.githubusercontent.com/1402241/34438653-f66535a4-ecda-11e7-9406-2e1258050cfa.png">

Since the usernames are no longer available on the DOM _until it's too late,_ the only fix is to load these usernames via the API.

The problem is that this call might be rather large on very active discussions, so this might no longer be worth it.

PR welcome to figure out what changes are required and what the impact would be on large conversations like https://github.com/facebook/react/issues/13991

**Comment by fregante** [comment]
Another solution to consider is to trigger GitHub’s requests and then update add the avatars once they load. 

This causes multiple requests per page but… this feature is already relatively heavy HTTP-wise (it loads dozens of avatars separately)

This has the advantage of:
- not having to figure out and maintain an API cal
- essentially preloading GitHub’s own requests

HTTP requests can be limited/staggered by triggering the requests a bit before they enter the viewport using IntersectionObserver with 1000px margin

**Comment by jef** [comment]
> Another solution to consider is to trigger GitHub’s requests (those that happen on hover)

I think this even has changed. I could be wrong, but doesn't seem to be making those calls anymore either. We'd have to explicitly call for all the separate types (issue/pr comments, issue/prs). Not too hard, but different.

That being said, just for one comment:

- Using without `content`, it grabs up to 30 users. Seems to be the first 30.

![image](https://user-images.githubusercontent.com/12074633/82721104-49734d80-9c88-11ea-9efd-241748e2a80f.png)

- With `content`, same as before. Up to 30 users, probably the first 30.

![image](https://user-images.githubusercontent.com/12074633/82721189-f0f08000-9c88-11ea-82be-8fa5b574f712.png)

I'm assuming the first 30 because of timestamp. Not sure if this helps at all -- y'all probably already knew this.

> ...this feature is already relatively heavy HTTP-wise (it loads dozens of avatars separately)

~240ms response though with 30kb of data just for one issue comment that has 30+ reactions across the board. Luckily we have asynchronous :laughing: Still quite a bit of time though, you're right.

**Comment by fregante** [comment]
Neither solution is great, I’d very much prefer triggering GitHub’s own queries on hover than calling the API, as I mentioned in my comment.

**Comment by jef** [comment]
> Neither solution is great, I’d very much prefer triggering GitHub’s own queries on hover than calling the API, as I mentioned in my comment.

I thought this was broken, but it actually might be the browser. Not sure, but I do see that label getting updated.

Much better implementation.

**Comment by yakov116** [comment]
Looks like github went back to the old way!!

**Comment by fregante** [comment]
PR welcome to drop the first ~10 lines of `showAvatarsOn`
