### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by mfulton26** [sindresorhus/refined-github#3198]
Can [/refined-github/releases](https://github.com/sindresorhus/refined-github/releases) be used instead of [/refined-github/issues/1137](https://github.com/sindresorhus/refined-github/issues/1137) to provide details on releases? Would that not be more intuitive or are there some features that "Releases" does support? Thank you.

**Comment by fregante** [comment]
Yes, I'd love this to be automated as well. A PR would be welcome to automatically generate releases inside the deployment workflow (https://github.com/sindresorhus/refined-github/pull/3190)

A few notes though:

- This has to be **automated**, I'm not gonna create release notes manually weekly; https://github.com/sindresorhus/refined-github/issues/1137 is updated monthly at best.
- This shouldn't force us to tag each commit like `fix(pencil)`, `feat(yaddayadda)` because that's still extra work that we'll forget to follow.

Also this means that

- The Releases page won't be very different from the commits page, which already includes all commits and their tags: https://github.com/sindresorhus/refined-github/commits/master

The best solution for this would be a simple GitHub Action that does this in one or two lines, without extra effort.

**Comment by fregante** [comment]
## 🙌  https://github.com/sindresorhus/refined-github/releases/tag/20.9.10

**Comment by yakov116** [comment]
Awesome!
