### ISSUE TITLE
Disable code linkify and whitespace showing for very long files and pages

### ISSUE THREAD

**Issue by aminya** [sindresorhus/refined-github#3218]
I sometimes open a very long files or the files tab in the pull request page, and I feel that showing the code is slowed down because of refined-github DOM modifications.

**Comment by fregante** [comment]
Example URL please, as the issue template suggested.

**Comment by fregante** [comment]
`show-whitespace` is not the culprit, it already only acts on the visible lines.

**Comment by aminya** [comment]
> Example URL please, as the issue template suggested.

This one for example https://github.com/aminya/SnoopCompile.jl/pull/1/files

**Comment by fregante** [comment]
Most features affect the loading time because they apply their changes all at once — This _could_ be be `linkify-code` — and don't affect the scrolling once that's done (it's only a handful of changes usually)

`show-whitespace` is one of the most intensive features, which is why it was modified to only act on a few lines at a time to avoid locking the document at the beginning.

This is probably the only feature that could affect the scrolling performance, but I don't personally notice any differences in scrolling in neither browser (my notebook is from 2013)

Do you have any other extensions running?

**Comment by aminya** [comment]
I can test using a safe mode setup with refined Github only, and will return back to you.

**Comment by fregante** [comment]
Let me know if this is still an issue, if you have more info
