### ISSUE TITLE
"The HEAD of master isn't tagged" but no commit count on `latest-tag-button`

### ISSUE THREAD

**Issue by flatcap** [sindresorhus/refined-github#3228]
The latest-tag feature doesn't show the number of commits, just `+`.

The latest tag for my project, [NeoMutt](https://github.com/neomutt/neomutt), is [`20200501`](https://github.com/neomutt/neomutt/tags).
`master` is currently 115 commits ahead of this tag.

![tag](https://flatcap.org/mutt/tag.png)

- https://github.com/neomutt/neomutt
- https://github.com/neomutt/neomutt/releases
- https://github.com/neomutt/neomutt/tags

My release commits are signed.
My tags are annotated and signed.

Annotated tags are a link to a message object which links to a commit.
Perhaps we're missing a lookup.

Note: The commit history for `master` is linear.  Releases aren't in branches.

<sub>edit: add note about history</sub>

---

Many thanks for creating Refined-Github :heart:

**Comment by fregante** [comment]
Yes, this is by design:

- the previous solution didn't work on some repos (GitHub wasn't showing some required information) https://github.com/sindresorhus/refined-github/issues/2927
- GitHub doesn't offer a lightweight way to compare branches. The API endpoints we found could take **a few seconds** to respond with a sizable HTTP response if the comparison was large https://github.com/sindresorhus/refined-github/pull/2771#discussion_r378109419
- the initial objective of the feature was to tell you **_whether_** HEAD was tagged https://github.com/sindresorhus/refined-github/issues/2601

We added the number to understand _how stale_ it was, but after a certain number it doesn't matter anymore: It just means that _it's very stale._

We still show the number, but we only look for the first 20 commits due API limitations. Anything more it's "undeterminable", also because on some repos the tags are not on the same branch at all, so it could be just 1 commit behind, but we can't know without a proper _Compare_ API.

**Comment by flatcap** [comment]
OK.  Thanks for explaining.
(love the Impossible tag :-)
