### ISSUE TITLE
default-branch-button doesn't actually use default branch

### ISSUE THREAD

**Issue by DianaNites** [sindresorhus/refined-github#3239]
The default branch button normally only appears when you're not currently on the default branch, but github allows repositories to change the default branch, which causes the button to *always* appear.

Button appears, despite being on the (different) default branch

![Screenshot_20200615_214643](https://user-images.githubusercontent.com/5275194/84722622-b7dac100-af51-11ea-805f-f620f0e43d78.png)

No button when on the default branch

![Screenshot_20200615_214245](https://user-images.githubusercontent.com/5275194/84722416-29fed600-af51-11ea-86ab-6c77cfa8c11d.png)

Button when not on the default branch

![Screenshot_20200615_214604](https://user-images.githubusercontent.com/5275194/84722635-c6c17380-af51-11ea-803e-7124e01dee14.png)

**Comment by yakov116** [comment]
We dont check every time you visit a repo if the default branch changed. Since changing a default branch is not a common thing, we check once every 10 days.

Either you can wait for the 10 days or you can clear the cache from the extension options.

**Comment by yakov116** [comment]
@fregante I think we should add a detection if the branch is “main” and the default is “master” then re validate. Due to many people changing the master branch to main.

**Comment by DianaNites** [comment]
Oh, there is a check? Is that documented anywhere?

Clearing the cache did correct the issue, so not a bug I guess.

**Comment by fregante** [comment]
> I think we should add a detection if the branch is “main” and the default is “master” then re validate.

That means "always fetch unless you're on the default branch"

Changing default branch is not a common action so we shouldn't slow down the other hundred thousand "get default branch" requests for that.

What we _could_ do is speed up this getter since it's one of the most common information we use.

For example, when you're on `isRepoRoot`, you're _definitely_ on the default branch. This means:

- we can use the `current branch` value, already on the page
- we can skip/refresh the cache https://github.com/fregante/webext-storage-cache/issues/18

If anyone wants to add the first part: https://github.com/sindresorhus/refined-github/commit/1de71bb0a7b1b60d6dd123dd6699f346029399f8

**Comment by yakov116** [comment]
Another detection can be when your on the branches page, the default branch is there.

**Comment by yakov116** [comment]
@fregante wasn't this done?

**Comment by fregante** [comment]
> * we can use the `current branch` value, already on the page
> 
> * we can skip/refresh the cache [fregante/webext-storage-cache#18](https://github.com/fregante/webext-storage-cache/issues/18)

Neither one of this is done. This commit hasn't been merged: https://github.com/sindresorhus/refined-github/commit/1de71bb0a7b1b60d6dd123dd6699f346029399f8

See: https://github.com/sindresorhus/refined-github/blob/master/source/github-helpers/get-default-branch.ts

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/pull/3261 did the first half of the issue and https://github.com/sindresorhus/refined-github/issues/3302 will avoid it in most cases.
