### ISSUE TITLE
`forked-to` works inconsistently

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#3284]
I would say this feature doesn't work consistently from time to time, ~~but it seems to completely stop working after the design update.~~ you can notice the missing of "Go to own fork" button below.

Also, there is background flashing caused by Refined GitHub, but I'm not sure if it's related to`forked-to`.

![c2KP0kU87c](https://user-images.githubusercontent.com/44045911/85748328-912f3e00-b73a-11ea-9460-db58ae1a92ac.gif)

Well, there are two ways to trigger the flash:

- The first opening of fork popup (this only happens once if you don't refresh the page)
- When fork popup is open, click outside of the popup to close it (Strangely I can't screenshot it)

**Comment by fregante** [comment]
I didn't see it 2 hours ago, but now I see it. The selector is probably right

<img width="539" alt="" src="https://user-images.githubusercontent.com/1402241/86268179-12b61e80-bbc8-11ea-9bc4-2ce0bb425442.png">

**Comment by kidonng** [comment]
Now I see it in other repos, but I never see it on this repo after design update 🤣

**Comment by notlmn** [comment]
Can't say why `forked-to` fails but the flashing is because of `z-index` from `sticky-discussion-sidebar` feature

https://github.com/sindresorhus/refined-github/blob/594bca7ff4a34ad18fd5cb932c0b2e628e7a9fe0/source/features/sticky-discussion-sidebar.css#L1-L3

Droppping all `z-index` related code in that feature seems to do the trick.

**Comment by kidonng** [comment]
Closing as I no longer have this problem. Regarding the flashing issue, thanks @notlmn I will open an issue/PR later.
