### ISSUE TITLE
How disable align-repository-header feature?

### ISSUE THREAD

**Issue by cipchk** [sindresorhus/refined-github#3336]
It conflict with [Gitako](https://github.com/EnixCoda/Gitako) caused misalignment.

png:

![image](https://user-images.githubusercontent.com/2987467/87215155-12efb000-c366-11ea-8ee3-c2b8b9f6bbeb.png)

**Comment by quangkieu** [comment]
I think the cause is on this.
https://github.com/sindresorhus/refined-github/compare/20.7.2...20.7.9#diff-765d4988f08edb45ad447cfeab8a3421R3
Could we have a switch to disable the padding left for those do not want it. And could we change it to something smaller like cal(10%) is what I found reasonable.

**Comment by fregante** [comment]
We can *try* to fix the conflict with it

**Comment by ZackBoe** [comment]
This gets weirder at larger resolutions:
![image](https://user-images.githubusercontent.com/904055/87233473-a391b480-c395-11ea-94c1-800c52ca9d65.png)

**Comment by fregante** [comment]
This is not due to Refined GitHub. It happens even after you disable it

**Comment by fregante** [comment]
Actually, that was incorrect, I had some extra CSS being applied even without Refined GitHub.

However, Gitako here is adding some styles (that do essentially the same thing) but probably shouldn't, because Gitako’s intent is supposedly to add a file tree, not change the layout.

So you can open an issue on their repo asking to drop this unrelated change. 

# Regular (no extensions)

![reg](https://user-images.githubusercontent.com/1402241/87233958-917f3880-c3cc-11ea-83ee-47d4e784527f.png)


# Gitako

Notice the misaligned header and commit content

![gitako](https://user-images.githubusercontent.com/1402241/87233960-9512bf80-c3cc-11ea-9036-6632bf72871f.png)

**Comment by cipchk** [comment]
@fregante I have a suggestion to remove `!important` because `body:not(.full-width):not(.enterprise) .repohead> * {` has sufficient priority.

**Comment by fregante** [comment]
@cipchk That element has a `!important`, so we must also use `!important`

**Comment by fregante** [comment]
This feature has now been dropped in https://github.com/refined-github/refined-github/pull/6247
