### ISSUE TITLE
Ability to expand all collapsed code in PR diffs - 2

### ISSUE THREAD

**Issue by msugakov** [sindresorhus/refined-github#3436]
I'd like to follow-up on the existing issue that was closed for commenting and I can no longer make comments there. https://github.com/sindresorhus/refined-github/issues/2151

![Peek 2020-08-06 11-20](https://user-images.githubusercontent.com/537715/89515085-f0bb4780-d7d6-11ea-8eb9-ff4956bbd0e0.gif)

I'm Linux user (xubuntu 20.04) with Firefox 79.0. I cannot use the feature to expand the entire diff' context using Alt+click. There's either browser's menu shown on Alt button press or just no reaction when clicking the diff expander while Alt is pressed.

Is there a way to make use of the feature for me?  
I find this is really crucial to be able to see the entire file and it's surprising GitHub doesn't provide that natively.

**Comment by fregante** [comment]
Thanks for the GIF, that explains it. This is very likely due to the menu bar: when you press alt, the “mouseup” event (and therefore the “click” event) is no longer triggered on the button itself. 

That is preventing you from using “alt-click” anywhere on the web. I don’t think that there’s a solution to this very niche issue that should probably be avoided by your browser, not us.

**Comment by msugakov** [comment]
Thanks for taking a look! I think, there were Windows and Linux users who reported the similar issue in the previous thread, [link](https://github.com/sindresorhus/refined-github/issues/2151#issuecomment-603357055). Basically, not everyone works or wants to work on Mac. Is there a possibility to remap modifier key to Shift or introduce a hotkey like Alt+E?

**Comment by fregante** [comment]
Windows and Linux don’t have an alt key? Other maintainers have Windows and it works there. 

Try this: zoom the page at 300%, try alt clicking. This should make sure that the mouseup/click event ends up on the button even after the content shift. Does it work? If not, can you post a gif again?

**Comment by fregante** [comment]
Alternatively, I think that the right alt key doesn’t show the menu. Can you try alt-clicking with that?

**Comment by msugakov** [comment]
Did both left and right Alts with 300%, same results. Right Alt does show the menu though.
If I reconfigure right Alt to be a compose key, browser's menu isn't shown but that does not help still.

Left Alt + 300%
![Peek 2020-08-06 16-36 - left 300](https://user-images.githubusercontent.com/537715/89545182-53c2d380-d803-11ea-992e-cf104ebbd421.gif)

Right Alt + 300%
![Peek 2020-08-06 16-36 - right 300](https://user-images.githubusercontent.com/537715/89545187-54f40080-d803-11ea-84e9-86c86c322ae0.gif)

**Comment by fregante** [comment]
According to this page, Linux users should be able to alt-click links to download the linked page: https://support.google.com/chrome/answer/157179?hl=en-GB

This should work on every system. Does it work for you?

**Comment by msugakov** [comment]
Just tried in Chromium 84.0.4147.105, it does not work still.
Would it be really so difficult to enable another modifier key?

**Comment by fregante** [comment]
> Would it be really so difficult to enable another modifier key?

We do have [5 separate features](https://github.com/sindresorhus/refined-github/search?q=altkey&unscoped_q=altkey) that use the alt key a GitHub themselves have alt-clicks: <img width="434" alt="" src="https://user-images.githubusercontent.com/1402241/89634078-b4521f00-d89c-11ea-8d52-703cf6439bbf.png">


Adding an alternative modifier means that we have to support it, document it, and it would also exclude the modifier from future use.

> Just tried in Chromium 84.0.4147.105, it does not work still.

It sounds like a whole host of software shortcuts isn't going to work for you then and I generally think it's better to solve the problem at the root, rather than force this onto a 3rd party.

**Comment by msugakov** [comment]
MDN's info on [MouseEvent.altKey](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/altKey):

> Be aware that the browser can't always detect the alt key on some operating systems. On some Linux variants, for example, a left mouse click combined with the alt key is used to move or resize windows.

That's the case for xfce. This is very convenient.
Rebinding Alt to Super (Windows) for windows moving/resizing as suggested here https://unix.stackexchange.com/a/86831 helps.

The feature works now for me.

![Peek 2020-08-07 12-18](https://user-images.githubusercontent.com/537715/89636002-3267f300-d8a8-11ea-8b80-a905cfe05d1a.gif)

Thanks!

**Comment by fregante** [comment]
Excellent! Thanks for reporting a solution
