### ISSUE TITLE
Exclude 0.0.0 tags from `latest-tag-button`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3464]
Example: https://github.com/facebook/react

<img width="448" alt="" src="https://user-images.githubusercontent.com/1402241/90318931-cdf20700-df2b-11ea-8f90-5d01caf180a1.png">

**Comment by yakov116** [comment]
That is failing on

https://github.com/sindresorhus/refined-github/blob/e93ffb711e3739cd53928aac2fb76eda5b456b7e/source/github-helpers/index.ts#L77-L78

**Comment by fregante** [comment]
Something like

```js
const excludedVersion = /^[vr]?0\.\0\.\0/;
```
```diff
- if (!tags.every(tag => validVersion.test(tag))) {
+ if (!tags.every(tag => validVersion.test(tag) && !excludedVersion.test(tag))) {
```

**Comment by yakov116** [comment]
@fregante the issue is


["v0.0.0-experimental-d7382b6c4", "v0.0.0-d7382b6c4", "v16.13.1", "v0.0.0-experimental-aae83a4b9", "v0.0.0-experimental-8b155d261", "v16.13.0", "v16.12.0", "v16.11.0", ***"status"***, "v16.10.2", "v16.10.1", "v16.10.0", "v16.9.0", "v16.9.0-rc.0", "v16.9.0-alpha.0", "1.2.5", "v16.8.6", "v16.8.5", "v16.8.4", "v16.8.3"]

That _**status**_ is not a valid version

**Comment by fregante** [comment]
??

The issue is **not** that. Status is already taken care of by that line.

**Comment by fregante** [comment]
Ah you’re right
