### ISSUE TITLE
Pull Request header is not showing the base branch

### ISSUE THREAD

**Issue by bbugh** [sindresorhus/refined-github#3508]
Example link: `https://github.com/organization/repository/pull/1800`

With the extension:

<img width="385" alt="Pasted_Image_8_27_20__10_07_AM" src="https://user-images.githubusercontent.com/438465/91460176-217a2400-e84d-11ea-9518-be4d10eff46b.png">

Without the extension:

<img width="711" alt="Pasted_Image_8_27_20__10_06_AM" src="https://user-images.githubusercontent.com/438465/91460099-0ad3cd00-e84d-11ea-97ef-bd49331b2f59.png">

Version: 20.8.23

**Comment by kidonng** [comment]
Is `develop` your default branch? This is a feature called [`clean-conversation-headers`](https://github.com/sindresorhus/refined-github/blob/master/source/features/clean-conversation-headers.tsx)

**Comment by bbugh** [comment]
It is indeed. I looked around in the settings and couldn't find anything about it, and couldn't imagine why anyone would want it as a feature, so I thought it might be a bug. Thanks for the help.

**Comment by fregante** [comment]
> and couldn't imagine why anyone would want it as a feature

Because the vast majority of PRs are towards the base branch, so that information is useless in most cases: https://github.com/sindresorhus/refined-github/issues/3089

`clean-conversation-headers` will instead **highlight** the branch when it's not towards the default branch: https://github.com/sindresorhus/refined-github/pull/3480

So the feature serves 2 purposes: reduces noise while making _the signal_ clearer.
