### ISSUE TITLE
Ability to remotely disable broken features

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3529]
Crazy idea, but occasionally we have very breaking bugs that cause frustration: https://github.com/sindresorhus/refined-github/issues/3527 https://github.com/sindresorhus/refined-github/issues/2357 https://github.com/sindresorhus/refined-github/issues/1805 https://github.com/sindresorhus/refined-github/pull/1148 https://github.com/sindresorhus/refined-github/issues/2700 [etc](https://github.com/sindresorhus/refined-github/issues?q=label%3Abug+is%3Aclosed+sort%3Areactions-%2B1-desc)

These are often fixed quickly, but users have to suffer it until the browser updates the extension, which could be a day later.

We could have a mechanism that pings this repo to check whether a feature should be temporarily disabled. For example inside [`globalReady`](https://github.com/sindresorhus/refined-github/blob/e1d836a2f542bb77e9510e5c5aaed2af8c572c91/source/features/index.tsx#L105)

```js
const options = await optionsStorage.getAll();
const hotfix = await cache.get('hotfix');
fetchHotfixesAsynchronously(); // `cache.function` to be run up to ~4 times a day?
Object.assign(options, hotfix);
```

`fetchHotfixesAsynchronously` could fetch the content of a dedicated, locked issue with a content like:

```js
false
```

or

```js
{"cleanup-repo-filelist-actions": false, "unaffected": "20.9.4"}
```

`fetchHotfixesAsynchronously` would use `looseVersionCompare` to compare `unaffected` with the current version and either store `{'cleanup-repo-filelist-actions': false}` or `{}` accordingly.

## Notes

Performance: up to 4 fetches a day should make it lightweight enough
Privacy: it would only fetch public content on GitHub, only if you open GitHub
Security: it would only `GET` JSON content from api.github.com, it doesn't `POST` anything

**Comment by shinenelson** [comment]
I would say the points under the 'Notes' section should be the **Acceptance Criteria**.

**Comment by shinenelson** [comment]
Also, it would make sense to make it a 'feature' so that users can opt-in for these hotfixes. If not, they are at their own risk.

This could possibly go into the "Debugging" section in the Preferences tab of the extension.

**Comment by shinenelson** [comment]
I have not developed on a WebExtension before, but I'm willing to try. Is this 'good-first' enough for a person like me?

**Comment by fregante** [comment]
> Also, it would make sense to make it a 'feature' so that users can opt-in for these hotfixes. If not, they are at their own risk.

No, it would not make sense. This solution is meant to be instant and for the user’s own good.


> Is this 'good-first' enough for a person like me?

That'd be great! You can try following `contributing.md` and keep it simple. I think the code is not far from:


```js
const fetchHotfixesAsynchronously = cache.function(async () => {
	const response = await fetch('https://raw.githubusercontent.com/sindresorhus/refined-github/hotfix/hotfix.json');
	const hofixes = await response.json();
	if (!hotfixes) {
		return {};
	}

	if (hotfixes.unaffected) {
		const currentVersion = await browser.etc get version()
		if (looseVersionCompare(hotfixes.unaffected, currentGetVersion) >= 0) {
			return {};
		}
	}

	return hotfixes;
}, {
	maxAge: {hourse: 6},
	key: 'hotfix'
});
```

And we can change this file: https://github.com/sindresorhus/refined-github/blob/hotfix/hotfix.json

If there are no hotfixes, the content will be `false`, which AFAIK is valid JSON

**Comment by shinenelson** [comment]
Great, I'm going to try this and see how close I can get. Thank you for the code example. That is a head-start.

As for the files, do we need to introduce a new directory in the tree for one file? I don't see anything that could expand into that directory. I'm thinking along the lines of `source/hotfix.ts` and `source/hotfix.json`. Does that make sense?

**Comment by shinenelson** [comment]
straying away from the KIS philosophy, I'm going to ask this question : what if, somehow, my browser did not update my extension to an offending version but the hotfix poll would disable the feature for me anyway?

also, how often do we keep updating `hotfix.json`? I mean, how long does a hotfix version stay in the `hotfix.json` file before it is deemed safe to be cleared?

because I'm ignoring KIS philosophy for this comment, I want to elaborate and include a `first` and `last` tag to `hotfix.json` that looks like : 
```json
{
    "cleanup-repo-filelist-actions": {
        "first": "20.9.3",
        "last": "20.9.4"
    }
}
```
that indicates when a bug was introduced and when it was fixed. the version compare logic should apply to the versions in between.

I guess this can be the next iteration, let me see if I can get the first iteration working in the first place.

**Comment by yakov116** [comment]
LooseVersionCompare would tell you if your current version is after the first unaffected

**Comment by yakov116** [comment]
Another thing to keep in mind that it should not disable debug versions otherwise it will be impossible to fix.

**Comment by fregante** [comment]
> As for the files, do we need to introduce a new directory in the tree for one file?

No we can just keep exactly this file on the `hotfix` branch: https://github.com/sindresorhus/refined-github/blob/hotfix/hotfix.json

So we can change it at will without making changes on master.

> straying away from the KIS philosophy

Let's not. 😁

> also, how often do we keep updating `hotfix.json`

This happens **once or twice a year** and the file is only meant to last less than a week to ensure everyone has updated, so it doesn't need to be that complicated at all. This solution is only to cover extreme breakage until a new version is pushed and downloaded (which already has its own [mechanism to disable broken features](https://github.com/sindresorhus/refined-github/blob/f527259f797d18964483d2e065d13d4dfbe36200/source/features/index.tsx#L22)). After 7 days the file will likely be reset to `false`. This is not meant to be a perennial list of broken lists.

> include a `first` and `last` tag

If some user on an older, unaffected version of RG loses access to feature `xyz` for 7 days, it's not a big deal. Refined GitHub is progressive enhancement; the lack of (part of) it is not a deal-breaker.

**Comment by fregante** [comment]
> Another thing to keep in mind that it should not disable debug versions otherwise it will be impossible to fix.

Good point, in our case it that means:

```js
const hotfix = chrome.manifest.version !== '0.0.0' && await cache.get('hotfix');
```

**Comment by shinenelson** [comment]
> on the hotfix branch

this was the only fact that I missed to notice. Though it was the most important fact to not miss. :facepalm:

If it is not on `master`, then none of my arguments really matter at all.

I'm going to put some extra attention and read all the comments on this issue more carefully so that I don't miss any more of the direct instructions like this.

**Comment by fregante** [comment]
One last piece of code would be also run `cache.delete('hotfix')` when the extension is updated, which is this listener: https://github.com/sindresorhus/refined-github/blob/master/source/background.ts#L24

**Comment by shinenelson** [comment]
I am kind of lost at `looseVersionCompare`.
1. Is that a function that is already present somewhere in the codebase?
2. Is it a package I need to add?
3. Is it an `export` of the `tiny-version-compare` package that is already included as a dependency?

My answer to all of those questions after digging into the codebase is 'no'.

1. `git grep --ignore-case looseVersionCompare` yielded no results
2. I looked for [loose version compare on npmjs.com](https://www.npmjs.com/search?q=loose%20version%20compare) in vain. However, I found a ( 2-year-old ) version of a package on an [aliyun npm mirror](https://developer.aliyun.com/mirror/npm/package/loose-version-compare) that apparently seems like [a predecessor](https://github.com/fregante/tiny-version-compare/releases/tag/v0.9.0) of `tiny-version-compare`.
3. I dug into the [source](https://github.com/fregante/tiny-version-compare) of `tiny-version-compare` and could not find an export called `looseVersionCompare`. There is only a single function export. So does that mean I should `import looseVersionCompare from tiny-version-compare`?

Also, `tiny-version-compare` is currently being imported only in `source/features/tag-changelog-link.tsx` and `source/github-helpers/index.ts` ( with 2 different names; because function `export` ) at the moment

I need some pointers here.

---
I also made some changes to the pseudo-patch provided in https://github.com/sindresorhus/refined-github/issues/3529#issuecomment-687367554. I'm putting them here to validate if I'm on the right track.

```diff
-		const currentVersion = await browser.etc get version()
+		const currentVersion = await browser.extension get version()
```
```diff
-		if (looseVersionCompare(hotfixes.unaffected, currentGetVersion) >= 0) {
+		if (looseVersionCompare(hotfixes.unaffected, currentVersion) >= 0) {
```
```diff
-	maxAge: {hourse: 6},
+	maxAge: {hours: 6},
```

**Comment by shinenelson** [comment]
I made 2 assumptions and opened #3530 : 
1. `import looseVersionCompare from tiny-version-compare`
2. all the other changes that I mentioned that I made in https://github.com/sindresorhus/refined-github/issues/3529#issuecomment-687473518 are correct.

If I am wrong, please point them out on the pull request review.

**Comment by shinenelson** [comment]
I learnt the hard way that `browser.etc get version()` meant _find the corresponding browser API that provides the installed extension's version_. The tests and build failed on me. I didn't think of it earlier, but I eventually found `browser.runtime.getManifest().version`.

**Comment by fregante** [comment]
> I am kind of lost at `looseVersionCompare`.

Sorry about that! It's my own module and I even forgot how I named it 😅 

Everything else in right. I wrote that code in the comment box to explain clearly what I had in mind, expect typos and subtle exceptions because I didn't run it.
