### ISSUE TITLE
Automatically disable wiki and project features

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/refined-github#3533]
I don't personally use the wiki or project features in repositories so it would be useful for them to be automatically disabled on creation.

**Comment by fregante** [comment]
Not a bad idea, we’d look for the “repository/new” page and make an API call after it. 

@sindresorhus do you know whether it’s still not possible to have them disabled natively? I think they implemented this for organizations, with a repository named `.github`

**Comment by yakov116** [comment]
Almost done: (Needs more work like to use `postForm` etc.)
https://github.com/yakov116/refined-github/commit/24086419244e798311a12a3cbe59508592ae2f2d

@fregante should we add a checkbox like we do by auto merge after tests pass? (forgot what the feature is called)

**Comment by sindresorhus** [comment]
> @sindresorhus do you know whether it’s still not possible to have them disabled natively? I think they implemented this for organizations, with a repository named .github

Not as far as I know.

**Comment by fregante** [comment]
> should we add a checkbox

Not a bad idea, but instead of breaking and posting the form, this feature should only **remember** that a repository was just created, but then it should run on the next page, so we don’t have to handle (and potentially break) the creations form. 

You can add sessionStorage on submit; then detect it in isRepoRoot and make the api call

**Comment by yakov116** [comment]
> so we don’t have to handle (and potentially break) the creations form.

Agree that was my next issue
