### ISSUE TITLE
Add a pin icon next to the pinned issue title

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#3575]
Add a pin icon next to the pinned issue title. Therefore, I can see if this issue is pinned after I open an issue.

URL: https://github.com/sindresorhus/refined-github/issues/2730

**Comment by fregante** [comment]
Please include a real URL where this would appear, like asked by the Issue Template.

**Comment by Geeyun-JY3** [comment]
This feature should apply to every pinned issue.The URL should be like `https://github.com/:owner/:repo/issues/***`, but only the pinned issue in the repository. So I cannot give a specific real URL.
If you really want me to give a real URL, for instance, https://github.com/sindresorhus/refined-github/issues/2730.

**Comment by yakov116** [comment]
While this is useful information (such as a popular issue) I don't know if this is worth an api call. Since it would requesting at least every day to make sure it's not stale and the info is on the issue list page.

If this is accepted it should work off the cache of `pinned-issues-update-time`.

About position maybe put it where a collaborator would see it (in the side bar).

**Comment by Geeyun-JY3** [comment]
@yakov116 It depnds on you😉. I am OK.

**Comment by yakov116** [comment]
Did some research as of now that is the **only** way. 
https://github.community/t/filter-issue-search-by-pinned-issue/133325

I am 👎 on this until there is a possible API request. Since the feature will not work at all until the user visits the issue list page.

@fregante WDYT?

**Comment by fregante** [comment]
Yeah not really worth it, doesn't seem like useful information once you're already in the issue.
