### ISSUE TITLE
Prepare for dropping the old github layout

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3595]
https://github.blog/2020-09-23-github-enterprise-server-2-22/

We have been keeping the code for the old layout to be compatible with enterprise users. I think we still need to wait at least another month before we drop the code.

A lot of the code can use some refactoring. This is due to us just adding an additional class or an additional check not to complicate the code.

This includes not just the typescript files but also the css files.

@fregante what do you say to opening a new branch for these changes?

**Comment by busches** [comment]
Let's pump the brakes a bit, this is the first release and the first release of 2.21 was quite broken. With that said, they normally support releases for a year, they just announced 2.19 is EOL in November of this year. I wouldn't and don't expect most enterprises to jump on the upgrade because they can, that's not how enterprises work.

**Comment by fregante** [comment]
Let's try again when COVID is over 😝

**Comment by yakov116** [comment]
@fregante you mean it's not over yet??!!

**Comment by fregante** [comment]
Probably in a hundred years

**Comment by fregante** [comment]
@busches feel free to reopen this when _it's time_

**Comment by busches** [comment]
2.21 will probably be EOL June 2021 😐

**Comment by fregante** [comment]
We're not GitHub, nobody pays us to support GHE, but the code can stay there until it starts smelling (3 months more is plenty)
