### ISSUE TITLE
Unread items at dashboard

### ISSUE THREAD

**Issue by evgenyrodionov** [sindresorhus/refined-github#370]
Hi, at first: thanks for the extension.
I want to propose highlight for unread items at the dashboard. Store at localStorage and mark as unread on hover at an element.

Example:
![image](https://cloud.githubusercontent.com/assets/775692/24203961/23da7d00-0f28-11e7-8435-3d00ce752777.png)

What do you think? If it'll be appreciated, I'll try to make a PR.

**Comment by hkdobrev** [comment]
I personally wouldn't use that, because I have a very big backlog of items in the dashboard and I rarely open the homepage really so the extension won't be able to cache things and would show everything as new for me. But I don't have anything against that if it works for others. Please provide feedback.

@evgenyrodionov Thanks for opening this for discussion and providing such a useful screen!

**Comment by sindresorhus** [comment]
Going to pass on this. I don't see the benefit of making the dashboard a todolist/inbox. Just adds more pressure on having to check everything. This could easily be a separate extension.

**Comment by sindresorhus** [comment]
> I rarely open the homepage really so the extension won't be able to cache things and would show everything as new for me.

It could just fetch the news feed in the background on an interval.
