### ISSUE TITLE
Allow to customise the numbers of spaces in `tab-to-indent`

### ISSUE THREAD

**Issue by MrChocolatine** [sindresorhus/refined-github#3727]
Currently the option `tab-to-indent` use 4 spaces but it would be nice if we were allowed to customise it.

Or a least, to provide a switch between 2 and 4 spaces, as these are the most common scenarios.

I don't have a full URL to provide, this feature is used whenever we have a comment field.

Thank you.

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765658
3. It doesn't require options.


Anything that requires configuration most likely does not belong to Refined GitHub. It’s just extra complexity and we already have 130+ features to attend to.

Imagine you want a feature to be "per branch", someone else wants it "per organization", etc. The options’ UI would just balloon because of different needs.

**Comment by MrChocolatine** [comment]
Damn it, I read this thread but turns out I apparently missed or misread this point.
My apologies.

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/2910

**Comment by fregante** [comment]
No worries. Here's another explaination: https://github.com/fregante/indent-textarea/issues/8#issuecomment-520009734

**Comment by fregante** [comment]
To clarify, `tab-to-indent` uses tabs, not spaces. If you'd like to display tabs as 2-character-long instead of 4, you can use https://github.com/lukechilds/github-custom-tab-size

**Comment by MrChocolatine** [comment]
Thank you for the links @fregante. Too bad it is only for changing the display of indentation, not when writing code in a suggestion block (the feature I really liked from your extension), but that's okay! It's better than nothing.
