### ISSUE TITLE
Add a reload button to pr checks

### ISSUE THREAD

**Issue by cncolder** [sindresorhus/refined-github#3762]
Sometimes the `checks` are passed but the status is stale.

<img width="994" alt="截屏2020-11-24 19 57 59" src="https://user-images.githubusercontent.com/127009/100091526-a944ee00-2e8f-11eb-890b-039181d03c4a.png">

**Comment by fregante** [comment]
In what situation would they be stale?

**Comment by cncolder** [comment]
I will double-check first if this issue relates to the circle ci and pipelines.

**Comment by fregante** [comment]
There's a button to do this that appears when to you click on any Details:

<img width="203" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/109460845-e2f53a00-7a26-11eb-8571-d2943c28cd5d.png">

This feature only works on GitHub Actions so it wouldn't make sense on the generic Checks page because it might include other CIs, which we can't refresh (each has their own mechanism)
