### ISSUE TITLE
GH Actions: Link from workflow overview to log for context (on errors and warnings)

### ISSUE THREAD

**Issue by tooomm** [sindresorhus/refined-github#3782]
In the workflow overview, you can see the list of warnings and errors in the `Annotations` section.
Unfortunately, that only links you to the code, but not the logs to see more context on the message.

**Comment by fregante** [comment]
Can you provide a link? I almost accepted this because it's so simple, but also it seems redundant:

<img width="754" alt="Screen Shot 2020-12-06 at 20 30 29" src="https://user-images.githubusercontent.com/1402241/101302774-26625280-3802-11eb-9846-c67a92e3623f.png">

The annotation can only link to the job itself, not to a sub-line, because we don't know exactly where that happen, there's no additional information.

On this page for example, linking to "Lint" is all we can do and it's not really useful since the link is already on the page: https://github.com/sindresorhus/refined-github/actions/runs/391710657
