### ISSUE TITLE
Black flashing in code review

### ISSUE THREAD

**Issue by peppy** [sindresorhus/refined-github#3792]
Version: 20.12.3
Reproduction URL: https://github.com/ppy/osu-framework/pull/4069/files
Browser: Chromium Version 89.0.4347.0 (Developer Build) (x86_64)

![2020-12-07 14 42 52](https://user-images.githubusercontent.com/191335/101313843-8c021d80-389a-11eb-8dac-9014f4d25b73.gif)

This seems to happen on pull request review pages, especially when they are on the long side (can't always reproduce, but the above URL is 100%). I can confirm that it does not occur without the refined plugin loaded.

Not sure if this is some weird chromium hardware rendering bug or something specific to the style/layout code added by refined github.

**Comment by fregante** [comment]
This is a chrome rendering bug; Unless you’re willing to look into what feature might be causing this and why, I don’t think anyone else can fix it, especially because you’re using a non-stable version of chrome.

Does disabling `show-whitespace` fix it? It’s the feature that makes the most changes on that page.

**Comment by peppy** [comment]
Unfortunately `show-whitespace` doesn't seem to help. I've been trying to narrow it down to a specific feature but haven't had huge success yet (was focusing on features with "review" in their name but i'll start to go through the rest as well).

Thanks for confirming it's something chrome-end. I'll test on a stable build when i get a chance and provide more details if it seems like anything that can be actioned on by you guys.
