### ISSUE TITLE
Auto expand Large Diffs

### ISSUE THREAD

**Issue by gcbw** [sindresorhus/refined-github#3807]
When viewing a PR file change tabs, some files will not load and instead show: "Load Diff. Large diffs are not rendered by default." (Worst case of awful user experience so they can save a few bucks on CPU. sigh)

This is very annoying and cause problems for me as I usually open a PR diff, and search with my browser for some change. If I do not know that the file is hidden, I am mislead to think that my browser not finding some text mean that text was not present in the diff.

ideally I would like to see a noticeable warning that there are hidden changes, and better yet, to automatically load them.

**Comment by fregante** [comment]
This was already requested and rejected in the past. GitHub avoids rendering large diffs by default because they’re expensive for them and also heavy for the user, when sometimes they can be avoided altogether.

You can already hold alt while clicking to show one of these diffs and ALL of them will be toggled (the feature is called `toggle-all-with-alt`

**Comment by gcbw** [comment]
What about the notice if there are hidden diffs? I will probably implement this anyway and would rather send upstream instead of maintaining a local patch.

my workflow I have to open a few PRs to look for a change (mostly because GH search is useless for phrases) and ctrl+f the phrase i'm searching for... the hidden diffs always fool me.

**Comment by gcbw** [comment]
> This was already requested and rejected in the past.

when i searched for duplicates, only found this one #2043. which is about loading all of them (which by your comment is now implemented)
