### ISSUE TITLE
An option to turn off all features that hide something from GitHub

### ISSUE THREAD

**Issue by aminya** [sindresorhus/refined-github#3843]
I like refined-GitHub and use it everywhere, but I don't like some of the features that hide something from GitHub, and this possibility that every extension update can hide something new. I prefer to use refined-GitHub for the features it "adds", not hiding UI elements. 

Could you add a switch to the extension that allows us to batch disable these features? This also removes the need for checking the list every once in a while, to disable those new hider features.

Before downvoting this issue, keep in mind that I am just asking for an option. 

The list is so long that it takes a lot of time to find all of them one by one and disable them. This has put a burden on me recommending this extension to others. 

Some of these that I have found:

![image](https://user-images.githubusercontent.com/16418197/103121287-2c996100-4641-11eb-8a9b-87d984d8c078.png)
![image](https://user-images.githubusercontent.com/16418197/103121323-4d61b680-4641-11eb-8d87-78e0d205043e.png)
![image](https://user-images.githubusercontent.com/16418197/103121357-65393a80-4641-11eb-8797-bb477fb4a53c.png)
![image](https://user-images.githubusercontent.com/16418197/103121375-76824700-4641-11eb-915f-9322a61891be.png)

**Comment by aminya** [comment]
Before downvoting or closing this issue, keep in mind that I am just asking for **an option**. It is sometimes good to accept that there may be other preferences and maybe GitHub had a reason for adding those elements.

**Comment by yakov116** [comment]
So you want an option to disable options? Nope ain't gonna happen.

> It is sometimes good to accept that there may be other preferences and maybe GitHub had a reason for adding those elements.

We already take into account other peoples preference by allowing users to easily disable features. 

You want an option to disable this set of feature, the next person wants an option to only have enabled another set of features... there is no end.

Thanks for your understanding.

**Comment by cheap-glitch** [comment]
> This also removes the need for checking the list every once in a while, to disable those new hider features.

You can subscribe to the GitHub releases to be notified every time a new feature might have appeared. They come with a pretty detailed changelog, not to mention the "NEW" labels in the feature list that make it easy to spot new features.

> The list is so long that it takes a lot of time to find all of them one by one and disable them. This has put a burden on me recommending this extension to others.

But isn't it a good thing to comb through the list at least once and check every feature? I mean, otherwise you're just blindly trusting the extension.

**Comment by aminya** [comment]
> So you want an option to disable options? Nope ain't gonna happen.

No worries! I just thought you might be open to considering other people's preferences.

 To fix this issue, I have set up a fork disabling these features by default. Once published in the Chrome store and Firefox, I would close this issue.

https://github.com/aminya/github-extras

> You can subscribe to the GitHub releases to be notified every time a new feature might have appeared. They come with a pretty detailed changelog, not to mention the "NEW" labels in the feature list that make it easy to spot new features.

Thanks for the tip.

> But isn't it a good thing to comb through the list at least once and check every feature? I mean, otherwise you're just blindly trusting the extension.

I am not someone who does not trust open-source projects. If I wanted to **not** trust this extension, I had to read all the source code of this extension, which I don't have time for. Checking the extensions page is not representative of the security/safety of this extension.

**Comment by fregante** [comment]
This is the problem with having 200 features, everyone has their own opinion on what they like and what they don’t. Grouping, disabling by default, etc have been requested in the past, but they don’t help the core problem: someone still won’t agree on the defaults or will expect different groupings.

It’s 200 features, there’s no winning, the only way forward is to fix any problems with the existing features (like https://github.com/sindresorhus/refined-github/issues/3832) and filtering new feature requests so that they effectively improve the experience for most developers (which we already do)

If you are nitpicky, you already have the option to disable the features you don’t like, but that of course requires you to go through the list. We also have an option to show which features are enabled on each page, so that should make it a little easier to find something that bothers you.

**Comment by fregante** [comment]
What I would love to see is a way to anonymously and voluntarily collect the reason why some features are being disabled. For example the options could show a message like 

> 5 features have been disabled, would you mind anonymously explaining why? [Fill in this form](#)

And the form would be pre-filled with each disabled feature.

**Comment by jerone** [comment]
I never expressed my opinion about this, but I have the same preference as the author of this issue.

Luckily, naming convention is very consistent in this extension, so once in a while I go to the settings and search for the word `hide`. This will give all the features that "hide" parts of the UI. Choose the features that you want to disable.

**Comment by aminya** [comment]
> What I would love to see is a way to anonymously and voluntarily collect the reason why some features are being disabled. For example the options could show a message like

@fregante I am not shy to express my opinions publicly, and that is why I have made this issue. Anonymous messages are good, but I am not afraid of saying what I think.

 My problem with the current default options is that you are removing/hiding things that GitHub has put effort to make based on an opinionated set of features. This is different from the new additive features that everyone loves.

I want to make Refined-GitHub more inclusive, and so that is why I am paying Google 5$ just to host GitHub-Extras. 

In my fork, I created a list of feature removers. They are disabled by default and are marked as feature-remover in the extension list. This makes GitHub extras less opinionated. 

https://github.com/aminya/github-extras/blob/e8486a54f23e4858ab4949091eb3a713592cfceb/source/options-defaults.ts#L3-L30

![image](https://user-images.githubusercontent.com/16418197/103161665-e5c77a80-47aa-11eb-9916-291e9b6fe190.png)


I also made a list of other disabled features. Those that I don't think should be enabled by default:
```ts
export const otherDisabledFeatures = [
  "set-default-repositories-type-to-sources", // discourages forking and collaboration in favor of hosting personal repositories
  "quick-repo-deletion", // very dangerous
  "edit-files-faster" // still buggy
]
```

**Comment by fregante** [comment]
> * quick-repo-deletion", very dangerous. Not everyone gets 10s of stars

You only need 1 star. Star your own repos. #3832 is coming

**Comment by fregante** [comment]
Features like `clean-sidebar` and `clean-conversation-headers` are _a plus_ because they help you focus on the important content rather than filler and duplicates.

`clean-conversation-filters` and `cleanup-repo-filelist-actions` are required because you can't keep _adding_ buttons without making room for them. I guarantee that GitHub Extras will suffer the exact bugs that those 2 features exist to prevent.

**Comment by fregante** [comment]
> * set-default-repositories-type-to-sources": discourages forking and collaboration in favor of hosting personal repositories.

This makes sense, however:

- GitHub already does that by blurring the lines between a meaningful fork and a fork created just to contribute
- the vast majority of users have the latter type of fork cluttering up their repository list

This means that regardless of our extension, finding meaningful forks in the repository list is like looking for the infamous pin in a haystack. Nobody likes that, thus Refined GitHub hides the haystack. Sorry forks, blame it on GitHub.
