### ISSUE TITLE
Indicator that you're about to comment on a Draft PR

### ISSUE THREAD

**Issue by nedrebo** [sindresorhus/refined-github#3857]
I often mix up whether a PR is a draft and final as I do not always pay attention to the subtle difference in the icons.

The latest incident motivating this feature request is the following PR comment.

---
![draft-background-color](https://user-images.githubusercontent.com/5791955/103384211-df603800-4af5-11eb-91e5-ca7ed04357c0.png)

---

For our team the PR is treated completely differently if it is a draft. Reviewing a draft as a final PR is annoying for the author and a waste of time and miss of target for the reviewer.

My proposal is to draw the entire background on draft PRs in another color, _or_ to add some other visual clue that is similarly impossible to not see.

I expect to see this change on https://github.com/sindresorhus/refined-github/pull/3841 and all sub-pages like https://github.com/sindresorhus/refined-github/pull/3841/files if https://github.com/sindresorhus/refined-github/pull/3841 is a draft.

**Comment by yakov116** [comment]
![image](https://user-images.githubusercontent.com/16872793/103385925-84fdb200-4aca-11eb-8503-61b2bedcdd71.png)

**Comment by fregante** [comment]
Draft PRs are reasonably different on the regular theme:

<img width="45%" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/103393202-2692fc80-4ae7-11eb-8374-cb4aebbf7454.png"><img width="42%" align=top alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/103393201-24c93900-4ae7-11eb-8d3a-78d6dfd0ed14.png">


But dark mode’s labels are pretty poor because the color is now limited to the text and border, with the background barely changing at all:
 
<img width="45%" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/103393288-838eb280-4ae7-11eb-814f-675a5fcca995.png"><img width="45%" align=top alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/103393286-82f61c00-4ae7-11eb-8c56-8d071f43130d.png">

I think it'd make sense to highlight that "You're commenting on a draft PR." Backgrounds might still not be super obvious though.

**Comment by nedrebo** [comment]
The thingy pointed to by the arrow in https://github.com/sindresorhus/refined-github/issues/3857#issuecomment-752785690 is the "subtle icon difference" I referred to in the original issue description. To me, this is a real issue, but I understand if this is closed as `notanissue` or `wontfix`.

My proposal is something more noticeable. If you are going through with a change I think that can be implemented in a nice and unmissable by a full-page background color change. That is not uncommon for drafts in other SW.

I also like the proposal above. Changing the `Comment` button text to be `Comment on Draft PR` will also improve the experience for me.

**Comment by fregante** [comment]
> full-page background color change

That's too in-your-face to be part of Refined GitHub, also because it doesn't really offer any explanation about _why_ it's a different color, people won't know. If they need an explanation, you might as well put it where it's needed: By the comment box

**Comment by nedrebo** [comment]
> By the comment box

Sure, that will work for me. :+1:

**Comment by yakov116** [comment]
Is this still applicable with the new draft icon?

**Comment by nedrebo** [comment]
The new icon has improved my life :D This issue is now less important to me. I would still enjoy a `Comment` -> `Comment on Draft` button change, but you decide if that is worth it.

**Comment by darkred** [comment]
> I would still enjoy a `Comment` -> `Comment on Draft` button change, but you decide if that is worth it.

I think this suggestion is very useful to have: 
this impossible-to-miss button name change next to the comment box
would put the user in the mindset of making sure they actually *want* to post a comment in a Draft PR.

&nbsp;
If this suggestion is accepted, I'd gladly make a PR for this.

**Comment by fregante** [comment]
I think that the comment form field is a little complex to handle, but you can try. if I remember correctly in the PRs there's a hidden form in the body that gets copied internally and injected multiple times, maybe you will be able to just edit that once. It's likely that you need to use `onNewComments`.

Good luck! It's not an easy one

**Comment by darkred** [comment]
Thank you for the guidance. 
I made PR #4520. 
My approach was simple, but it works ok in all tests I made.
Unless I missed things, I found it easy enough.
