### ISSUE TITLE
Original poster label is wrong on inline discussions

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#387]
I don't have a public example of this, but I'll try to describe it below:

1. Look at a PR with inline review comments.
1. There's a comment thread started from a reviewer who is not the OP.
1. There are replies to this thread from the OP.
1. When you're on the Conversation tab of the PR, the OP label is correct.
1. When you go to the Files tab, we take the starter of the thread as OP. The actual author of the PR is not marked as OP, and all of the comments from the reviewer who started the thread are marked with the OP label.

@jgierer12 @paulmolluzzo What do you think? Should we create some test comments to try to reproduce publicly? Have you noticed this as well?

**Comment by paulmolluzzo** [comment]
Not at my computer, but does this PR show the issue? https://github.com/paypal/glamorous/pull/24

If I had to guess it's the selector we're using to define OP (it's the first comment node essentially). On the types of threads I'm thinking this issue is referring to the OP isn't really clearly defined by the DOM. They might be _any_ of the comments (or not present).

Unfortunately, I think the only way to really get it is by either saving it to local storage or doing a `GET` to the conversation page and parsing that.

Of course another option is to only show OP on the conversation page.

I can look later and update this thread when I have an actual computer. 😀

**Comment by hkdobrev** [comment]
@paulmolluzzo This thread is a great example of the issue, it shows it in a few different varieties. On that I've also noticed that after the PR is merged the text at the top which is present on all tabs changes from "someone wants to merge" to "someone merged" and this case these two people are different.

My suggestion would also be to not put the badge on the Files tab in PRs.

**Comment by jgierer12** [comment]
Another possibility would be to look at the branch name (<code><b>[user]</b>:[branch]</code> in your example; won't work if the branch is deleted) or the window title (<code>[PR title] by <b>[user]</b> · Pull Request #[num] · [owner]/[repo]</code>) to figure out the OP

**Comment by hkdobrev** [comment]
@jgierer12 user:branch won't work in so many cases:
- PR is from a branch on the same repo
- someone created a PR from someone else's fork
- using a fork from an organisation

The page title could work, though!
