### ISSUE TITLE
When having more than 100 pull requests open, the fork header still displays "100 open pull requests"

### ISSUE THREAD

**Issue by Calinou** [sindresorhus/refined-github#3888]
**Browser:** Firefox 84 on Linux

On a repository fork (https://github.com/Calinou/godot), the header states I have 100 open pull requests:

![More than 100 open PRs](https://user-images.githubusercontent.com/180032/104203071-01c64f80-542c-11eb-85c0-4958f565901d.png)

However, as of writing, I have [111 open pull requests](https://github.com/godotengine/godot/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3ACalinou) on [godotengine/godot](https://github.com/godotengine/godot).

Since this is an edge case and is likely a limitation of the GitHub API, I think we can just display "100+" if the number of pull requests is equal to 100.

**Comment by yakov116** [comment]
Correct we only show the first 100, however I don't know if we can know if its more than 100.

Even if we get the total count here ⬇️ 

https://github.com/sindresorhus/refined-github/blob/382b398cbaccbb5a3f7135cf873f1302daf5901e/source/features/show-open-prs-of-forks.tsx#L23-L29

We still need to filter out ⬇️ 

https://github.com/sindresorhus/refined-github/blob/382b398cbaccbb5a3f7135cf873f1302daf5901e/source/features/show-open-prs-of-forks.tsx#L34-L35

@fregante Maybe if its 100 show 100+?

**Comment by fregante** [comment]
Let's put it this way:

- if you fetch 100 PRs and 100 are yours, you can't be sure that there aren't more
- if you fetch 100 PRs and 50 are yours, you can't be sure that there aren't more
- if you fetch 100 PRs and 0 are yours, you can't be sure that there aren't more

Whatever we do, since we only check the last 100 PRs, the number is always the _minimum amount of open PRs._

I think the best we can do, unless the API lets us query _my PRs,_ is to change the copy to "at least [3 open pull requests](#)"

**Comment by yakov116** [comment]
> unless the API lets us query _my PRs_

It cant give you only from the matching repo, so we will always have to filter it

> is to change the copy to "at least [3 open pull requests](#)"


👍
