### ISSUE TITLE
`bugs-tab`: Cannot read property 'pathname' of undefined

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3897]
https://github.com/sindresorhus/refined-github

Don't have time to debug this second

**Comment by fregante** [comment]
https://github.com/dertieran/refined-github/blob/70305e61141304b02592d6276241349eaccb3045/source/github-helpers/search-query.ts#L68

It wasn't a problem until #3837 because the feature didn't use `.get` before, but now `.get` is always called. A quick fix could be to replace `!` with `?`, but since the whole block depends on `this.link` maybe it should be slightly refactored

**Comment by yakov116** [comment]
```diff
@@ -56,8 +56,8 @@ export default 
class SearchQuery {

        get(): string {
                const currentQuery = this.searchParams.get('q');  
-               if (typeof currentQuery === 'string') {
-                       return currentQuery;
+               if (typeof currentQuery === 'string' || !this.link?.pathname) {
+                       return currentQuery ?? '';
                }

                // Query-less URLs imply some queries.
```

Not sure what that does but that code made him quiet
