### ISSUE TITLE
Text from `update-pr-from-base-branch` is duplicated

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#3927]
![image](https://user-images.githubusercontent.com/6032823/106312195-97544280-6266-11eb-8f9b-63845dcfea6f.png)
![image](https://user-images.githubusercontent.com/6032823/106312113-7855b080-6266-11eb-9ca0-adab794be8f4.png)

I can't really send links since only maintainers and PR authors can update the base branch, but it seems to happen on any PR I can update the base branch on.

**Comment by fregante** [comment]
Yeah I’ve seen this happen fairly often lately. It’s likely because the DOM changes 3 times quickly, triggering the comparison API call 3 times. Normally this value is cached once the API call completes, but not before. 

We use memoization to avoid this, the whole api.v3 method is memoized, so either this analysis is wrong or the memoization is not happening correctly.

**Comment by yakov116** [comment]
I tried debugging this morning. Looks the `isLoading` detection is not working.

**Comment by fregante** [comment]
This could be fixed with selector-observer, so addButton is only ever called once.
