### ISSUE TITLE
Some way to filter "destructive" features

### ISSUE THREAD

**Issue by asmeurer** [sindresorhus/refined-github#3964]
This idea was initially discussed at https://github.com/sindresorhus/refined-github/issues/3357#issuecomment-776349543. Some features of Refined GitHub are more "destructive" than others, in the sense that they affect more than just the user interface, but also affect actions that would be seen by other people. An example of such a feature would be the feature that disables wikis on new repos. These change my mental model of how GitHub works in a way that affects other users, so I prefer to disable them. 

"Destructive" isn't really the right word here, but I'm unsure what this would be called. 

Just having some way to filter only these options would be helpful, as it's hard to go through the whole options list.

**Comment by fregante** [comment]
It'd be great to have a list of such features, as a decision would depend on them.

**Comment by dnknn** [comment]
In fact, categories/categories/catalogs are not necessarily required.

### Can we lead into the screening concept of the Label/Tag system?

> Of course, it's just an idea, which may not be realistic or well realized.

- If there is a 🏷/🔖Label/Tag feature UI, the same can be achieved. specific:

1. Label/Tag each feature/item/option.
1.1 Obviously, most of them have very clear tags, e.g. `Global` 、`hotkey` ..
1.2 Yes, there are some who don’t know why they want to summarize the tag, so just name it `Misc` `more`.... (for example)

2. Users can filter  any combination of tags...

**Comment by cheap-glitch** [comment]
> It'd be great to have a list of such features, as a decision would depend on them.

I've combed through the list and couldn't find any other features like this. Granted, I'm far from being familiar with all of them, but based on their description, every feature falls into one of four categories:
1. Remove or reduces useless/redundant visual clutter
2. Add "shortcuts" for the user (links, keyboard shortcuts, buttons instead of dropdowns, etc.)
3. Warns the user if they're about to something stupid or lose some data
4. Automate some menial tasks (usually by auto-completing some fields)

Any "destructive" features would be in (4), but afaik `new-repo-disable-projects-and-wikis` is the only one that has any lasting effects (maybe also `sync-pr-commit-title`?)

**Comment by yakov116** [comment]
> new-repo-disable-projects-and-wikis

The funny thing is that this is the **only** feature we actually have an option! Its on by default but there is a checkbox to disable it.

**Comment by asmeurer** [comment]
The other ones that I noted when I went through the options were `pr-branch-auto-delete` and `sync-pr-commit-title`. There are a *lot* of options, though, so I may have missed some when I went through them (which is kind of why I would like to have this feature).

**Comment by fregante** [comment]
> Its on by default but there is a checkbox to disable it.

`sync-pr-commit-title` and `wait-for-ci` also have inline options that let you _opt out_ temporarily.



> `pr-branch-auto-delete`

The point we generally make is that this and `new-repo-disable-projects-and-wikis` are easily undoable and aren't particularly "destructive." If anything, `sync-pr-commit-title` is the one silently changing the title and commit message and neither one of those can be changed once the PR is merged. So in this case we can make `sync-pr-commit-title` only appear as "Cleanup title" button instead of being automatic.

**Comment by fregante** [comment]
So, so far we have:

- `pr-branch-auto-delete`
- `new-repo-disable-projects-and-wikis`
- `sync-pr-commit-title`
- `clear-pr-merge-commit-message`

**Comment by kidonng** [comment]
Can we also have a checkbox (checked by default) for `pr-branch-auto-delete`?

When I recommended Refined GitHub to two groups of my friends, they were both surprised to find that the merged branch was deleted by the extension. Some of them even disabled the extension worrying that it may have more "unexpected" behaviors.

I didn't expect this either. The intention of the feature has no issue from my perspective, but the implementation can certainly be improved, reasons:

- People will likely to **notice the feature before it actually does anything**.
	- Yes, [the deletion is easily reversible](https://github.com/sindresorhus/refined-github/issues/2267#issuecomment-514328977), but the deletion itself can cause side effects. Not a very practical example: deleting a branch may cause a Continuous Development service to unassign a preview domain which may be in use.
	- Deletion is a destructive operation inherently, and this issue is (kind of) about making them more noticeable.
- Not everyone is seasoned enough to know the existence of [protected branches](https://github.com/sindresorhus/refined-github/issues/3636#issuecomment-706272556), and they are paid features for private org repos.
- As mentioned in #3636, this feature is useful in your own repo or when it suits the workflow, but it will better if you can disable it temporarily for some projects.

**Comment by fregante** [comment]
> Can we also have a checkbox (checked by default) for `pr-branch-auto-delete`?

- https://github.com/sindresorhus/refined-github/issues/4604


> people are unfamiliar with some certain features

I empathize with that, but it's a tough one to solve as we just have to choose between:

- read all features to disable some (current)
- read all features to enable some (if we were to default to "opt-in" for every feature)

We default to "opt-out" because we _try_ to avoid controversial features in the first please.

---

I'm closing this issue since I opened actionable PRs for each problematic feature. Feel free to open _"I don't like something"_ issues for specific features to discuss possible solutions.
