### ISSUE TITLE
Triple back-ticks incorrectly rendered in commits' body

### ISSUE THREAD

**Issue by MrChocolatine** [sindresorhus/refined-github#3990]
1. The issue is cause by Refined GitHub, I tried with and without it.

2. URLs where the bug appears

_These URLs are for example and might not contain what it is needed for see the actual issue._
_But at least you see the format of URLs where the issue appears._

   - `https://github.com/sindresorhus/refined-github/commit/71975fa0c18ee7eabee9f2b640d7aaa8a731859c`
   - `https://github.com/sindresorhus/refined-github/pull/3974/commits/66ec30d7428ccf42acf0bbe4bacae49c4106fd0f`

3. Screenshots

_Screenshots for a private project_

**Without the extension**

![00 without](https://user-images.githubusercontent.com/47531779/108196247-cb59af80-7110-11eb-88a5-69c7b9c9a015.png)

**With the extension**

![01 with](https://user-images.githubusercontent.com/47531779/108196223-c39a0b00-7110-11eb-92f1-0944b27c7aef.png)

**Comment by MrChocolatine** [comment]
It is not a big deal, and not a "real bug" to me (everything works perfectly) but it might have other consequences? 🤔

**Comment by fregante** [comment]
It’s indeed a bug, even though a minor one. Thanks for reporting. 

I think an easy fix would be to change the regex to *require text between backticks* + *exclude line breaks*, so that probably means adding `[^\n]+` somewhere in it. 

Supporting the whole block (as a separate feature) would also be nice, but I think the commits body is the only place where this exists, plus it wouldn’t make any difference since the whole block is already mono-spaced. Also one would expect syntax highlighting. This is likely impossible in Refined GitHub because I don’t want to import a whole library.

**Comment by fregante** [comment]
The tests for the parser also need to be updated (I assume it has tests? Or maybe I’m wrong)
