### ISSUE TITLE
Show previews of top 10 Pull Request on long hover over the `Pull requests` tab

### ISSUE THREAD

**Issue by ericboucher** [sindresorhus/refined-github#4000]
It would be awesome if we could get shortcuts to the most recently updated PRs on a long hover over the `Pull requests` tab.

This would appear on most pages, but is most useful from the `code` project tabe and `issues` tab 
- https://github.com/sindresorhus/refined-github
- https://github.com/sindresorhus/refined-github/issues

<img width="841" alt="Screen Shot 2021-02-19 at 9 08 29 PM" src="https://user-images.githubusercontent.com/16843267/108583593-ae330580-72f7-11eb-99a3-8e2a489fa0a0.png">

For most of the projects we maintain, having a quick look at the most recently updated PRs would save a lot of time and clicks.

I did not find a similar feature request (and checked all the points listed [here](https://github.com/sindresorhus/refined-github/issues/2960)) and think it would be a great addition to `refined-github` but I would love your thoughts and feedback!

**Comment by fregante** [comment]
This is one of those features that would be nice to have and would make sense in a proper app, but due to how GitHub is set up it doesn’t make sense. 

First of all is the problem that to get that list we should load it. So when do we load it? Every time you visit a repo? Or just when you hover?

Loading it every time would be wasteful and loading it on hover means having to wait for it to load. At that point you might as well open it in a new tab. 

Now compound this to every piece of information that one might be interested in on the same page: top 10 issues? Top 10 discussions? Top 10 action runs? And so on.

**Comment by fregante** [comment]
You could consider requesting it in https://github.com/Justineo/github-hovercard
