### ISSUE TITLE
Linkify quote replies

### ISSUE THREAD

**Issue by aureooms** [sindresorhus/refined-github#4024]
When an issue discussion includes more than two people it makes sense to add a link to the quoted comment. I do not think automatically adding an @-mention makes sense since you may not want this by default and it is easily added by hand.
Full URL where the feature should appear: https://togithub.com/sindresorhus/refined-github/issues/4024

**Comment by fregante** [comment]
So do you want existing conversations to be linkified somehow or that a link should be added before leaving a comment?

**Comment by aureooms** [comment]
A link should be hard-catenated to the quote.

**Comment by aureooms** [comment]
Unless this is against some existing standard...

**Comment by fregante** [comment]
So you mean you want your own comments to include a link for everyone else to see?

**Comment by aureooms** [comment]
Yes. Maybe useless if it does not become standard GitHub behavior.

**Comment by fregante** [comment]
You might like: https://github.com/jerone/UserScripts/tree/master/Github_Reply_Comments @aureooms 

Example result: https://github.com/jerone/UserScripts/issues/1#issuecomment-459992579

**Comment by fregante** [comment]
> When an issue discussion includes more than two people it makes sense to add a link to the quoted comment. I do not think automatically adding an @-mention makes sense since you may not want this by default and it is easily added by hand.

@aureooms another example:

1. Select the text to quote
2. Press the R key to quote it
3. Click the `quick-mention` button:
4. 
![gif](https://user-images.githubusercontent.com/1402241/109458192-f3ef7c80-7a21-11eb-8f78-1fec66f9e56c.gif)

**Comment by fregante** [comment]
I'd find it useful as well, but adding this feature would mean at least one of these:

A. Hacking the native R shortcut and "Quote Reply" features to add a link
B. Recreating the whole "quote text" feature
C. Adding a button

They're likely impossible, heavy (due to a DOM-to-Markdown converter), inexact (i.e. different from the native converter), error-prone (we had the converter before, it required several fixes) and visually noisy.

I think the script above will have to do. It does what it does by using B and C.

---

Other than that, you could just right-click the comment’s time, copy its URL and paste it after quoting it.

**Comment by aureooms** [comment]
Yep. That makes sense.
