### ISSUE TITLE
Highlighting in seperated code diff selecting both colums

### ISSUE THREAD

**Issue by Nokel81** [sindresorhus/refined-github#4094]
1. https://github.com/lensapp/lens/pull/2153/files
2. 

https://user-images.githubusercontent.com/8225332/110994959-958e9c00-8347-11eb-8e62-a612c7cd2508.mov

This only happens when highlighting from bottom to top.

**Comment by fregante** [comment]
This is funny. We had this feature for months and it was working pretty well. Then GitHub added it natively (#4060) with a lot more code and now it doesn't even work well.

As such, this is not a Refined GitHub bug, but it is entertaining

**Comment by fregante** [comment]
Anyway, nothing we can do because re-adding our feature would mean fighting the native one. In my case it seems to work ok, in the end maybe you have to try twice but the right selection appears

![2gif](https://user-images.githubusercontent.com/1402241/111024470-8f7ad880-83a4-11eb-8d71-41c9338cb9d8.gif)
