### ISSUE TITLE
Open options page when clicking the toolbar button

### ISSUE THREAD

**Issue by j-f1** [sindresorhus/refined-github#4140]
When clicking the Refined GitHub button (in Safari, but the source suggests the behavior is the same for Chrome), https://github.com is opened in a new tab. I’d argue this isn’t much easier than typing <kbd>g</kbd><kbd>enter</kbd> in the URL bar, and that a better use of the buttons would be to open the options page. This would give quick and more discoverable access to this page (the options page is currently somewhat hidden in the Safari preferences) and would make the extension button useful even if it was hidden in Chrome’s menu.

**Comment by fregante** [comment]
That's how it was before, but I changed to be a GitHub.com button to be more useful. I don’t think entering the options is something that people do regularly enough to keep the button visible, especially in Safari since it doesn't have any "overflow menu" for such buttons and thus it has to stay always, on every window, forever.
