### ISSUE TITLE
How are the preview screenshots done?

### ISSUE THREAD

**Issue by SirWindfield** [sindresorhus/refined-github#4163]
I just noticed that clicking the screenshot button from the extension's settings page opens github with a screenshot next to the latest commit that changed that file:

![image](https://user-images.githubusercontent.com/5113257/112756906-8cf4c180-8fe7-11eb-86ea-3ba235ab1c56.png)

Can this be used by users somehow? For example, could I also provide those previews for people that have refined github installed?

**Comment by fregante** [comment]
This is one of our new meta-features: `rgh-feature-descriptions` if I remember correctly. Our meta features are only enabled on our own repo and the data is actually bundled into the extension itself, with the screenshots stored as URL. 

This type of feature could never be applied to 3rd parties because it would require querying every single repo when it would probably only be used by a handful of them.

**Comment by SirWindfield** [comment]
Thanks!
