### ISSUE TITLE
Directly show TOC dropdown of READM.md when hovers on the button of TOC

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#4280]
Directly show TOC dropdown of READM.md when hovers on the button of TOC

**Comment by fregante** [comment]
I think we’re not going to open things on hover in Refined GitHub because people will head there and click the button, therefore closing it. Or head there and wait for it to auto-open but the feature broke in the meanwhile. Or simply overshoot with their mouse and suddenly there’s an unwanted popup that needs to be closed. It’s a rather subjective thing IMHO

**Comment by Geeyun-JY3** [comment]
Fine.
