### ISSUE TITLE
Settings icon in repository sidebar has misaligned outline

### ISSUE THREAD

**Issue by Krausso** [sindresorhus/refined-github#4434]
It's not appearing in case of installed refined github. I haven't installed it yet, but I think you should fix it.
Steps to reproduce:
1. Open your repository
2. Press on settings icon on the right side of the screen to manage your repo "About" section.
3. Press Escape.
*Magic*
![image](https://user-images.githubusercontent.com/52201020/120152890-b9e76f80-c1f6-11eb-931f-cd6ddce22f47.png)
Settings icon has wrong outline.

System: macOS 11.2.2
Browser: Chrome 90.0

**Comment by Krausso** [comment]
Installed refined github extension. Problem is still reproducible.

**Comment by fregante** [comment]
This is a feature request, not a bug report.

Anyway, a fix might be easy via 2 CSS rules. GitHub’s DOM doesn't have any classes specific to that icon, so the selector might be a little brittle (also because it needs to be very specific, or else we might silently break other parts of the site)

PR welcome to remove the padding from the icon and move it to `summary`, even if that means hardcoding some CSS lengths.

**Comment by fregante** [comment]
I'd suggest reporting it to GitHub and hope for the best, or fix it locally. This kind of micro CSS fixes tend to get obsolete quickly and this doesn't seem worth the time and future bug reports that it will cause.
