### ISSUE TITLE
In `avoid-accidental-submissions`, focus primary button instead of next field

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4462]
I think `avoid-accidental-submissions` feels a little strange, like slipping on a banana peel. What if we focus the submit button instead of the text area?

<img width="435" alt="Screen Shot 9" src="https://user-images.githubusercontent.com/1402241/121675395-8b627200-cadd-11eb-8bd2-a35b97204076.png">

Pros:

- submission is possible with an additional plain [Enter] press, without using ctrl/cmd
- maybe it feels less broken

Cons:

- if it _was_ accidental, going back now means pressing shift-tab several times instead of once

---

An alternative would be to add a temporary "confirm" button right below it and focus it.

<img width="724" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/121675762-0a57aa80-cade-11eb-8c24-b428807d8f44.png">

The message would still be welcome everywhere.

**Comment by darkred** [comment]
If you recall, in my first ever [comment](https://github.com/sindresorhus/refined-github/issues/3911#issue-792867900) about having a feature like this, I had written that:

> GitHub allows in the Issues and Discussions section of repos:
> 
> * to submit a new issue/discussion with just 1 character as title and no body, and
> * to submit a comment with just 1 character .

I justn oticed that in Discussions this is no longer the case:
if you try to submit an empty discussion, all empty elements (dropdown/input/textarea) get a red border and text balloons that "category/title/body can't be blank" :
![2021-07-08_161340](https://user-images.githubusercontent.com/723651/124927616-81ae2a80-e007-11eb-9231-40003e5a92b2.jpg)


&nbsp;
So, I thought of the following alternative approach: 
maybe we could duplicate the style (colored border + balloon text, maybe blue instead of red)
and display your suggested message in that text: 
`A submission via Enter has been prevented. You press enter again or use ctrl-enter next time`
maintaining the focus to the title input element the first time you press Enter,
thus avoid creating a temporary `Confirm?` button below the title, as in your mockup?

**Comment by fregante** [comment]
Yeah maybe a little notice is enough, no focus change. Chrome has a simple solution to avoid accidental closures of the app via CMD+Q: It just shows a temporary overlay for a couple of second, during which you can just press the buttons again to close the app.

![gif](https://user-images.githubusercontent.com/1402241/125042016-98b25280-e0c3-11eb-9a1f-331c54105ede.gif)


In this case:

1. Prevent enter
2. Show message somewhere
3. Allow a second enter on the field, either at any time later or just within the next few seconds

Adding a plain `<p>` as pictured before might be the easiest solution that doesn't require us to deal with error-looking styles on fields that might not support them.

This is easily implemented as:

```diff

function onKeyDown(event: delegate.Event<KeyboardEvent, HTMLInputElement>): void {
	if (
		event.key !== 'Enter'
		|| event.ctrlKey
		|| event.metaKey
		|| event.isComposing // #4323
		|| select.exists('.suggester', event.delegateTarget.form!) // GitHub’s autocomplete dropdown
+		|| previouslyPressedEnter.has(event.delegateTarget)
	) {
		return;
	}
+	previouslyPressedEnter.add(event.delegateTarget);
+	event.delegateTarget.form.prepend(
+		<p className="github’s notice classname I don't remember which">My message here</p>
+)
```

**Comment by fregante** [comment]
Actually we can skip the WeakSet and just add a class to the existing `select.exists` check

**Comment by darkred** [comment]
I just made PR #4556 to facilitate this.
All credits go to you of course.
