### ISSUE TITLE
Click handler for search in navigation header

### ISSUE THREAD

**Issue by Stanzilla** [sindresorhus/refined-github#4479]
It looks like at some point GitHub added a click area in the blank part of the header, right in the middle, that triggers the search opening. 

It is pretty annoying to me but I wanted to open a discussion first to see if anyone else is bothered by it before doing more.

**Comment by yakov116** [comment]
GIF or Video of what you are referring to?

**Comment by Stanzilla** [comment]
There you go 

https://user-images.githubusercontent.com/75278/122133772-a3b7f100-ce3d-11eb-9e90-3c63558fcaff.mp4

**Comment by yakov116** [comment]
This does not happen to me in chrome on windows

**Comment by fregante** [comment]
Same on Safari, nothing happens when clicking outside

**Comment by Stanzilla** [comment]
That is weird, I can repro without any browser extensions even on Chrome 92.0.4515.51. I will test with more browsers.

**Comment by darkred** [comment]
I managed to repro consistently in a fresh Chrome 91 profile (having login to github)
by rightclicking on the middle of the blank area of the header, then immediately leftclicking 
*(the mouse has to be in a specific vertical height, otherwise it doesn't occur)* 
and finally pressing Esc, and repeat: 

![](https://user-images.githubusercontent.com/723651/122278164-4d0aef80-ceef-11eb-858d-d4b4efce0d10.gif)

**Comment by fregante** [comment]
Please report this to GitHub
