### ISSUE TITLE
Hide dependabot PR link-back noise

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4480]
In PRs, we can hide any mentions from PRs include `Update dependency * to`. I think they should be completely hidden without `Unhide` button. Maybe as a new `init` in `dim-bots`?

https://github.com/xojs/eslint-config-xo/pull/60#ref-commit-a613304

<img width="879" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/122141286-3759e380-ce77-11eb-864e-d6fb2e08306c.png">

**Comment by kidonng** [comment]
Actually, that's [Renovate](https://github.com/renovatebot/renovate) not Dependabot. Dependabot's references uses `https://github-redirect.dependabot.com/` instead of linking directly, so it won't flood the original discussion.

I think we should report this to Renovate, rather than just hiding them.

**Comment by fregante** [comment]
Yeah this looks like a "bug" in their replacer. Closing for now. If I see it again I'll report it. Until then, anyone else can do the same.
