### ISSUE TITLE
Convert our issue templates to issue forms

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4508]
We should convert the templates we're using in this repo into forms as described in https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/

Related feature request: https://github.com/sindresorhus/refined-github/issues/3365

**Comment by patil2097** [comment]
I would love to help in closing this issue.

**Comment by fregante** [comment]
You can! ☺️

**Comment by darkred** [comment]
Is it ok if I provide a PR for this ?
It would be a variation of the [issue template](https://github.com/darkred/Userscripts/issues/new?assignees=&labels=bug%2Ctriage&template=bug_report.yml) I have made for my Userscripts repo.

**Comment by darkred** [comment]
I made PR #4539 .

**Comment by fregante** [comment]
There are more templates, not fix yet 😃

**Comment by darkred** [comment]
I'll submit a PR shortly. 👍 

_(to be frank, I actually thought to make forms for the rest 3 templates, but I hesitated because they all are very short, and so it might not be worth it)._

Here are the 3 current templates:
<details>
<summary>Feature Request</summary>

```
---
name: 🆕 Suggest an improvement or new feature
about: ———
labels: enhancement, under discussion
---

<!--

1. Make sure your requested feature makes sense for Refined GitHub:
   https://github.com/sindresorhus/refined-github/issues/2960

2. Include a REAL URL where the feature should appear.
   e.g. Do you want a feature to appear on the main page of a repo? Paste a link to a repo

-->
```

</details>

<details>
<summary>Discussion</summary>

```
---
name: 💬 Ask a question or open a discussion
about: ———
labels: under discussion
---
```

</details>

<details>
<summary>Complain</summary>

```
---
name: 🤌 Complain
about: Is there something you don't like? Let's talk
labels: change request
---

<!-- If you find any related threads, link them here -->
<!-- Duplicate issues are ok, but they may be closed pretty quickly -->
```
</details>

&nbsp;
Regarding the 'Discussion' template (the shortest of all): 
I'd say to enable Discussions for the repo, and make the template chooser (when clicking Discussions) to just link to `https://github.com/sindresorhus/refined-github/discussions`.

The only limitation that currently exists in Discussions, is this:
- you can convert issues into discussions, but
- you CAN'T convert discussions into issues. 

But the latter is soon to be available for everyone, it'is currently available as a private beta: https://github.com/github/feedback/discussions/2861#discussioncomment-696235).
That's why I believe it's worth enabling Discussions for the repo now, at this point.

**Comment by darkred** [comment]
I made PR #4586

**Comment by yakov116** [comment]
@darkred FYI we get notifications when you make a PR
