### ISSUE TITLE
Notifications: shove dependabot to a different tab

### ISSUE THREAD

**Issue by jtagcat** [sindresorhus/refined-github#4523]
Not sure, if related: #3090 (dashboard, not notifications).

I watch some repos for PRs. I'm not a maintainer of the repo. I can't merge them or similar.

My notifications tend to be filled with noise-spam from dependabot. It's so bad, that when opening notifications of a day or two, I ctrl-f for dependabot, and unsubscribe from all of them. I don't even look if it's my repo or not (most cases).

I've complained to gh, they seem not to care.

***

 - At the very least, could dependabot's notifications be shoved in to a separate tab in the inbox?
 - Alternatively: Ignore dependabot from this repo (should be in the watch dropdown, and then carried over to notifications (repo name, automatically unsubscribe or mark as done).
 - ~~Additionally: Make an API request while in notifications (and store the result) to detect, whether it's a repo the user has write access to.~~

**Comment by kidonng** [comment]
There are more noisy bots other than Dependabot. Targeting just one doesn't help much (for other people).
Perhaps `dim-bots` can be extended to notifications as well, though the code will be very different.

**Comment by fregante** [comment]
I think this feature is two-part:

- dim the notifications in the notifications page
- hide/color the notification bubble if there are no other notifications 

The first part is doable, but I think it wouldn't be particularly better because you're still getting notified.

The second part requires continuous fetching of the notifications, which another extension already can do. It only needs this issue to be fixed: https://github.com/tanmayrajani/notifications-preview-github/issues/82

**Comment by fregante** [comment]
Yeah this is covered in its entirety by that other extension, once that issue is resolved:

- https://github.com/tanmayrajani/notifications-preview-github/issues/82
