### ISSUE TITLE
Send ZIP Button

### ISSUE THREAD

**Issue by jamiebuilds** [sindresorhus/refined-github#4549]
GitHub's "Download ZIP" repo feature is a great way of sharing code without sharing history or granting any access to the repo.

But ZIP files can sometimes be difficult to share on larger repos... emails often bounce, uploading them to dropbox/etc gets you back into permissions issues and is more work.

So I was wondering if it'd make sense to build this into Refined GitHub as a button:

![Screen Shot 2021-07-08 at 2 07 19 PM](https://user-images.githubusercontent.com/952783/124991013-f7a99600-dff5-11eb-8f96-aeb260d27aaf.png)

There are a number of different encrypted file sharing services like https://wormhole.app/ I asked if they were considering adding an API, and they said they probably will.

**Comment by fregante** [comment]
This would only be for private repos since public ones already have a shareable URL like https://github.com/sindresorhus/refined-github/archive/refs/heads/main.zip

To implement something like this we’d have to download the URL in the browser itself (to use its cookies) and then pass the blob to something like Wormhole. I see several problems with this:

- it requires an extra permission on the extension for a Wormhole API
- we’d have to implement a transload progress UI on the page itself for larger repos
- it sounds like a pretty niche situation
- it also sounds like it’s something that would sense on any website

For these reasons I think it’d be best to implement this as its own extension, ideally even as a context menu that works on any link.
