### ISSUE TITLE
Make changes to the merge button temporary

### ISSUE THREAD

**Issue by alimpfard** [sindresorhus/refined-github#4551]
In my own experience, changing that button to "Squash and merge" (or any other option) is only ever a temporary measure, but github switches to it permanently until you change it back.
This has caused a few squashes by mistake so far.
I think it'd be a sane default to make changes to that button temporary.

**Comment by fregante** [comment]
I don’t think we can change how that button works without confusing everyone in the process. And to be honest I think the current situation makes the most sense because people are more likely to stick to one type of merge for each repo. What you suggest would only work if there was a way to define a “default merge” for the repo in order to always use that… but also allow the occasional unusual merge. Unfortunately that doesn’t exist.
