### ISSUE TITLE
Compatibility with Firefox v78/ESR

### ISSUE THREAD

**Issue by Jorge9811** [sindresorhus/refined-github#4561]
Title.
Is there a reason why this couldn't or shouldn't work in Firefox v78?
![untitled](https://user-images.githubusercontent.com/54429803/125365039-f0fa8600-e349-11eb-9ac4-40c8379c5070.png)

**Comment by busches** [comment]
It was bumped here https://github.com/sindresorhus/refined-github/pull/4361 for a selector change. May want to consider rolling it back for ESR support, otherwise, using an older version will still work.

**Comment by fregante** [comment]
Supporting older releases would likely mean having to set up postcss and Babel to ensure that they are not continuously broken since none of us uses them.

However they probably still wouldn’t work because often older version contain webextension-related bugs that we just don’t expect while writing anymore. 

My suggestion, however not easy, would be to keep a fork that includes these adjustments and then deal with the breakage that might happen over time.

**Comment by fregante** [comment]
For reference, here's the Firefox release schedule: https://wiki.mozilla.org/Release_Management/Calendar

I just realized that postcss/babel can't fix the changes brought in #4361. Supporting ESR would mean we have to keep its compatibility in mind instead of just testing on the last version of browsers.

In practice this probably isn't a big deal but these changes would need to be done by ESR users themselves as we're not going to explicitly test/support ESR.

I'm to close this for this reason, but PRs welcome.
