### ISSUE TITLE
Allow users to add notes to notifications

### ISSUE THREAD

**Issue by thomaseizinger** [sindresorhus/refined-github#4576]
I treat my GitHub notifications as a list of things I need to do (Inbox Zero style model). When I go through my notifications, some of the work I want to do as part of it takes too much time so I don't want to deal with it right now and rather postpone it until later. Hence, I'll let the notification sit there as _read_ but don't mark it as done.

Currently, I need to remember _what_ I want to do with this notification that requires more time so I can't do it right away.

It would help my workflow if I could add a little note to each notification where I can write down ideas so that I don't have to keep them in my head.

The note would have to be stored in local storage I presume.

I read through the "Can we add this feature?" list and this request is probably borderline in terms of UI complexity.

Prior art to this is the "Hey" email client from Basecamp where you can add notes to email threads.

This feature request concerns the "notifications" page: https://github.com/notifications

**Comment by fregante** [comment]
That would be great and I also follow inbox zero, but this sounds like a whole extension that can live on its own and isn't just a _refinement_ because it's relatively large and requires its own UI. For example we _could_ add a field on the notification and issues to add notes… but then what happens in a month? How will you find this note? Should we also allow you to filter it? We'll also need to build a UI to show and delete these notes.

**Comment by thomaseizinger** [comment]
That makes sense, I thought that it might be a bit much for refined GitHub!

Closing this then :)
