### ISSUE TITLE
Trending nav item is repeating in header

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#479]
![image](https://user-images.githubusercontent.com/506129/26841039-fd17f8aa-4af0-11e7-8997-327dfc3d3c58.png)

Steps to reproduce:
1. Go to https://github.com/sindresorhus/refined-github It's added twice
1. Click on a sub-repo navigation item - e.g. Issues tab.

This has been introduced relatively recently on `master`.

**Comment by bfred-it** [comment]
I cannot reproduce on `master`

**Comment by hkdobrev** [comment]
It is indeed quite strange. The function is actually called twice and it's fixed when I remove both async and await. Would reinstall and report back.

**Comment by bfred-it** [comment]
It's it's called twice then the script is being injected twice, probably. Stick a console.log at the bottom of content.js

**Comment by bfred-it** [comment]
Do you have multiple extensions loaded? 😃

**Comment by busches** [comment]
I was able to have this occur today too.
![image](https://user-images.githubusercontent.com/857700/27190093-fd54e75a-51b8-11e7-96a0-fecba7c3b6db.png)
Running latest master, confirmed I do not have two extensions loaded. Additionally the Trending item is being added with the back button as well.

**Comment by bfred-it** [comment]
ahhhh I think the [dynamic script injector](https://github.com/bfred-it/webext-dynamic-content-scripts)'s [ping receiver](https://github.com/bfred-it/webext-dynamic-content-scripts/blob/f5c92f38b20eb98959bd2d3719eacce0266edf37/dist/webext-dynamic-content-scripts.js#L33-L38) got lost. Try this PR:

**Comment by bfred-it** [comment]
New issue report here: https://github.com/sindresorhus/refined-github/pull/492#issuecomment-310583630

**Comment by bfred-it** [comment]
I saw this issue once I re-enabled the AMO version, but then I reloaded the page and it stopped appearing (for now)

It might happen once.

**Comment by SimenB** [comment]
What's AMO? 😅

**Comment by bfred-it** [comment]
Mozilla Addons site 😃

**Comment by OmgImAlexis** [comment]
It's getting worse. Yesterday I had 20 of them. 😨 

![screen shot 2017-06-25 at 12 39 37 pm](https://user-images.githubusercontent.com/6525926/27513393-6effa718-59a3-11e7-8d34-37e4de3186b5.png)

**Comment by bfred-it** [comment]
I'm having a hard time figuring this out. Surprisingly, `chrome.permissions` doesn't include github.com (because in manifest.json it's only specified in `content_scripts` but not `permissions`), so the injector should be stopped [pretty early](https://github.com/bfred-it/webext-dynamic-content-scripts/blob/ed45ec9/src/index.js#L31-L38) and it should not run at all.

Can you [inspect the background page](https://stackoverflow.com/questions/10257301/where-to-read-console-messages-from-background-js-in-a-chrome-extension/10258029#10258029) and run this code in its console?

```js
chrome.permissions.getAll(console.log);
chrome.tabs.onUpdated.addListener((tabId, ignore, {url}) => console.log(url));
```

Then open github.com and look back in the background page's console. It should look like this:

<img width="545" alt="screen shot 2017-06-25 at 12 04 48" src="https://user-images.githubusercontent.com/1402241/27513597-838a6006-599e-11e7-9c3d-0b0c88d48170.png">

`origins: Array(0)` and then a lot of `undefined`

**Comment by bfred-it** [comment]
Are the Trending links consistently there? All the time every time?

If so, try this:

1. visit a repo
2. paste this in the console:
    ```js
    chrome.runtime.onMessage.addListener(request => console.log(request, chrome.runtime.id));
    ```
3. visit the Issues tab

Nothing should appear in the console, the page should be loaded via ajax (i.e. the console should still contain what you pasted)

**Comment by OmgImAlexis** [comment]
![screen shot 2017-06-25 at 11 49 00 pm](https://user-images.githubusercontent.com/6525926/27516861-ea18d606-5a00-11e7-8c6c-9d00f903a6ad.png)

The trending links seem to start off on 1 or 2 and then add another on the first time I load another section within the repo like the issues/PRs/Releases, etc. e.g. issues only gives 1 more but going to 3 repos and clicking issues each time adds 3.

![screen shot 2017-06-25 at 11 52 07 pm](https://user-images.githubusercontent.com/6525926/27516880-5de8b588-5a01-11e7-9fe3-73c91b051888.png)

**Comment by bfred-it** [comment]
I'll some logging at every step and push to Chrome so we can get more details.

**Comment by busches** [comment]
An easy way to work around this is to add the same code we have for most other items we add to the dom and check for it's existence before adding it. Doesn't solve the root cause of why the extension is running twice, but if it's an odd edge case, it may be worth the time savings of solving it the quick and easy way, especially since we use that pattern for everything else.

**Comment by bfred-it** [comment]
I'd rather not do that because it'd push the real problem under the rug, deprioritizing the issue. You don't want an extension to run 10 times.

**Comment by paulmolluzzo** [comment]
> I'd rather not do that because it'd push the real problem under the rug, deprioritizing the issue. You don't want an extension to run 10 times.

While that's fair, I think it's worth fixing the issue as best as we can immediately and then addressing the larger issue without this clear bug in the way.

I think @busches suggestion of checking for the existence of the element before adding it is a fine fix for now (we're doing it elsewhere already). Later when we have time to circle back on the underlying issue we can also remove the unnecessary DOM checks for this element and others when we have a better fix.

**Comment by SimenB** [comment]
+1 for quick fix, it's really annoying...  Even though I get an itch by treating symptoms and not the underlying issues

**Comment by busches** [comment]
@bfred-it I'm not suggesting we ignore the issue all together, only that we put in the workaround as it's super annoying, as @paulmolluzzo and @SimenB mentioned.
