### ISSUE TITLE
Add Git hooks

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#512]
I often forget to run `npm run build` after checking out a PR branch. Would be useful to set up some shared Git hooks for running `npm install` and `npm run build` on Git changes, like updated master or other checked out branches.

Maybe using https://github.com/typicode/husky

**Comment by yakov116** [comment]
🚨   must specify --input and --output when using rollup --watch

```npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! refined-github@ watch: `run-p --continue-on-error --silent "build -- --watch"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the refined-github@ watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Front Desk\AppData\Roaming\npm-cache\_logs\2017-06-19T16_05_14_319Z-debug.log```

What does this mean?

**Comment by hkdobrev** [comment]
@yakov116 Please run `npm install` again. It should be fixed with the latest updates.

**Comment by yakov116** [comment]
@hkdobrev tried it gave the same error

**Comment by bfred-it** [comment]
@yakov116 the support for multiple files has been added in rollup 0.42. Make sure that npm (5?) isn't failing to install that 🙄

**Comment by yakov116** [comment]
@bfred-it thanks how would I check that?

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by bfred-it** [comment]
```
rm -rf node_modules && npm install
```

Perhaps also just downgrade to npm 4 (`npm install npm@4 --global`) or use `yarn`

**Comment by yakov116** [comment]
@bfred-it thanks will try that and report back

_Sent from my HTC Nexus 9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by yakov116** [comment]
@bfred-it that worked thanks

**Comment by bfred-it** [comment]
@sindresorhus that'd be helpful, but for me it wouldn't fully resolve my issues:

- I forget to start up `watch` while working on the extension
- I forget to reload the extension after making any changes

I'm not entirely sure of how to fix these, but mind goes to

- self-destructing content.js etc — after`watch`, so that you'll always need `watch` open to load the extension
- auto-reloading the extension so that you're not using a cached version **and** that it'll fail completely when `watch` isn't running. 

This would of course only be included during `watch`, which would then become the preferred way to build locally, not `builf`

Solutions could be

- adding `process on exit => trash extension/*.js` to the watch script
- appending livereload+`chrome.runtime.reload()` to the bundles built during `watch`

Also build/syntax errors are ugly if your terminal is not visible and your file just isn't being updated while you think it is.

I wouldn't mind switching to `webpack` if its ecosystem helps with this more advanced solutions. I had already considered the switch after seeing the reduced build times (especially on watch: 30ms vs 700ms), but I haven't because of its size (30mb on disk vs 5mb, if I remember correctly)

**Comment by sindresorhus** [comment]
> but I haven't because of its size (30mb on disk vs 5mb, if I remember correctly)

Size on disk doesn't matter though. We care about bundle size and execution speed. If Webpack can improve that, I wouldn't mind switching. The ["scope hoisting" in Webpack 3](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b) looks pretty good.

**Comment by bfred-it** [comment]
Good to hear. I was afraid you'd dislike webpack because of its sprawl (compared to your minimal modules)

Unfortunately, bundle size is also higher and I couldn't get the scope hosting to work, honestly. :((( In theory it should bring webpack's bundle near rollup's efficiency in speed and size.

**Comment by bfred-it** [comment]
Little idea: a build age indicator that's only added on `npm run watch`.

When I check out multiple branches I always have the watch running, it automatically builds the new versions as I go and I only have to reload that in Chrome.

We could add a tiny indicator in the `watch` build only, that your eye will be trained to see when expecting fresh changes.

The indicator would indicate a 10 minutes countdown, it could be anything. Example:

* a 1px line that "unloads" from right to left as the time passes. It could be at the top of the screen or at the bottom, fixed to the dev tools
    
  <img width="388" alt="screen shot 2017-07-07 at 01 08 01" src="https://user-images.githubusercontent.com/1402241/27923406-dc33473e-62b0-11e7-9fe8-f167d0365c56.png">

**Comment by sindresorhus** [comment]
@bfred-it Wouldn't it be easier to just embed the relative build time explicitly then? Maybe on the left side of the navbar. Like: `Built 10 min ago`. It's only for watch mode anyways, so doesn't matter if it's noisy or looks ugly.

**Comment by bfred-it** [comment]
Both are pretty easy to implement. Text like that is fine too, but it actually needs screen estate and it needs to be _read_ (analog clock vs digital clock). I wouldn't mind a combination of the two.

**Comment by leggsimon** [comment]
FWIW, I have like 5 commits in https://github.com/sindresorhus/refined-github/pull/898 that are just linting, I think a pre-push hook that runs `npm test` is worthwhile because then at least you could amend your actual commits with the linting changes before making a PR more untidy.

**Comment by bfred-it** [comment]
Those can be usually avoided by having a live linter in your editor, like SublimeLinter-contrib-xo

**Comment by leggsimon** [comment]
@bfred-it True but IMO I don't think it's reasonable to ask any contributors to add extensions to their editor of choice. I don't use xo for anything else so I haven't got an extension for it
