### ISSUE TITLE
Phantom semicolon added to closing XML element

### ISSUE THREAD

**Issue by blairconrad** [sindresorhus/refined-github#513]
Seen in the wild at https://github.com/thomaslevesque/FakeItEasy/blob/19f6cbcd444c443949eb3a9f43ce52d4eebb65e4/src/FakeItEasy/FakeItEasy.csproj#L18 when using Refined GitHub 1.19.0, it looks like

```xml
<PackageProjectUrl>https://fakeiteasy.github.io/<;/PackageProjectUrl>
```

Here's an image, just in case:

![image](https://user-images.githubusercontent.com/3275797/27379782-a5b055c0-564a-11e7-9102-33036a9fdcff.png)

Note that the semicolon is not really there, as can be seen in the raw view.

**Comment by bfred-it** [comment]
Happens because:

- https://github.com/sindresorhus/refined-github/blob/c7a12c3af073b423321ff5fd97e423311c8b4b65/src/libs/linkify-urls-in-code.js#L37 transforms the node to:
    `&gt;https://fakeiteasy.github.io/&lt;/`
- and because https://github.com/sindresorhus/linkify-urls/blob/72d8831/index.js#L5 will match that  extra `&lt` as part of the URL
