### ISSUE TITLE
Add repository size 

### ISSUE THREAD

**Issue by vinkla** [sindresorhus/refined-github#53]
Wouldn't it be nice to see how large a repository is just by visiting the repos main page?

<img width="1038" alt="screen shot 2016-03-04 at 9 24 12 am" src="https://cloud.githubusercontent.com/assets/499192/13521704/e5bc25ac-e1ea-11e5-957d-972316f1db6c.png">

Is it even possible?

**Comment by sindresorhus** [comment]
Why? For what purpose?

**Comment by vinkla** [comment]
Right now there is no way to know how big a repository is (I guess?). Before I clone a big repository it would be good to know about it before.

**Comment by xavhan** [comment]
I think it is a great idea, but in my opinion it would be more relevant to display the size of the main minified file, because it is most of the time this file that will be used in production. 

Having at first glance an indication of production size make sense, especially for frontend libraries.

**Comment by sindresorhus** [comment]
@xavhan I think you're misunderstanding what's being requested here and why.

**Comment by xavhan** [comment]
@sindresorhus : Honestly, today who really cares of a repo size, memory is not really a problem anymore I suppose. No?

**Comment by sindresorhus** [comment]
Yeah, I don't really see the point. Most repos are small.

**Comment by sindresorhus** [comment]
> but in my opinion it would be more relevant to display the size of the main minified file, because it is most of the time this file that will be used in production.

Out of scope of this plugin. It would have to guess which file are the main and so many uncertainties.

**Comment by vinkla** [comment]
Okay, to bad. Better luck next time.

**Comment by hkdobrev** [comment]
@vinkla you can write an extension which injects in the readme or somewhere else on the page this badge: https://github.com/ngryman/badge-size

**Comment by vinkla** [comment]
@hkdobrev okay, cool. Thanks for sharing!

**Comment by eMPee584** [comment]
> Yeah, I don't really see the point. Most repos are small.

Well some are gigabyte sized.
This was the only reason I searched for github addons in the firefox store and this was the one with recent commit activity. The other features are nice and interesting, but missing repo size is one major pain point in the github experience, esp. if you're running low on disk space. That's why there are several distinct addons for this.. so it still would be great to include as a feature..

<img width="1109" height="849" alt="Image" src="https://github.com/user-attachments/assets/c105fafb-652b-496a-84bf-979f47853868" />
