### ISSUE TITLE
[BUG] Big icons in feed?

### ISSUE THREAD

**Issue by vinkla** [sindresorhus/refined-github#56]
Some of the icons in the feed on the startpage has become huge. Is this intentional or is this a bug? 
<img width="291" alt="screen shot 2016-03-07 at 10 02 35" src="https://cloud.githubusercontent.com/assets/499192/13564693/dbca543e-e44b-11e5-8d3f-722c569ad127.png">

**Comment by hkdobrev** [comment]
@vinkla It was intentional to increase visibility of stars. They are equal to pull requests, issues, comments etc. See https://github.com/sindresorhus/refined-github/pull/55.

**Comment by vinkla** [comment]
Aah, okay. I'll close this then.

**Comment by kumarharsh** [comment]
I've used this plugin for more than a month now, and although most of the UI changes have dissolved into the background, the huge starts on the dashboard still feel very jarring. I think it's because the stars' visual area is larger than the other icons? Can it be reduced just a smidge to `28px` from `32px`?

**Comment by sindresorhus** [comment]
Maybe it would make sense to make the star icon border only too?
