### ISSUE TITLE
Edit readme link is visible on top of delete button on certain pages

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#64]
![screen shot 2016-03-08 at 02 41 39](https://cloud.githubusercontent.com/assets/506129/13588303/5b280d9e-e4d7-11e5-9169-99551f3dd586.png)

The added edit button which was meant for the readme on the front page of a repository is on top of the delete file button when looking at certain files.

E.g.
- See https://github.com/sindresorhus/refined-github/blob/master/readme.md
- https://github.com/sindresorhus/pageres/blob/master/contributing.md

It is not visible when looking at a specific commit reference like https://github.com/sindresorhus/pageres/blob/511d29f6c5a9b5438bd85cefe15ec6fa8074e227/contributing.md

**Comment by paulmolluzzo** [comment]
I'm about to make a PR, but I want to call out something this issue highlights:

> It is not visible when looking at a specific commit reference like https://github.com/sindresorhus/pageres/blob/511d29f6c5a9b5438bd85cefe15ec6fa8074e227/contributing.md

This is expected (you're not in the root) and is different from the other pages because you are affecting a full page refresh.

We're seeing the same issue other PRs, and it's because `'DOMContentLoaded'` is not firing for many navigation-type events on GitHub. These bad edit README links disappear on their own on a page refresh, and the recurring "have to refresh to make XXX work" is the same underlying issue.

PR is coming with a CSS fix, but if there's a JS fix (bind to the `load` event?) then we can do that instead.

**Comment by hkdobrev** [comment]
@paulmolluzzo thanks for fixing this! I also meant it's not desired the link to be there. I didn't dig deeper in the regex or the CSS, but , but just wanted to show it's not reproducible in every case.

**Comment by paulmolluzzo** [comment]
@hkdovrev you bet! The point I was making was why two similar scenarios behaved differently. That's all.
