### ISSUE TITLE
Firefox port

### ISSUE THREAD

**Issue by bogas04** [sindresorhus/refined-github#71]
Though the future of extension system of Firefox isn't clear, but I guess with advent of [WebExtensions](https://wiki.mozilla.org/WebExtensions) it would be fairly easy to port the extension for Nightlies. 

---

See #403 for progress on this.

**Comment by hkdobrev** [comment]
BTW see #14.

**Comment by bogas04** [comment]
Makes sense! 
I'll try to fork over weekend.

**Comment by sindresorhus** [comment]
Happy to link to a port, but I don't have time or interest in maintaining and publishing new versions of a Firefox plugin ;)

**Comment by silverwind** [comment]
Couldn't this be easily converted to a userscript?

**Comment by sindresorhus** [comment]
@silverwind Yes, that would be the easiest solution for Firefox support.

Not sure how far Web Extensions support is in Firefox, but that would be the best solution: https://blog.mozilla.org/addons/2015/12/21/webextensions-in-firefox-45-2/

**Comment by anselmh** [comment]
Hint, hint. There’s more to come soon in Firefox making it even easier to port a Chrome extension to a Firefox one: http://xulforge.com/blog/2016/03/porting-a-chrome-extension-to-webextensions-in-half-a-step/#comment-123898

**Comment by sindresorhus** [comment]
Oh nice. That's a good move. I'll reopen this so no one wastes time manually porting this to Firefox when it's so close to being an automatic process.

**Comment by JeroenDeDauw** [comment]
+1 for a port

**Comment by sindresorhus** [comment]
@JeroenDeDauw Use reactions. https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by dvcrn** [comment]
All right, I had some free time and tried porting this with WebExtensions. There are some minor changes and tweaks needed from what I've seen so far but in general, it looks very straight forward. 

How should I proceed with this? Does this make sense in a separate repo or should I PR my changes into this one here?

**Comment by sindresorhus** [comment]
What changes needed? According to the linked article there should be need for none. I'd prefer to wait for that. As for where to have it. Happy to host it here if someone offers to do the publishing of new releases the Firefox addons store.

**Comment by dvcrn** [comment]
I debugged this a little and it seems that firefox doesn't like the `const` keyword in for loops:

- https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L58-L60
- https://github.com/sindresorhus/refined-github/blob/master/extension/reactions-avatars.js#L36-L38

Both are causing a SyntaxError. Replacing it with `let` fixes it.

Then we need to add the applications key to the [manifest.json](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications)

This at least let's the extension run without errors. I didn't go through the entire list but on the first look a few things like quick edit README, show user avatars next to reactions or show patch / diff links don't quite work yet. 
Other things like live reloading, collapsible files in pull requests or the release tab seem to work. 

Going to check that when I have more time :)

**Comment by sindresorhus** [comment]
> I debugged this a little and it seems that firefox doesn't like the const keyword in for loops:

Try Firefox Nightly. That was also an issue with older Chrome versions not being spec compliant.

> Then we need to add the applications key to the manifest.json

That will go away: https://wiki.mozilla.org/WebExtensions/Applications

**Comment by dvcrn** [comment]
> Try Firefox Nightly. That was also an issue with older Chrome versions not being spec compliant.

hrrm, I'm on the developer edition. Guess that's not nightly enough. I'll report back later

**Comment by silverwind** [comment]
FWIW, Dev is around 6 weeks behind Nightly.

**Comment by hkdobrev** [comment]
Firefox 48 (and 49) is now released. So there's no need for [changing the manifest now](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/applications) - https://github.com/sindresorhus/refined-github/issues/243#issuecomment-224372899

Anyone who wants to try and make this extension work on Firefox is welcome!

@dvcrn @bogas04 Do you want to try that out?

**Comment by bogas04** [comment]
Sure, i'll [try](https://github.com/bogas04/refined-github) it out.

**Comment by bogas04** [comment]
I tried [installing](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox) it as WebExtension and it just worked. Also, from the [compatibility list](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities), it seems there's no conflict. Further, debugging it gave no console error apart from "empty string passed to document.getElementById".

So I guess we can simply ship it to [AMO](https://addons.mozilla.org/en-US/firefox/). 

Do you have any UI check list to ensure all features are working ?

**Comment by hkdobrev** [comment]
@bogas04 That's great news! Thanks! I didn't expect this to be so easy.

Could you check if the console error is indeed from the extension? This seems a bit worrisome.

Regarding a checklist probably we can go through what's listed in the readme and try it out one by one.

Here's a table with what I found out:

Feature                                                                         | Chrome | Firefox
--------------------------------------------------------------------------------|--------|--------
Mark issues and pull requests as unread (They will reappear in Notifications)   |   [x]  |   [ ]
Linkifies branch references in pull requests                                    |   [x]  |   [x]
Linkifies issue/PR references in issue/PR titles                                |   [x]  |   [x]
Adds a 'Releases' tab to repos (g r hotkey)                                     |   [x]  |   [x]
Adds user avatars to Reactions                                                  |   [x]  |   [ ]
Adds a quick edit button to the readme                                          |   [x]  |   [x]
Shows current filename in the sticky pull request header                        |   [ ]  |   [ ]
Adds blame links for parent commits in blame view                               |   [x]  |   [x]
Shows user's full name in comments                                              |   [x]  |   [ ]
Improves readability of tab indented code                                       |   [x]  |   [ ]
Adds a 'Copy' button to the file view                                           |   [x]  |   [x]
Adds a shortcut to quickly delete a forked repo                                 |   [x]  |   [x]
Adds ability to collapse/expand files in a pull request diff                    |   [x]  |   [x]
Adds option to view diffs without whitespace changes (d w hotkey)               |   [ ]  |   [ ]
Adds links to patch and diff for each commit                                    |   [ ]  |   [ ]
Differentiates merge commits from regular commits                               |   [x]  |   [x]
Easier copy-pasting from diffs by making +/- signs unselectable                 |   [x]  |   [x]
Shows the reactions popover on hover instead of click                           |   [x]  |   [x]
Supports indenting with the tab key in textareas like the comment box           |   [x]  |   [x]
Automagically expands the news feed when you scroll down                        |   [x]  |   [x]
Hides other users starring/forking your repos from the newsfeed                 |   [x]  |   [x]
Prompts you when pressing Cancel on an inline comment in case it was a mistake  |   [x]  |   [x]
Moves the dashboard organization switcher to the right column                   |   [x]  |   [x]
Adds a Trending link to the global navbar. (g t hotkey)                         |   [x]  |   [x]
Removes annoying hover effect in the repo file browser                          |   [x]  |   [x]
Removes the comment box toolbar                                                 |   [x]  |   [x]
Removes tooltips                                                                |   [x]  |   [x]
Copy canonical link to file when the y hotkey is used                           |   [x]  |   [x]

I've specifically included a column for Chrome as there are a couple of things not working at the moment and they are not because of Firefox and I wanted to show that as well.

So we have 4 features working on Chrome, not working on Firefox:

- [ ] Mark issues and pull requests as unread
- [ ] Adds user avatars to Reactions
- [ ] Shows user's full name in comments
- [ ] Improves readability of tab indented code

**Comment by hkdobrev** [comment]
@bogas04 @sindresorhus @paulmolluzzo @DrewML I've updated the description of the issue to track what's working on Firefox and what's not. Do you want to create separate issues for each one? Any ideas on why these are not working?

**Comment by bogas04** [comment]
@hkdobrev I'm sorry I won't be able to contribute this week, busy with work. I'll check over weekend probably !

**Comment by sindresorhus** [comment]
@hkdobrev Some of the ones that are not working on only Firefox uses `chrome.storage`. Not sure whether that's implemented fully in Firefox. Did you test with Firefox nightly? If something works there, we can just wait.

I think it's easier to just keep it here for now until we've had some time to look into the issues and determined how hard it would be to fix.

**Comment by hkdobrev** [comment]
@sindresorhus From what I could tell `chrome.storage` is working without problems with the extension running on stable Firefox.

**Comment by AdrianoCahete** [comment]
Any update on this port?

**Comment by gluons** [comment]
Trying it on Firefox 53 (Developer Edition). Not bad. 👍 

![firefox port issue 71 sindresorhus refined github](https://cloud.githubusercontent.com/assets/4688092/23093491/00bd3930-f618-11e6-9ad5-37c306405953.png)

**Comment by jgierer12** [comment]
Since most of these are working now, I'll try to fix the remaining bugs.
