### ISSUE TITLE
Easy copy paste of branches and filenames in PR's

### ISSUE THREAD

**Issue by edhgoose** [sindresorhus/refined-github#77]
When reviewing a PR from a colleague, I often want to check it out on my local machine. I often do this by copying the branch name from the PR into a shell. More often than not, I don't quite get it right first time and for some reason find it difficult to copy the branch name.

The same applies if I want to look at a specific file (doubly more annoying because of truncated file names in Pull Requests)

The copy button next to sha's in the commits file is handy, so why not add it next to branches too?

E.g.:

![screenshot 2016-03-11 at 23 16 40](https://cloud.githubusercontent.com/assets/1108173/13718164/614f6112-e7df-11e5-95d9-9d92b0afe19a.png)

and

![screenshot 2016-03-11 at 23 20 38](https://cloud.githubusercontent.com/assets/1108173/13718220/ec6c63a8-e7df-11e5-8080-2864babb48f0.png)

**Comment by sindresorhus** [comment]
Why do you need to copy the branch name?

**Comment by edhgoose** [comment]
@sindresorhus I don't know what I was writing last night, the first line was supposed to be much more sensible. Does it make sense now? Apologies!

> When reviewing a PR from a colleague, I often want to check it out on my local machine. I often do this by copying the branch name from the PR into a shell.

**Comment by hkdobrev** [comment]
I can imagine this is needed to check out that branch locally without typing. But I use `hub` for that with the PR URL and you can also configure git to download PR refs which GitHub provides via the git protocol. Then you can check out a PR by its number.

**Comment by paulmolluzzo** [comment]
Do you guys not have git completion? I just fetch, then `gco [first-letter]`<kbd>tab</kbd>. And

**Comment by hkdobrev** [comment]
@paulmolluzzo that won't work with a PR from a new fork.

**Comment by edhgoose** [comment]
@paulmolluzzo A lot of our branches are called `feature-` or quite often if there's multiple branches in the same area we'll have similar branch names. Or `fix-1234-broken-foo` vs `fix-1235-broken-bar`, so tab completion while helpful isn't a silver bullet.

**Comment by paulmolluzzo** [comment]
@edhgoose I totally hear you on the `feature-` prefix.

I found an interesting thing while looking into this problem, and it also solves the issue @hkdobrev brought up: https://help.github.com/articles/checking-out-pull-requests-locally/

You should read the link, but the cliff notes is: `git fetch origin pull/[ID_of_pull_request]/head:[branch_name_you_want_locally]`

Then you can check out the branch as usual, and do whatever you want, but if you push you'll be pushing that new branch to the current repo (not the fork).

Another solution (that this extension hides, funny enough), is to checkout a new branch as usual and just pull from the fork. Again, pushing is going to push to your (the original) repo, not the fork.

With all that in mind, if you're going to copy something to the clipboard, if it's a fork, you want to copy a the `git fetch` command above that interpolates the ID of the PR, and then makes a branch name like `${username}-${fork-branch-name}`.

Anyway, maybe this helps, but I have even less need for this. I'll be making a bash script for it for my dotfiles. :v:

**Comment by edhgoose** [comment]
@paulmolluzzo, interesting. It's surprising how different workflows can be for using the same tool!

It still doesn't quite solve my use case I don't think. I'm leading a private project, and we never fork. The leading part is relevant because I'm trying to help my colleagues frequently. It's just a team of 4 of us developing at the moment, and we always introduce PR's to the original repo. 

While `gcopr 1234` works great, and I could even extend it to say if the second parameter isn't provided then the branch is called something like `pr-1234` automatically, that still doesn't cover our workflow. We sometimes have branches that live longer than PR's (maybe the PR gets closed for further work, or targeted against a new branch), and we often talk about a branch (e.g. "can you just quickly look at branch `foo` and tell me the flobber function is correct?") which gets harder if the branch name I checked it out under is totally different. 

Or in other words: `branch_name_you_want_locally` is exactly what it is remotely, and that's what I'm trying to copy.

**Comment by hkdobrev** [comment]
My general advice (which of course cannot cover all use cases and workflows) is:

- Keep it simple. Use shorter brand names. I know it sounds scary, but one-two words for a branch name is most often enough.
- Keep it simple. Use brand names which start with the specific thing they deal with. E.g. avoid prefixes such as `feature-`, `fix-`, `remove-`, `add-`, `implement-` etc. Instead for a feature called `intercom` you could use `intercorm-integration`, `intercom-remove`, `intercom-fix-chatheads`.
- Avoid features consisting of two words. In most cases the first word in the branch name should show what it relates to.
- Use `git fetch` and `git branch --remote` (`-r` for short) to show you remote branches. Use tab completion, smart copy-pasting using in the terminal (Iterm2 latest builds), or just plain and simple copy-and-paste using select or even simpler typing out the short branch name.
- Use [`hub`](https://hub.github.com/) or at least the PR refs GitHub offers together with some aliases and functions like the ones above.

In any case, try to use at least somewhat consistent branch names across your organisation.

If you rely on a visual copy button for the branch name and it's faster for you to move your mouse and click the button instead of already checking out the branch locally, then I'd say the lack of the button is not your main problem with the branch names. I mean that in the best possible way, I'm sorry if it sounds condescending.

**Comment by edhgoose** [comment]
Interesting. Once again, fascinating that you use the tool completely differently.

One other case which I think you haven't covered which, now that I've had this running for a few days, I use really regularly is to copy the branch into another tool (i.e. not into a terminal). The best example of this is deploying a branch via Jenkins. Jenkins doesn't have an autocomplete (that I'm aware of).

How would you handle that?

**Comment by hkdobrev** [comment]
> The best example of this is deploying a branch via Jenkins.
Why do you need to copy paste a branch in a CI server? It should get it automatically. I've previously used Jenkins and never had to deal with branch names other than initial set up.

Anyway this is still not hard if you use short brand names.

**Comment by sindresorhus** [comment]
I think a copy button for the file paths of the files in the diff could be useful once in awhile, but I've never needed to copy a branch name.

**Comment by DevVersion** [comment]
I also confirm that this is a very useful feature. Mostly when a user files a PR on the upstream and we need to test it locally, then we'll checkout the branch. 

I know there're is Git CLI Autocompletion and other Scripts, which are applying the PR's patch.
But I also run often into the use-case, where I need to copy the branch name.

And mostly those branch names are not consistent, with a correct prefix (`fix/`, `feat/`, `chore` etc.), so it is difficult to finde them through typing.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/refined-github/pull/78#issuecomment-203835026

-

Copying the filename might have been useful once in awhile, but not very often, and I just realized it could be done a lot better in a separate extension. Many editors supports custom URL schemes for opening files. So you could make it so that when you click a filename it opens directly in your editor (customized in an options page). That would be so cool!

**Comment by Empty2k12** [comment]
<img width="739" alt="Screenshot 2019-04-01 at 18 35 23" src="https://user-images.githubusercontent.com/6954968/55344177-05821f80-54ad-11e9-8fd0-8c70aae49591.png">

Github added this natively. Who could have known people actually want this? /s

**Comment by bfred-it** [comment]
Yes, people who don’t know better will keep using slower methods of doing business :)

**Comment by bfred-it** [comment]
GitHub has to help absolute beginners, Refined GitHub doesn’t. 🙂
