### ISSUE TITLE
Close dropdowns when they scroll out of view

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#778]
From https://github.com/sindresorhus/refined-github/pull/735#issuecomment-340138827

Can use `IntersectionObserver`.

**Comment by hkdobrev** [comment]
Specifically, because of my workflow when reviewing (described here: https://github.com/sindresorhus/refined-github/pull/735#issuecomment-339183475) I'd prefer not to do that.

Even though it sounds nice, clicking somewhere to close is easy and I want to keep it explicit for the review dropdown. If you this could be done for other dropdowns, but not for the review dropdown, I'm fine with it.

**Comment by sindresorhus** [comment]
I agree it would be annoying for the review dropdown, but for the other ones, I think it's ok.

**Comment by tom-sherman** [comment]
Hi all, I've got a working version of this new feature here: https://github.com/tom-sherman/refined-github/tree/close-out-of-view-dropdowns

It currently only works on some dropdowns, namely ones that use `details` elements. I'll submit a PR when I have all of the dropdowns working 👍
