### ISSUE TITLE
Removes content from the dashboard

### ISSUE THREAD

**Issue by Keith94** [sindresorhus/refined-github#822]
This add-on removes a lot of content from the activity feed on the dashboard/homepage. Why is that?

### With the add-on

![firefox_2017-11-18_23-53-03](https://user-images.githubusercontent.com/5490615/32988566-c5fc54cc-ccbb-11e7-8a38-d78932146c46.png)

### Without the add-on

![firefox_2017-11-18_23-52-52](https://user-images.githubusercontent.com/5490615/32988568-c9305abc-ccbb-11e7-97c8-f8156d3681f2.png)

**Comment by hkdobrev** [comment]
This is one of the first features it promotes: https://github.com/sindresorhus/refined-github#highlights

> **Dashboard cleanup**

See the list here: https://github.com/sindresorhus/refined-github#declutter

It's an opinionated extension which removes things which we believe are not really useful on a regular basis to GitHub power users.

You are free to either:

- not use it
- override styles https://github.com/sindresorhus/refined-github#customization
- suggest specific changes in an issue/PR so we could discuss whether they make sense :)

Cheers!

**Comment by Keith94** [comment]
Just add an option to disable this "Dashboard cleanup"? It removes way too much, making the dashboard useless for my case.

**Comment by yakov116** [comment]
@Keith94 Please search you will see this has been said many times. (For example #561)
You can use stylish to correct what you would like.

**Comment by Keith94** [comment]
That's hardly a user-friendly solution. I hope this is made configurable some day.

**Comment by yakov116** [comment]
@Keith94 I think thats a bit harsh. If that is the only thing about the extension you have an issue with then I think that is a great idea.

**Comment by hkdobrev** [comment]
@Keith94 The default is like that because if you follow hundreds of people and watch hundreds of repos - pushes and branches quickly become irrelevant to you and most likely you follow events like this in GitHub notifications for things you're participating in.

With that said I don't see a good reason changing the default. It is already configurable - either don't use the extension or override the CSS. We have an option for "Hide other users starring/forking your repos". This option is also hiding things by default as these events are not useful for power users.

>  I hope this is made configurable some day.

The maintainers of the extension are extremely welcoming to new suggestions, but please bring good arguments from the point of view of the target audience.

I'd also like to iterate this is an opinionated project.

**Comment by yakov116** [comment]
@hkdobrev I have a very simple use case.
I am a manager and the way I tell if the workers are doing their work is by seeing when they pushed.

**Comment by hkdobrev** [comment]
@yakov116 I'm in a similar position, but pushes are too much for me. I've configured to receive emails for pushes for things I'm participating in. Seeing pushes from coworkers in the dashboard completely eliminate other things I want to see on my dashboard during work hours.

**Comment by bfred-it** [comment]
This can now be disabled: https://github.com/sindresorhus/refined-github/pull/988
