### ISSUE TITLE
Improve profile page

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#89]
From https://github.com/sindresorhus/refined-github/issues/87.

-

Personally I'd like to see the `Contributions graph` gone as it's completely useless and even inaccurate as it only shows commits, but I guess that would be too controversial as many people think they need it, but they don't.

Another idea would be to fetch some of the items from the `Activity` tab and show them there. I often go to the `Activity` tab to see what the author worked on last. We could either fetch it or do an iframe.

Any other ideas? What would be useful to have on a profile landing page? What could we remove?

**Comment by hkdobrev** [comment]
> Personally I'd like to see the Contributions graph gone as it's completely useless and even inaccurate as it only shows commits

The contributions graph shows issues and PRs as well though.

---

1. Contributions graph
I'll vote to keep it. It's helpful to see the user has many contributions on other repositories even when they don't have much repositories themselves.

2. Activity tab
We can show the most recent activity in the lower half of the user profile I guess.

3. Popular repositories
What I'd really love to see in the user page is the ability to expand the popular repositories and see more than 5.

**Comment by sindresorhus** [comment]
> The contributions graph shows issues and PRs as well though.

Right. But it misses comments and closing of issues/PRs, which maintainers spend most their time on, meaning PR review, issue triage, etc.

> Contributions graph

Sure. I'll just remove it locally.

> Activity tab

:+1: 

> Popular repositories

:+1: 

-

Some other ideas:

- `Repositories contributed to` isn't very useful as it easily gets out of date and isn't really representative of actual contributions. I had jQuery there for years after two small contributions. I wonder if we can come up with a better algorithm for this. Maybe `Repositories contributed to recently`. Similar to `Hot` tabs in many websites (Reddit/StackOverflow/etc) where we take into account recently contributed to repos and how long ago it was.
- Remove the two `streaks` columns from the contribution graph? They have no practical purpose.
- Remove `Joined on Dec 21, 2009`. It gives no indication of when the user actually started contributing. I joined GitHub in 2009, but didn't use it actively until 2012.

**Comment by paulmolluzzo** [comment]
I think it's too ambitious for this project, but I'd prefer to organize my repositories instead of just the top 5 starred repos. Or include something like a badge or tag if you want to promote a repo.

I agree with @sindrsorhus about public activity. That's the most accurate picture of what some has done, but it's the last tab. I'd replace "Contributions" with Acitivity, or at least put it higher.

**Comment by paulmolluzzo** [comment]
> The contributions graph shows issues and PRs as well though.

@hkdobrev that's only for new Issues or PRs. If you open an Issue and then spend a week discussing it in the comments you only get "credit" for the opening it.

As @sindresorhus mentioned, it's kind of a detraction from making contributions. Is discouraging to users when they're "empty" and people chase the green squares. I almost wonder if people would do more or less if they didn't think there was a public "scorecard".

**Comment by paulmolluzzo** [comment]
Whoops, fat fingered the close button. :disappointed:

**Comment by raphaelokon** [comment]
@sindresorhus 
I totally agree on the Contributions graph.
Personally I'd like to have the option to decide which parts of my profile are public or private or visible to teams etc.. I generally like that you can have a private profile at Bitbucket.

**Comment by hzoo** [comment]
> Maybe Repositories contributed to recently. 

At the time I thought it would be cool to just augment the contributions graph to include comments as well. (maybe https://www.githubarchive.org/ for historical data)

I think being able to show activity that is non-code related is useful (similar to https://github.com/hzoo/contributors-on-github/issues/2).

And for certain orgs it would be good to show/graph activity across an org (https://github.com/hzoo/contributors-on-github/issues/8) somewhere (if you don't use a monorepo)?

Being able to separate those one-off commits of repos vs something you are consistently contributing to or maintaining would be cool and you could see trends and stuff.

I thought it would be interesting to make like a sparkline or something to see activity on a specific repo, and seeing the major projects a user has worked on would be useful. (So just a better timeline of what is actually worked on)

**Comment by paulmolluzzo** [comment]
> I thought it would be interesting to make like a sparkline or something to see activity on a specific repo

@hzoo when you look at Repositories there's a graph in the background. It'd be nice to emphasize that with more obvious colors and some amplification. The scale seems to be drawn at an absolute (0-100) so a commit or two here and there seems small. If it were relative (0-most ever for repo) then it'd seem more active relative to the repos usual activity. For a small repo 4 commits in a day is a big blip. (Not sure if that's clear...)

**Comment by sindresorhus** [comment]
Relevant: http://erik.io/blog/2016/04/01/how-github-contribution-graph-is-harmful/

**Comment by bfred-it** [comment]
I agree with the article, but I kinda like using the graph to tell whether a user is active or not. If someone is active I may do a PR, otherwise I just open an issue and wait for the answer, if it ever comes. 

Perhaps it could be replaced by some sort of activity indicator? Activity: rare, medium, frequent

**Comment by hkdobrev** [comment]
Update from GitHub on the contribution graph: https://github.com/blog/2173-more-contributions-on-your-profile

Just wanted to put it here if anyone missed it.

**Comment by hkdobrev** [comment]
Thanks GitHub! https://github.com/blog/2191-pin-repositories-to-your-github-profile

**Comment by hkdobrev** [comment]
OK, GitHub has now added several improvements to the user profile since this issue was opened:

- [List anonymous private contributions on your contribution graph](https://github.com/blog/2173-more-contributions-on-your-profile)
- [Profile bios](https://github.com/settings/profile?focus_bio=1)
- [Pin and reorder repositories on your profile](https://github.com/blog/2191-pin-repositories-to-your-github-profile)
- [More things listed in the contribution graph](https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features#see-whats-behind-your-green-squares)

Comments are still missing from the contribution timeline, but we have #320 for that.

Do you think we can close this issue or is there anything else here?

**Comment by sindresorhus** [comment]
I still feel the profile page could be a lot more useful than it is, but I don't have any specific requests that are easily solvable by us, so I guess we can close it.
