### ISSUE TITLE
Add octohint

### ISSUE THREAD

**Issue by ocombe** [sindresorhus/refined-github#897]
Hello, could you consider adding octohint to refined github ? https://medium.com/@pd4d10/introducing-octohint-e1a3e4b80c47
Or maybe add a similar feature, it's super useful :)

**Comment by bfred-it** [comment]
There’s no need to merge extensions. You can install as many as you need.

**Comment by hkdobrev** [comment]
@ocombe You could submit a PR to mention in the readme in the related extensions section?

**Comment by ocombe** [comment]
@bfred-it I know but since it's related it would make sense to have this in refined github, I prefer to have one good extension than multiples ones that might not have the same level of support (because of the popularity of the project)

**Comment by hkdobrev** [comment]
Exactly because of the popularity of the project maintenance becomes harder and harder. It's quite easier to make it play nice with other extensions if they clash rather than bundling everything together.

Similar discussions:

- https://github.com/sindresorhus/refined-github/issues/151#issuecomment-208697642
- https://github.com/sindresorhus/refined-github/issues/669#issuecomment-322128664
