### ISSUE TITLE
Automatically delete a branch after PR merge

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#908]
Is there any reason not to delete it?

**Comment by hkdobrev** [comment]
👍

However, here's a case where you don't want to delete - e.g. you have a long-running branch the git-flow where you have `development`, release branches, hotfix branches and then you can create a PR to review what would be merged and merge it, but don't delete the long-running branch.

So I think this could be either be an option in the UI checked by default that you want to merge and delete or an option in the extension for all merges one does.

For the actual button, we have 2 cases where the button would be missing or disabled:

- you don't have permission to delete the branch because you are not a collaborator on the repo of the head PR branch
- the head branch of the PR is a base branch of another PR - I remember you cannot delete in this case, but not sure what the UI was.

**Comment by bfred-it** [comment]
Yeah, it’s auto click the button if it’s found, that’s not an issue.

Hmmm and the long-running branches make this possible feature a bit troublesome. Maybe it can just be part of #865

**Comment by bfred-it** [comment]
Closing as duplicate of #1024
