### ISSUE TITLE
Jump to bottom link appears in commits tab and does nothing

### ISSUE THREAD

**Issue by leggsimon** [sindresorhus/refined-github#914]
The jump to bottom link appears in the commits tab, in the commits tab there is no element with the id `#partial-timeline-marker` so the link just doesn't do anything.

I think this line needs to be updated to be 
https://github.com/sindresorhus/refined-github/blob/189377fc323e1f802ebaca299830be19a4f6feaa/source/features/add-jump-to-bottom-link.js#L7

```js
if (!meta || jumpToBottomLink || !select.exists('#partial-timeline-marker')) {
  ...
}
```

**Comment by jgierer12** [comment]
Are you on https://github.com/sindresorhus/refined-github/tree/master? This shouldn't happen because since #912 we check if we're on the PR 'Conversations' tab before adding the link:

https://github.com/sindresorhus/refined-github/blob/189377fc323e1f802ebaca299830be19a4f6feaa/source/content.js#L146-L148

**Comment by leggsimon** [comment]
Oh, yes sorry. I noticed the bug where it was being added multiple times and originally was raising that as an issue. Saw that that had been fixed but didn't realised this one had as well.
